import type { QuestionTranslationMap } from '../types'

export const architecturePracticalVi: QuestionTranslationMap = {

  'ap-001': {
    question: 'Thiết kế trình chỉnh sửa tài liệu cộng tác theo thời gian thực như Google Docs.Kiến trúc giao diện người dùng của bạn là gì?',
    answer: '1',
    explanation: 'Việc chỉnh sửa cộng tác yêu cầu: (1) Giải quyết xung đột - CRDT (Yjs, Automerge) hoặc OT (Chuyển đổi hoạt động).CRDT được ưu tiên sử dụng vào năm 2025 vì chúng hoạt động ngang hàng và ngoại tuyến.(2) Khung soạn thảo - ProseMirror hoặc Slate cung cấp mô hình tài liệu có cấu trúc ánh xạ tới các hoạt động CRDT.(3) Vận chuyển - Kết nối WebSocket với logic kết nối lại, bó tin nhắn và mã hóa nhị phân (Yjs sử dụng giao thức đồng bộ nhị phân hiệu quả).(4) Nhận thức - vị trí con trỏ, phạm vi lựa chọn, sự hiện diện của người dùng thông qua giao thức nhận thức nhẹ.(5) Persistence — chụp ảnh nhanh định kỳ tới máy chủ, với nhật ký cập nhật CRDT cho lịch sử.(6) Hoàn tác/làm lại - phải dành cho mỗi người dùng, không phải toàn cầu, được xử lý bởi người quản lý hoàn tác của thư viện CRDT.',
  },
  'ap-002': {
    question: 'Trang web thương mại điện tử của bạn cần xử lý lưu lượng truy cập Thứ Sáu Đen (tải bình thường gấp 100 lần).Chiến lược tối ưu hóa giao diện người dùng của bạn là gì?',
    answer: '1',
    explanation: 'Tối ưu hóa Thứ Sáu Đen có nhiều lớp: CDN/Edge — phục vụ nội dung tĩnh và các trang được kết xuất trước từ biên, giảm hơn 90% tải ban đầu.Bộ nhớ đệm - Tiêu đề bộ nhớ đệm HTTP (Kiểm soát bộ đệm: cũ trong khi xác thực lại) cho phép trình duyệt hiển thị nội dung được lưu trong bộ nhớ đệm trong khi tìm nạp dữ liệu mới.Tách mã - chỉ tải JS thanh toán khi người dùng bắt đầu mua hàng.Quản lý yêu cầu — gỡ bỏ/xếp hàng các nhấp chuột thêm vào giỏ hàng, sử dụng giao diện người dùng lạc quan.Giảm tải - gắn cờ tính năng để tắt công cụ đề xuất, tiện ích trò chuyện, phân tích đang tải.Xuống cấp nhẹ nhàng — nếu API kho hàng chậm, hãy hiển thị nút "kiểm tra tính khả dụng" thay vì chặn kết xuất.',
  },
  'ap-003': {
    question: 'Thiết kế kiến ​​trúc giao diện người dùng vi mô cho một nhóm lớn gồm hơn 50 nhà phát triển làm việc trên cùng một sản phẩm.Làm thế nào để bạn phân chia quyền sở hữu, triển khai độc lập và tránh sự hỗn loạn?',
    answer: '1',
    explanation: 'Tại hơn 50 nhà phát triển, giao diện người dùng vi mô giải quyết các vấn đề phối hợp: (1) Quyền tự chủ của nhóm — mỗi nhóm triển khai MFE của mình một cách độc lập, không cần đào tạo phát hành.(2) Liên kết mô-đun (Webpack 5 / Rspack) tải điều khiển từ xa khi chạy, do đó shell không cần phải xây dựng lại.(3) Các phần chia sẻ — React, bộ định tuyến, mã thông báo thiết kế được hiển thị dưới dạng các phần tử đơn lẻ từ shell để tránh xung đột phiên bản và làm phồng gói.(4) Giao tiếp - sự kiện tùy chỉnh (được ghép nối lỏng lẻo), thông số URL cho trạng thái MFE chéo.Tránh chia sẻ Redux - nó tạo ra sự kết nối ẩn.(5) Kiểm tra hợp đồng - mỗi MFE hiển thị một giao diện được đánh máy;phá vỡ các thay đổi được ghi lại trong CI.(6) Quản trị - nhóm kiến ​​trúc duy trì shell, lib dùng chung và kiểm tra tích hợp.',
  },
  'ap-004': {
    question: 'Triển khai hệ thống cờ tính năng cho phép thử nghiệm A/B mà không cần triển khai lại.Bạn kiến ​​trúc sự tích hợp giao diện người dùng như thế nào?',
    answer: '1',
    explanation: 'Kiến trúc cờ tính năng: (1) Vận chuyển — Sự kiện do máy chủ gửi để cập nhật cờ theo thời gian thực hoặc thăm dò trong khoảng thời gian ngắn.Cờ ban đầu có thể được nhúng vào SSR HTML để tránh flash.(2) Tích hợp phản ứng - FeatureFlagProvider gói ứng dụng, useFlag("new-checkout") trả về biến thể.(3) Phân nhóm ổn định - hash(userId + flagKey) % 100 mang lại tỷ lệ phần trăm triển khai nhất quán.Người dùng luôn nhìn thấy cùng một biến thể.(4) SSR - đánh giá các cờ phía máy chủ để tránh tình trạng hydrat hóa không khớp.(5) Phân tích - mọi kết xuất/hành động được gắn thẻ với các biến thể cờ đang hoạt động đều cho phép phân tích A/B.(6) Dọn dẹp - phát hiện cờ chết thông qua quét mã, loại bỏ PR được tạo tự động.',
  },
  'ap-005': {
    question: 'Thiết kế hệ thống thông báo xử lý tin nhắn chúc mừng, thông báo đẩy và hộp thư đến trong ứng dụng.Bạn kiến ​​trúc giao diện người dùng như thế nào?',
    answer: '1',
    explanation: 'Các lớp hệ thống thông báo: (1) Vận chuyển - WebSocket cho thời gian thực, với dự phòng SSE.Kết nối lại với độ trễ theo cấp số nhân.(2) Dịch vụ thông báo singleton - nhận tất cả thông báo, chuẩn hóa hình dạng, tuyến đường theo loại.(3) Hệ thống con Toast - hàng đợi có hiển thị tối đa (3-5), mức độ ưu tiên (lỗi > cảnh báo > thông tin), loại bỏ trùng lặp bằng hàm băm nội dung, bộ hẹn giờ tự động loại bỏ có thể định cấu hình, các nút hành động.(4) Đẩy - Đăng ký Service Worker, quản lý quyền, dự phòng trong ứng dụng nếu bị từ chối.(5) Hộp thư đến — API REST cho lịch sử phân trang, WebSocket cho các mục mới, chuyển đổi đọc/chưa đọc lạc quan.(6) Trạng thái — tùy chọn thông báo được đồng bộ hóa với chương trình phụ trợ, bộ nhớ đệm ghi đè cục bộ.',
  },
  'ap-006': {
    question: 'Ứng dụng của bạn cần hoạt động ngoại tuyến và đồng bộ hóa khi trực tuyến trở lại.Thiết kế chiến lược đồng bộ hóa ngoại tuyến đầu tiên cho ứng dụng quản lý tác vụ.',
    answer: '1',
    explanation: 'Đồng bộ hóa ngoại tuyến đầu tiên: (1) Lưu trữ - IndexedDB cho dữ liệu có cấu trúc (tác vụ, dự án), API bộ đệm cho nội dung.localStorage quá nhỏ và đồng bộ.(2) Đường dẫn ghi - các đột biến sẽ chuyển đến DB cục bộ ngay lập tức, được thêm vào hàng đợi hộp thư đi với dấu thời gian và loại hoạt động.(3) Đồng bộ hóa — khi kết nối lại, sắp xếp hộp thư đi theo thứ tự.Máy chủ trả về xung đột.(4) Giải quyết xung đột - đối với các ứng dụng đơn giản, ghi cuối cùng sẽ thắng với dấu thời gian.Đối với các ứng dụng cộng tác, hãy sử dụng CRDT hoặc chuyển đổi hoạt động.Hiển thị giao diện người dùng xung đột cho những thay đổi không thể điều hòa được.(5) Đồng bộ hóa nền - Service Worker SyncManager kích hoạt sự kiện đồng bộ hóa khi kết nối trở lại, ngay cả khi ứng dụng bị đóng.(6) Lập phiên bản - mỗi bản ghi có một vectơ phiên bản;máy chủ từ chối ghi cũ và trả về trạng thái hiện tại để hợp nhất máy khách.',
  },
  'ap-007': {
    question: 'Thiết kế hệ thống quốc tế hóa (i18n) cho một ứng dụng lớn với hơn 20 ngôn ngữ và hỗ trợ RTL.Bạn xử lý các bản dịch, định dạng và bố cục như thế nào?',
    answer: '1',
    explanation: 'i18n ở tỷ lệ: (1) Định dạng thông báo - ICU xử lý các trường hợp phức tạp: "{count, số nhiều, một {# mục} khác {# mục}}".Thư viện: Reac-intl, next-intl hoặc i18next.(2) Bản dịch tách mã - chỉ tải miền địa phương hiện tại + không gian tên tuyến đường hiện tại.Tải nhanh những người khác trên điều hướng.(3) RTL - Thuộc tính logic CSS (bắt đầu/kết thúc so với trái/phải) làm cho bố cục hoạt động theo cả hai hướng.Thuộc tính dir="rtl" trên html.(4) Định dạng - không bao giờ định dạng ngày/số theo cách thủ công.Sử dụng Intl.DateTimeFormat, Intl.NumberFormat với ngôn ngữ.(5) Tích hợp CI - phát hiện bản dịch bị thiếu trong CI, tự động hóa PR dịch thuật.(6) Giả bản địa hóa - thay thế các chuỗi bằng các biến thể có dấu (ví dụ: "Héĺĺö") để phát hiện trực quan các chuỗi chưa được dịch và kiểm tra khả năng mở rộng văn bản.',
  },
  'ap-008': {
    question: 'Trang tổng quan của bạn tải 12 tiện ích, mỗi tiện ích thực hiện lệnh gọi API riêng.Tải lần đầu mất 8 giây.Làm thế nào để bạn tối ưu hóa?',
    answer: '1',
    explanation: 'Tối ưu hóa bảng điều khiển được phân lớp: (1) Mạng — Điểm cuối BFF tổng hợp dữ liệu giúp giảm các chuyến đi khứ hồi từ 12 xuống 1-2.(2) Ưu tiên - tải các vật dụng quan trọng (KPI, doanh thu) trước;đề xuất và nguồn cấp dữ liệu hoạt động bị trì hoãn.(3) Bộ nhớ đệm - Truy vấn TanStack với staleTime hiển thị dữ liệu được lưu trong bộ nhớ cache ngay lập tức.Tiêu đề Kiểm soát bộ đệm HTTP cho phép bộ đệm của trình duyệt.(4) Hiển thị - Ranh giới hồi hộp trên mỗi tiện ích với các dự phòng khung.Truyền phát SSR nếu sử dụng Next.js/Remix.(5) Ảo hóa — các tiện ích ngoài màn hình chỉ được hiển thị khi được cuộn vào chế độ xem bằng IntersectionObserver.(6) Điều này thường làm giảm tải cảm nhận xuống dưới 2 giây.',
  },
  'ap-009': {
    question: 'Bạn cần xây dựng một bảng Kanban kéo và thả phức tạp với các cột và thẻ có thể sắp xếp lại được.Cách tiếp cận nào mang lại UX và khả năng bảo trì tốt nhất?',
    answer: '1',
    explanation: 'Kéo và thả vào năm 2025: dnd-kit là phiên bản kế thừa của React-beautiful-dnd (hiện không được bảo trì).Các quyết định chính: (1) Thư viện - dnd-kit cung cấp các cảm biến (con trỏ, bàn phím, cảm ứng), thuật toán va chạm và các nguyên hàm có thể sắp xếp.(2) Trạng thái - duy trì thứ tự cột/thẻ ở trạng thái, áp dụng các cập nhật lạc quan ở đầu kéo, điều chỉnh với phản hồi của máy chủ.(3) Hiệu suất - DragOverlay hiển thị bên ngoài cây có thể sắp xếp, ngăn chặn việc hiển thị lại tốn kém trong quá trình kéo.(4) Khả năng truy cập - cảm biến bàn phím cho phép Tab lấy nét, Space để chọn, Phím mũi tên để di chuyển, Space để thả.(5) HTML5 DnD gốc có khả năng hỗ trợ di động kém, không có tùy chỉnh xem trước kéo và hành vi trình duyệt không nhất quán.',
  },
  'ap-010': {
    question: 'Nhóm của bạn đang xây dựng một thư viện thành phần.Cách hiệu quả nhất để phát triển và ghi lại các thành phần một cách riêng biệt là gì?',
    answer: '1',
    explanation: 'Storybook là tiêu chuẩn ngành để phát triển thành phần: (1) Câu chuyện - mỗi biến thể của thành phần là một câu chuyện (nút chính, nút bị tắt, nút tải).(2) Điều khiển - tự động tạo điều khiển prop từ các loại TypeScript thông qua autodocs.(3) Kiểm tra - các chức năng phát mô phỏng tương tác của người dùng để kiểm tra tích hợp.(4) Hồi quy trực quan - Ảnh chụp màn hình chụp Chromatic hoặc Percy để phát hiện những thay đổi hình ảnh ngoài ý muốn.(5) Tài liệu - Các trang MDX kết hợp Markdown với các bản trình diễn thành phần trực tiếp.(6) Đánh giá thiết kế - xuất bản dưới dạng trang tĩnh để các nhà thiết kế xem xét mà không cần chạy ứng dụng.',
  },
  'ap-011': {
    question: 'Thiết kế một chiến lược giám sát và quan sát lỗi giao diện người dùng.Bạn phát hiện, báo cáo và phân loại lỗi trong quá trình sản xuất như thế nào?',
    answer: '1',
    explanation: 'Khả năng quan sát sản xuất: (1) Ranh giới lỗi - bao bọc các khu vực tính năng quan trọng và cấp độ tuyến đường.Hiển thị giao diện người dùng dự phòng, báo cáo lỗi với ngăn xếp thành phần.(2) Trình xử lý chung - window.onerror cho lỗi đồng bộ hóa, window.onunhandledrejection cho không đồng bộ.(3) Tích hợp Sentry - tải lên bản đồ nguồn trong quá trình xây dựng (giữ chúng ở chế độ riêng tư), để các dấu vết ngăn xếp được rút gọn ánh xạ tới mã gốc.(4) Làm giàu bối cảnh - đính kèm userId, tuyến đường, ảnh chụp nhanh trạng thái Redux, cờ tính năng cho mọi sự kiện.(5) Các chỉ số quan trọng về trang web — theo dõi LCP, INP (FID thay thế), CLS qua thư viện các chỉ số quan trọng về trang web, báo cáo cho bộ phận phân tích.(6) Cảnh báo - tỷ lệ lỗi > 1% số phiên kích hoạt PagerDuty.Tương quan với dấu thời gian triển khai để đưa ra quyết định khôi phục nhanh chóng.',
  },
  'ap-012': {
    question: 'Ứng dụng của bạn có tính năng tìm kiếm kích hoạt yêu cầu API sau mỗi lần nhấn phím.Người dùng phàn nàn rằng nó chậm và lag.Sửa chữa tiêu chuẩn là gì?',
    answer: '1',
    explanation: 'Tối ưu hóa tìm kiếm: (1) Gỡ lỗi - trì hoãn lệnh gọi API cho đến khi người dùng tạm dừng nhập (tiêu chuẩn 300-500ms).Thư viện: lodash.debounce, usehooks-ts hoặc hook tùy chỉnh.(2) AbortController - hủy yêu cầu trước đó khi yêu cầu mới kích hoạt, ngăn chặn tình trạng chạy đua trong đó phản hồi cũ hơn ghi đè lên yêu cầu mới hơn.(3) Độ dài truy vấn tối thiểu - không tìm kiếm chuỗi ký tự 1-2.(4) Bộ đệm - TanStack Query lưu trữ các kết quả tìm kiếm trước đó, do đó việc nhập lại truy vấn là ngay lập tức.(5) Giao diện người dùng lạc quan - hiển thị công cụ quay vòng ngay lập tức khi thay đổi đầu vào, trao đổi kết quả khi sẵn sàng.Điều này làm giảm 80-90% lệnh gọi API và loại bỏ cảm giác lag.',
  },
  'ap-013': {
    question: 'Thiết kế kiến ​​trúc phân tích và theo dõi sự kiện cho một SPA lớn.Làm cách nào để bạn đảm bảo chất lượng dữ liệu, hiệu suất và trải nghiệm của nhà phát triển?',
    answer: '1',
    explanation: 'Phân tích trên quy mô lớn: (1) Lược đồ - Liên minh phân biệt đối xử TypeScript cho các sự kiện: type AnalyticsEvent = { name: "product_viewed";đạo cụ: { ProductId: chuỗi } } |... Điều này giúp phát hiện lỗi chính tả và các thuộc tính bị thiếu tại thời điểm biên dịch.(2) Mẫu nhà cung cấp — <AnalyticsProvider> đưa tính năng theo dõi qua ngữ cảnh.Các thành phần sử dụng hook useTrack().Dễ dàng hoán đổi Phân đoạn/Biên độ/tùy chỉnh.(3) Hiệu suất - các sự kiện hàng loạt (xóa cứ sau 5 giây hoặc 10 sự kiện), sử dụng navigator.sendBeacon() khi dỡ trang để phân phối đáng tin cậy.(4) Tự động theo dõi - thay đổi tuyến đường, kiểu nhấp chuột, độ sâu cuộn được theo dõi một cách khai báo.(5) Quyền riêng tư - PII đã được kiểm soát phía khách hàng, chế độ đồng ý được tôn trọng.(6) DX - bảng gỡ lỗi hiển thị các sự kiện trong nhà phát triển, xác thực lược đồ trong CI ngăn chặn việc gửi các sự kiện không được nhận dạng.',
  },
  'ap-014': {
    question: 'Thiết kế hệ thống kiểm soát truy cập dựa trên quyền và vai trò (RBAC) cho một ứng dụng giao diện người dùng phức tạp với hơn 10 vai trò và quyền cấp tài nguyên chi tiết.',
    answer: '1',
    explanation: 'RBAC giao diện người dùng: (1) Mô hình quyền - vai trò (quản trị viên, người chỉnh sửa, người xem) ánh xạ tới các quyền (hóa đơn: chỉnh sửa, hóa đơn: xem, người dùng: quản lý).Được tìm nạp dưới dạng quyền được đặt khi đăng nhập.(2) Kiểm tra khai báo — <Can action="edit" Resource="invoice"> hiển thị có điều kiện các phần tử con.Được xây dựng với bối cảnh React + thư viện CASL hoặc tùy chỉnh.(3) Hook - usePermission trả về boolean, được sử dụng cho logic có điều kiện.(4) Bảo vệ tuyến đường - kiểm tra phần mềm trung gian hoặc trình tải trước khi hiển thị tuyến đường.Không được phép → chuyển hướng đến trang 403.(5) QUAN TRỌNG: kiểm tra giao diện người dùng chỉ dành cho UX.Máy chủ phải xác thực mọi đột biến.Frontend chỉ ẩn các nút/tuyến đường.(6) Động - WebSocket đẩy các cập nhật quyền khi quản trị viên thay đổi vai trò, làm mất hiệu lực các quyền được lưu trong bộ nhớ đệm.',
  },
  'ap-015': {
    question: 'Ứng dụng React của bạn hiển thị một bảng có 10.000 hàng.Thao tác cuộn bị giật và trang bị treo khi thực hiện các thao tác lọc.Làm thế nào để bạn sửa nó?',
    answer: '1',
    explanation: 'Hiệu suất danh sách/bảng lớn: (1) Ảo hóa - chỉ hiển thị các nút DOM cho các hàng hiển thị + bộ đệm quét quá mức nhỏ.TanStack Virtual không phụ thuộc vào khung và hỗ trợ chiều cao hàng thay đổi.cửa sổ phản ứng đơn giản hơn cho độ cao cố định.(2) Ghi nhớ - React.memo trên các thành phần hàng ngăn chặn việc hiển thị lại các hàng không thay đổi.(3) Web Workers — lọc/sắp xếp 10K hàng có thể mất 50-100 mili giây, chặn giao diện người dùng.Giảm tải cho công nhân, gửi lại kết quả.(4) Gỡ lỗi - đầu vào bộ lọc bị gỡ bỏ ở tốc độ 200-300ms.(5) Ngăn chặn CSS - chứa: nghiêm ngặt cho trình duyệt biết bố cục của vùng chứa bảng là độc lập, cho phép tối ưu hóa sơn.Sự kết hợp thường đạt được tốc độ cuộn 60 khung hình/giây ngay cả với hàng hơn 100K.',
  },
  'ap-016': {
    question: 'Cửa hàng Redux của bạn có hơn 200 lát và việc gửi đi ngày càng chậm.Các thành phần hiển thị lại một cách không cần thiết.Bạn tái cấu trúc bằng cách nào?',
    answer: '1',
    explanation: 'Redux trên quy mô lớn: Vấn đề số 1 là trộn lẫn trạng thái máy chủ (dữ liệu API) với trạng thái máy khách (chuyển đổi giao diện người dùng, trạng thái biểu mẫu) trong Redux.Việc di chuyển dữ liệu API sang TanStack Query sẽ loại bỏ 60-70% mã Redux và nhận bộ nhớ đệm tự động, tìm nạp lại nền và cập nhật lạc quan.Đối với trạng thái máy khách còn lại: (1) Bộ chọn - createSelector ghi nhớ dữ liệu dẫn xuất;các thành phần chỉ hiển thị lại khi giá trị được chọn thay đổi.(2) Chuẩn hóa - các bảng thực thể phẳng thay vì các đối tượng lồng nhau sẽ ngăn chặn các bản cập nhật xếp tầng.(3) Tách mã - chèn các bộ giảm tốc một cách linh hoạt trên mỗi tuyến đường, do đó cửa hàng không tải các lát không sử dụng.(4) Phần mềm trung gian RTK Listener thay thế redux-saga bằng quy trình làm việc không đồng bộ, được gõ đơn giản hơn.',
  },
  'ap-017': {
    question: 'Một thành phần cần dữ liệu từ 3 điểm cuối API khác nhau (hồ sơ người dùng, đơn đặt hàng của người dùng và đề xuất).Viết logic tìm nạp dữ liệu để xử lý các trạng thái tải, lỗi và thành công một cách tinh tế.',
    answer: 'nhập { useQuery } từ \'@tanstack/react-query\'\n\nhàm useUserDashboard(userId: string) {\nconst profile = useQuery({\nqueryKey: [\'người dùng\', userId],\nqueryFn: () => tìm nạp(`/api/users/${userId}`).then(r => r.json()),\n})\n\nđơn đặt hàng const = useQuery({\nqueryKey: [\'đơn đặt hàng\', userId],\nqueryFn: () => tìm nạp(`/api/users/${userId}/orders`).then(r => r.json()),\nđã bật: !!userId,\n})\n\nkhuyến nghị const = useQuery({\nqueryKey: [\'đề xuất\', userId],\nqueryFn: () => tìm nạp(`/api/users/${userId}/recommendations`).then(r => r.json()),\nđã bật: !!profile.data, // chỉ tìm nạp sau khi tải hồ sơ\nstaleTime: 5 * 60 * 1000, // các đề xuất ít nhạy cảm với thời gian hơn\n})\n\ntrở về {\nhồ sơ: hồ sơ.data,\nđơn đặt hàng: đơn hàng.data,\nkhuyến nghị: khuyến nghị.data,\nĐang tải: profile.isLoading ||đơn đặt hàng.isĐang tải,\nisError: profile.isError ||đơn đặt hàng.isError,\nlỗi: profile.error ||đơn đặt hàng.error,\nisSuymentsLoading: khuyến nghị.isLoading,\n}\n}',
    explanation: 'Truy vấn TanStack xử lý các truy vấn song song và phụ thuộc một cách tinh tế: (1) Các truy vấn độc lập (hồ sơ, đơn hàng) tự động thực hiện song song.(2) Truy vấn phụ thuộc sử dụng cờ được bật - đề xuất chờ hồ sơ.(3) Mỗi ​​truy vấn quản lý bộ đệm, trạng thái tải, lỗi riêng.(4) staleTime kiểm soát tần suất tìm nạp nền cho mỗi truy vấn.(5) Móc kết hợp cung cấp API sạch cho thành phần.(6) Ranh giới lỗi có thể phát hiện các lỗi truy vấn riêng lẻ.Điều này thay thế hàng trăm dòng useEffect + useState + try/catch bản tóm tắt.',
  },
  'ap-018': {
    question: 'Trạng thái toàn cầu và trạng thái máy chủ - nhóm của bạn kết hợp mọi thứ trong Redux (phản hồi API, chuyển đổi giao diện người dùng, trạng thái biểu mẫu, phiên người dùng).Làm thế nào để bạn tái cấu trúc thành một kiến ​​trúc sạch?',
    answer: '1',
    explanation: 'Phân loại trạng thái là thông tin chi tiết quan trọng: (1) Trạng thái máy chủ — dữ liệu bạn không sở hữu, được tìm nạp từ API.TanStack Query xử lý bộ nhớ đệm, tìm nạp nền, cập nhật lạc quan, phân trang.Đây thường là 60-70% những gì các nhóm đưa vào Redux.(2) Trạng thái toàn cầu của máy khách - chế độ chủ đề, thu gọn thanh bên, mã thông báo xác thực, tùy chọn người dùng.Đủ nhỏ cho Zustand (đơn giản hơn) hoặc RTK (nếu đã sử dụng Redux).(3) Trạng thái biểu mẫu — tạm thời, thuộc về thư viện biểu mẫu hoặc trạng thái cục bộ.Đưa các giá trị biểu mẫu vào Redux là một phản mẫu.(4) Trạng thái URL - bộ lọc, thứ tự sắp xếp, phân trang, tab đã chọn.useSearchParams làm cho nội dung này có thể chia sẻ và đánh dấu được.(5) Di chuyển - giải quyết từng phần một, thay thế các truy vấn Redux bằng các móc truy vấn TanStack.',
  },
  'ap-019': {
    question: 'Triển khai chức năng hoàn tác/làm lại cho ứng dụng vẽ.Người dùng có thể thêm hình dạng, di chuyển chúng và thay đổi màu sắc.Viết logic quản lý trạng thái.',
    answer: 'nhập { useCallback, useRef, useState } từ \'Reac\'\n\ngõ Hình dạng = { id: chuỗi;loại: chuỗi;x: số;y: số;màu: chuỗi }\n\nhàm useUndoRedo(initialShapes: Shape[]) {\nconst [hình dạng, setShapes] = useState<Shape[]>(initialShapes)\nconst undoStack = useRef<Shape[][]>([])\nconst redoStack = useRef<Shape[][]>([])\n\nconst pushToUndo = useCallback((currentShapes: Shape[]) => {\nundoStack.current = [...undoStack.current, currentShapes]\nredoStack.current = [] // xóa làm lại hành động mới\n}, [])\n\nconst addShape = useCallback((shape: Shape) => {\nsetShapes(trước => {\npushToUndo(trước)\ntrả về [...trước, hình dạng]\n})\n}, [pushToUndo])\n\nconst moveShape = useCallback((id: string, x: number, y: number) => {\nsetShapes(trước => {\npushToUndo(trước)\nreturn prev.map(s => (s.id === id ? { ...s, x, y } : s))\n})\n}, [pushToUndo])\n\nconst ChangeColor = useCallback((id: string, color: string) => {\nsetShapes(trước => {\npushToUndo(trước)\nreturn prev.map(s => (s.id === id ? { ...s, color } : s))\n})\n}, [pushToUndo])\n\nconst hoàn tác = useCallback(() => {\nif (undoStack.current.length === 0) trả về\nconst trước = undoStack.current[undoStack.current.length - 1]\nundoStack.current = undoStack.current.slice(0, -1)\nsetShapes(hiện tại => {\nredoStack.current = [...redoStack.current, current]\ntrở lại trước đó\n})\n}, [])\n\nconst redo = useCallback(() => {\nif (redoStack.current.length === 0) trả về\nconst next = redoStack.current[redoStack.current.length - 1]\nredoStack.current = redoStack.current.slice(0, -1)\nsetShapes(hiện tại => {\nundoStack.current = [...undoStack.current, current]\nquay lại tiếp theo\n})\n}, [])\n\ntrở về {\nhình dạng,\nthêm hình dạng,\ndi chuyển,\nthay đổi màu sắc,\nhoàn tác,\nlàm lại,\ncó thểUndo: undoStack.current.length > 0,\ncanRedo: redoStack.current.length > 0,\n}\n}',
    explanation: 'Mẫu hoàn tác/làm lại: (1) Ngăn xếp lịch sử - undoStack lưu trữ các trạng thái trước đó, redoStack lưu trữ các trạng thái chuyển tiếp.Việc sử dụng useRef sẽ tránh hiển thị lại các thay đổi của ngăn xếp.(2) Trên mọi hành động - đẩy trạng thái hiện tại về undoStack, xóa redoStack (phân nhánh sẽ xóa lịch sử làm lại).(3) Hoàn tác - bật từ undoStack, đẩy dòng điện sang redoStack, khôi phục trạng thái đã bật.(4) Redo — bật từ redoStack, đẩy dòng điện sang undoStack, khôi phục trạng thái đã bật.(5) Tối ưu hóa cho các ứng dụng lớn - lưu trữ các khác biệt/lệnh thay vì ảnh chụp nhanh đầy đủ (Mẫu lệnh).(6) Giới hạn bộ nhớ - kích thước ngăn xếp giới hạn (ví dụ: 50 mục nhập) để ngăn ngừa các vấn đề về bộ nhớ.Đối với các ứng dụng phức tạp, hãy xem xét các bản vá Immer để có sự khác biệt hiệu quả.',
  },
  'ap-020': {
    question: 'Hai trang khác nhau (Trang tổng quan và Cài đặt) cần có cùng dữ liệu hồ sơ người dùng nhưng phải đồng bộ hóa.Một trang có thể chỉnh sửa hồ sơ.Chiến lược của bạn là gì?',
    answer: '1',
    explanation: 'TanStack Query giải quyết dữ liệu được chia sẻ một cách tinh tế: (1) Cùng một khóa truy vấn = cùng một bộ đệm - useQuery(["user", id]) trên Bảng điều khiển và Cài đặt đọc từ cùng một mục nhập bộ đệm.(2) Đột biến trên Cài đặt — useMutation với onSuccess: () => queryClient.invalidateQueries(["user", id]) kích hoạt tìm nạp lại tự động.Bảng điều khiển hiển thị lại với dữ liệu mới.(3) Cập nhật lạc quan - lệnh gọi lại onMutate có thể cập nhật bộ đệm ngay lập tức: queryClient.setQueryData(["user", id], newData).Nếu đột biến không thành công, onError sẽ quay trở lại.(4) Không cần khoan prop, không ngữ cảnh, không Redux - bộ đệm là trạng thái được chia sẻ.(5) Phát hiện dữ liệu cũ - staleTime và refetchOnWindowFocus đảm bảo dữ liệu mới khi chuyển đổi giữa các tab/trang.',
  },
  'ap-021': {
    question: 'Bạn có thể truy cập vào nút chuyển đổi chủ đề (chế độ tối/sáng) trên toàn bộ ứng dụng.Cách tiếp cận đúng đơn giản nhất là gì?',
    answer: '1',
    explanation: 'Trạng thái chủ đề là trường hợp sử dụng trong sách giáo khoa cho Bối cảnh phản ứng: (1) Nó hiếm khi thay đổi (tần suất cập nhật thấp = không cần quan tâm đến hiệu suất).(2) Nó cần có thể truy cập được trên toàn cầu.(3) Triển khai: ThemeProvider quản lý trạng thái, lưu vào localStorage, đặt thuộc tính data-theme trên <html>.Các biến CSS phản hồi thuộc tính: [data-theme="dark"] { --bg: #1a1a1a }.(4) hook useTheme() cung cấp { theme,oggleTheme }.(5) Khởi tạo từ localStorage → tùy chọn hệ thống (thích-lược đồ màu) → mặc định.(6) Redux là quá mức cần thiết cho việc này.Zustand vẫn ổn nhưng Ngữ cảnh là đủ.',
  },
  'ap-022': {
    question: 'Thành phần React này có vòng lặp kết xuất lại vô hạn.Tìm và sửa lỗi.',
    answer: 'Hàm FetchUser được tạo lại trên mỗi lần kết xuất, khiến phần phụ thuộc useEffect thay đổi và kích hoạt lại vô hạn.Khắc phục: di chuyển FetchUser bên trong useEffect hoặc bọc nó bằng useCallback với [userId] làm phần phụ thuộc.',
    explanation: 'Lỗi: FetchUser được xác định trong nội dung thành phần nên nó nhận được một tham chiếu mới mỗi lần kết xuất.useEffect phụ thuộc vào [fetchUser], xem một tham chiếu mới, chạy lại, gọi setUser/setLoading, kích hoạt kết xuất lại, tạo ra một vòng lặp vô hạn tìm nạpUser... mới.Tùy chọn khắc phục: (1) Tốt nhất: di chuyển hàm async bên trong useEffect và phụ thuộc vào [userId].(2) Phương án thay thế: bọc getUser bằng useCallback(() => { ... }, [userId]).(3) Hiện đại: sử dụng TanStack Query để xử lý hoàn toàn việc này.Đây là một trong những lỗi React phổ biến nhất trong các cơ sở mã thực.',
  },
  'ap-023': {
    question: 'Nhóm của bạn đang xây dựng một bảng điều khiển giao dịch tài chính phức tạp với các cập nhật dữ liệu theo thời gian thực (hơn 100 cập nhật/giây).Cập nhật trạng thái đang gây ra hiện tượng rớt khung hình.Bạn kiến ​​trúc lớp trạng thái như thế nào?',
    answer: '1',
    explanation: 'Thời gian thực với hơn 100 cập nhật/giây: React không thể kết xuất lại ở tần số này mà không làm rơi khung hình.Giải pháp: (1) Web Worker - nhận thông báo WebSocket, phân tích cú pháp, tổng hợp và đăng các bản cập nhật theo đợt lên luồng chính theo khoảng thời gian được kiểm soát.(2) Cửa hàng bên ngoài — Đăng ký của Zustand bằng bộ chọn hoặc cửa hàng tùy chỉnh với useSyncExternalStore.Cập nhật cửa hàng đồng bộ và nhanh chóng (không có chi phí giảm thiểu).(3) Phân nhóm RAF - tích lũy các bản cập nhật, áp dụng một lần cho mỗi khung hình hoạt hình.Các thành phần nhìn thấy tối đa 60 cập nhật/giây.(4) Đăng ký có chọn lọc — tiện ích giao dịch đăng ký ["AAPL", "price"], bỏ qua tất cả các cập nhật khác.Phản ứng chỉ hiển thị lại khi giá trị đăng ký thay đổi.(5) Canvas - Cập nhật biểu đồ dựa trên D3/Canvas hoàn toàn nằm ngoài sự đối chiếu của React.',
  },
  'ap-024': {
    question: 'Bạn cần chia sẻ trạng thái giỏ hàng giữa tiêu đề (biểu tượng giỏ hàng có số lượng) và trang giỏ hàng.Giỏ hàng có các hành động thêm, xóa và cập nhật số lượng.Cách tiếp cận có thể mở rộng đơn giản nhất là gì?',
    answer: '1',
    explanation: 'Zustand lý tưởng cho trạng thái giỏ hàng: (1) Bản soạn sẵn tối thiểu - tạo cửa hàng trong ~ 20 dòng với trạng thái và hành động đã nhập.(2) Không có nhà cung cấp nào - useCartStore() hoạt động ở mọi nơi, không cần bọc cây.(3) Phần mềm trung gian liên tục - giỏ hàng vẫn tồn tại khi làm mới trang thông qua localStorage mà không cần thêm mã.(4) Đăng ký có chọn lọc - tiêu đề sử dụng useCartStore(s => s.items.length) và chỉ hiển thị lại khi số lượng thay đổi.Trang giỏ hàng sử dụng useCartStore(s => s.items) để có danh sách đầy đủ.(5) DevTools - Zustand hoạt động với Redux DevTools để gỡ lỗi.(6) Redux vẫn ổn nhưng nặng hơn đối với một tên miền;Ngữ cảnh khiến tất cả người tiêu dùng hiển thị lại khi có bất kỳ thay đổi nào mà không cần thủ thuật ghi nhớ.',
  },
  'ap-025': {
    question: 'Ứng dụng của bạn có trình hướng dẫn gồm nhiều bước (5 bước) với các quy tắc xác thực phức tạp.Bước 3 phụ thuộc vào các lựa chọn ở Bước 1. Bạn quản lý trạng thái và điều hướng của trình hướng dẫn như thế nào?',
    answer: '1',
    explanation: 'Kiến trúc trình hướng dẫn: (1) Máy trạng thái - các trạng thái rõ ràng ngăn chặn các chuyển đổi không thể thực hiện được (không thể chuyển từ bước 1 sang bước 5 nếu không hoàn thành bước 2-4).Bảo vệ xác nhận trước khi chuyển đổi.Trình hiển thị XState giúp gỡ lỗi các luồng phức tạp.(2) Xác thực biểu mẫu - Lược đồ Zod trên mỗi bước.Lược đồ của bước 3 chỉ có thể tham chiếu dữ liệu của bước 1: z.object({ plan: z.literal("enterprise") }) nếu bước 1 chọn Enterprise.(3) Tính bền vững của dữ liệu - Zustand hoặc ngữ cảnh lưu trữ dữ liệu trình hướng dẫn tích lũy.Kiên trì với sessionStorage để quá trình làm mới không bị mất tiến trình.(4) Đồng bộ hóa URL - /wizard/step/3 cho phép điều hướng trình duyệt.(5) Luồng động — một số bước có điều kiện: nếu bước 1 = "kinh doanh", hiển thị bước 2b (thông tin thuế), nếu không thì bỏ qua.',
  },
  'ap-026': {
    question: 'Thời gian xây dựng là 15 phút cho quy trình CI/CD ứng dụng React của bạn.Làm thế nào để bạn tối ưu hóa nó?',
    answer: '1',
    explanation: 'Các lớp tối ưu hóa CI/CD: (1) Bundler - Rspack (tương thích Webpack dựa trên Rust) hoặc Vite (esbuild cho dev, Rollup cho prod) nhanh hơn đáng kể so với Webpack 4/5.(2) Bộ nhớ đệm từ xa - Các tạo phẩm xây dựng bộ nhớ đệm Turborepo/Nx bằng hàm băm nội dung.Nếu không có gì thay đổi, quá trình xây dựng sẽ diễn ra ngay lập tức (nhấn bộ đệm).(3) Tính song song - Người chạy CI có thể thực hiện đồng thời các bài kiểm tra lint + type-check + unit thay vì tuần tự.(4) Phát hiện bị ảnh hưởng - trong monorepos, chỉ xây dựng lại/kiểm tra các gói bị ảnh hưởng bởi những thay đổi của PR.(5) Docker - xây dựng nhiều giai đoạn với lớp node_modules được lưu trong bộ nhớ cache;chỉ cài đặt lại khi pack.json thay đổi.(6) Kết quả điển hình: 15 phút → 3-4 phút với những tối ưu hóa này, có thể dưới 1 phút với tốc độ truy cập bộ đệm tốt.',
  },
  'ap-027': {
    question: 'Monorepo với 20 gói có xung đột phụ thuộc - các gói khác nhau cần các phiên bản khác nhau của cùng một thư viện.Làm thế nào để bạn quản lý điều này?',
    answer: '1',
    explanation: 'Chiến lược phụ thuộc Monorepo: (1) pnpm - cấu trúc node_modules nghiêm ngặt ngăn các gói nhập các phần phụ thuộc không được khai báo (các phần phụ ảo).Mỗi gói chỉ nhìn thấy deps được khai báo của nó.(2) danh mục pnpm — xác định các phiên bản được chia sẻ trong pnpm-workspace.yaml: Reac: "catalog:" phân giải thành phiên bản được xác định một lần trong danh mục.(3) ngang hàng - thư viện khung chia sẻ (React, Vue) được khai báo là ngang hàng để người tiêu dùng kiểm soát phiên bản.(4) Bộ thay đổi - quản lý phiên bản trên các gói: khi gói A thay đổi, các phần phụ thuộc của A sẽ tự động nhận được bản vá.(5) Loại bỏ trùng lặp — kho lưu trữ có thể định địa chỉ nội dung của pnpm có nghĩa là các phiên bản giống hệt nhau sẽ chia sẻ dung lượng đĩa.(6) Chính sách phiên bản - "gói bên trong" (nội bộ) sử dụng không gian làm việc:* mới nhất."Gói bên ngoài" (đã xuất bản) sử dụng phạm vi ngữ nghĩa.',
  },
  'ap-028': {
    question: 'Triển khai không thành công trong quá trình sản xuất - người dùng thấy ứng dụng bị hỏng với màn hình trắng.Chiến lược phản ứng ngay lập tức và khôi phục của bạn là gì?',
    answer: '1',
    explanation: 'Ứng phó sự cố sản xuất: (1) NGAY LẬP TỨC — khôi phục trong vòng vài phút chứ không phải hàng giờ.Các nền tảng như Vercel có khả năng khôi phục ngay lập tức.Đối với cơ sở hạ tầng tùy chỉnh: trỏ CDN/bộ cân bằng tải vào nội dung của phiên bản trước.(2) Thanh lọc CDN - nội dung cũ được lưu trong bộ nhớ đệm (JS cũ tham chiếu các đoạn đã bị xóa) gây ra màn hình trắng.Xóa bộ đệm cạnh sau khi khôi phục.(3) Nguyên nhân cốt lõi - Sentry hiển thị lỗi.Nguyên nhân phổ biến: lỗi tải chunk (thiếu tệp phân tách mã), thay đổi hợp đồng API, cấu hình sai biến môi trường.(4) Phòng ngừa: canary triển khai định tuyến lưu lượng truy cập 5-10% sang phiên bản mới, theo dõi tỷ lệ lỗi, tự động quảng bá hoặc tự động khôi phục.Điểm cuối kiểm tra tình trạng đạt được sau khi triển khai.(5) Băm khối - sử dụng tên tệp băm nội dung để phiên bản cũ và mới cùng tồn tại trên CDN.',
  },
  'ap-029': {
    question: 'Triển khai triển khai không có thời gian ngừng hoạt động với các bản phát hành canary cho ứng dụng giao diện người dùng.Cơ sở hạ tầng hoạt động như thế nào?',
    answer: '1',
    explanation: 'Canary cho giao diện người dùng: (1) Lập phiên bản nội dung - gói JS/CSS của cả hai phiên bản cùng tồn tại trên CDN với tên tệp băm nội dung.Không có xung đột.(2) Định tuyến biên - Cloudflare Workers hoặc Vercel Edge Middleware kiểm tra yêu cầu, kiểm tra cookie canary hoặc áp dụng phân chia tỷ lệ phần trăm, viết lại HTML để tải điểm nhập canary hoặc ổn định.(3) Phiên cố định - khi người dùng được chỉ định canary, cookie sẽ giữ họ trên đó.Ngăn chặn trải nghiệm khó hiểu khi chuyển đổi giữa các phiên bản.(4) Giám sát - so sánh canary và ổn định: tỷ lệ lỗi JS, LCP, CLS, tỷ lệ chuyển đổi.Ý nghĩa thống kê cần thiết trước khi khuyến mãi.(5) Rollback — instant: cập nhật cấu hình Edge để định tuyến 0% tới canary.Các gói cũ vẫn còn trên CDN.(6) Cờ tính năng bổ sung cho canary - canary kiểm tra các thay đổi về cơ sở hạ tầng, cờ kiểm tra các thay đổi ở cấp độ tính năng.',
  },
  'ap-030': {
    question: 'Gói của bạn có 50 gói npm chưa sử dụng, làm tăng kích thước gói.Làm thế nào để bạn kiểm tra và làm sạch chúng?',
    answer: '1',
    explanation: 'Quy trình kiểm tra phụ thuộc: (1) depcheck — phân tích tĩnh của dữ liệu nhập so với pack.json.Bắt các gói được liệt kê nhưng không bao giờ được nhập.Kết quả dương tính giả: gói cấu hình (eslint-config-*), plugin babel, gói chỉ loại.(2) knip - toàn diện hơn: tìm các tệp không sử dụng, các bản xuất, các phần phụ thuộc và các phần phụ thuộc của nhà phát triển.(3) Trình phân tích gói - sơ đồ dạng cây trực quan hiển thị thành phần gói thực tế.Bạn có thể tìm thấy các tệp ngôn ngữ moment.js (500KB), lodash được nhập đầy đủ (70KB so với 5KB đối với lodash-es Cherry-pick).(4) Rung cây - đảm bảo nhập là ESM: import { debounce } từ "lodash-es" không nhập _ từ "lodash".sideEffects: false trong package.json cho phép rung cây.(5) Ngân sách CI - kích thước gói hoặc giới hạn kích thước trong CI không thành công PR nếu gói tăng vượt quá ngưỡng.',
  },
  'ap-031': {
    question: 'Nhóm của bạn đang tranh luận giữa Vite và Webpack về một dự án React mới vào năm 2025. Đâu là điểm khác biệt chính dẫn đến quyết định này?',
    answer: '1',
    explanation: 'Vite vs Webpack vào năm 2025: Máy chủ Vite dev - phục vụ các tệp nguồn dưới dạng mô-đun ES gốc, không cần gói trong dev.Cập nhật HMR trong <50 mili giây bất kể kích thước ứng dụng.Máy chủ phát triển Webpack gói mọi thứ, vì vậy khả năng khởi động và mở rộng quy mô HMR phù hợp với kích thước ứng dụng.Sản xuất Vite - sử dụng Rollup (sắp có Rolldown, Rollup dựa trên Rust) để tối ưu hóa các bản dựng sản xuất.Sản xuất webpack - trưởng thành nhưng chậm hơn.Rspack (Webpack dựa trên Rust) là một giải pháp thay thế giúp duy trì khả năng tương thích của plugin Webpack với tốc độ cải thiện gấp 5-10 lần.Liên kết mô-đun - Tính năng độc quyền của Webpack/Rspack dành cho giao diện người dùng vi mô.Vite có giải pháp cộng đồng nhưng kém trưởng thành hơn.Quyết định: Vite cho 90% dự án mới.Rspack nếu di chuyển từ Webpack.Webpack 5 chỉ khi tồn tại khoản đầu tư plugin sâu.',
  },
  'ap-032': {
    question: 'Ứng dụng của bạn hoạt động trong quá trình phát triển nhưng hiển thị một trang trắng trong quá trình sản xuất sau khi xây dựng.Nguyên nhân phổ biến nhất là gì?',
    answer: '1',
    explanation: 'Trang trắng trong danh sách kiểm tra gỡ lỗi sản xuất: (1) Mở Bảng điều khiển DevTools của trình duyệt - thường hiển thị lỗi (404 đối với nội dung, biến không xác định, lỗi định tuyến).(2) Đường cơ sở — vấn đề phổ biến nhất.Cơ sở của Vite: "/app/" hoặc trang chủ của CRA: "/app/" phải khớp với đường dẫn URL nơi ứng dụng được triển khai.(3) Biến môi trường — Vite yêu cầu tiền tố VITE_.CRA yêu cầu tiền tố REACT_APP_.Các biến không có tiền tố sẽ bị loại bỏ khỏi bản dựng máy khách.(4) Định tuyến SPA - máy chủ phải trả về index.html cho tất cả các tuyến.Nginx: try_files $uri /index.html.Vercel: viết lại trong vercel.json.(5) Xây dựng đầu ra - luôn kiểm tra các lỗi TypeScript, thiếu nội dung nhập hoặc rung cây để loại bỏ các tác dụng phụ cần thiết.',
  },
  'ap-033': {
    question: 'Bạn đang thiết lập một monorepo mới cho 5 ứng dụng giao diện người dùng và 10 gói dùng chung.Bạn chọn ngăn xếp công cụ nào và bạn cấu trúc nó như thế nào?',
    answer: '1',
    explanation: 'Công cụ Monorepo vào năm 2025: (1) pnpm — cách ly node_modules nghiêm ngặt sẽ ngăn chặn các lỗi ảo.không gian làm việc:* giao thức để liên kết gói cục bộ.Cửa hàng có thể định địa chỉ nội dung giúp tiết kiệm dung lượng ổ đĩa.(2) Turborepo - xác định các phần phụ thuộc của tác vụ (bản dựng phụ thuộc vào^bản dựng của các phần phụ thuộc), lưu trữ đầu ra, chạy song song.Chia sẻ bộ nhớ đệm từ xa xây dựng các tạo phẩm trên CI và nhà phát triển.(3) Cấu trúc: apps/web, apps/admin, apps/mobile-web, packages/ui, packages/utils, packages/tsconfig, packages/eslint-config.(4) Gói nội bộ - cấu hình được chia sẻ được sử dụng thông qua "mở rộng" hoặc nhập gói, không được xuất bản.(5) Bộ thay đổi - khi các gói/ui thay đổi, các ứng dụng sử dụng nó sẽ tự động biết để xây dựng lại.Phiên bản cho các gói được xuất bản.(6) CI — turbo run build --filter=...[origin/main] chỉ xây dựng những gì đã thay đổi kể từ main.',
  },
  'ap-034': {
    question: 'Trang sản phẩm được tạo tĩnh cần hiển thị nội dung được cá nhân hóa (sản phẩm được đề xuất, giá dành riêng cho người dùng).Bạn giải quyết vấn đề này như thế nào mà không bị mất quyền lợi SSG?',
    answer: '1',
    explanation: 'Cá nhân hóa với SSG: Thông tin chi tiết quan trọng là hầu hết trang đều giống nhau đối với tất cả mọi người.(1) Vỏ tĩnh - tiêu đề, mô tả, hình ảnh, đánh giá sản phẩm giống hệt nhau.Kết xuất trước bằng getStaticProps/generateStaticParams.Được phục vụ từ biên CDN — nhanh chóng.(2) Các vị trí được cá nhân hóa — "Được đề xuất cho bạn", định giá động, phía khách hàng được tải "Đã xem gần đây" sau khi hydrat hóa.Dự phòng bộ xương ngăn chặn sự thay đổi bố cục.(3) Bộ nhớ đệm dựa trên phân khúc — thay vì cá nhân hóa theo từng người dùng, hãy nhóm người dùng thành các phân khúc (mới/cũ, khu vực, cấp gói).Edge Middleware đặt tiêu đề phân đoạn.Bộ nhớ đệm các biến thể tĩnh cho mỗi phân đoạn: /product/abc?segment=enterprise.(4) Truyền phát SSR - Bộ định tuyến ứng dụng Next.js có thể truyền phát các ranh giới Hồi hộp được cá nhân hóa trong khi lớp vỏ tĩnh tải ngay lập tức.',
  },
  'ap-035': {
    question: 'Các tuyến API trong ứng dụng Next.js của bạn đang bị API thượng nguồn giới hạn tốc độ.Bạn triển khai bộ nhớ đệm ở biên như thế nào để giảm số lệnh gọi API?',
    answer: '1',
    explanation: 'Bộ nhớ đệm biên cho các tuyến API: (1) Bộ nhớ đệm HTTP — Kiểm soát bộ đệm: s-maxage=60, stale-while-revalidate=300 có nghĩa là CDN phân phối phản hồi được lưu trong bộ nhớ đệm trong 60 giây, sau đó phân phối cũ trong khi tìm nạp mới ở chế độ nền trong tối đa 300 giây.(2) Upstash Redis — Redis không có máy chủ ở rìa.Route Handler kiểm tra Redis trước: const cached = wait redis.get(key);nếu (được lưu trong bộ nhớ cache) trả về được lưu trong bộ nhớ cache.Nếu không thì tìm nạp ngược dòng, lưu trữ trong Redis bằng TTL.(3) Yêu cầu kết hợp - nếu 100 người dùng yêu cầu cùng một dữ liệu cùng một lúc thì chỉ có một cuộc gọi ngược dòng được thực hiện.Sử dụng tính năng chống trùng lặp kiểu swr.(4) Bộ đệm theo cấp độ - Bản đồ theo từng phiên bản (nhanh nhất, không được chia sẻ) → Redis (được chia sẻ giữa các phiên bản, ~ 1 mili giây) → API ngược dòng (chậm, giới hạn tốc độ).(5) Vô hiệu hóa bộ nhớ đệm — webhook từ trình kích hoạt ngược dòng Redis.del(key) hoặc revalidatePath/revalidateTag trong Next.js.',
  },
  'ap-036': {
    question: 'Nhóm SEO cho biết các trang được hiển thị động không được Google lập chỉ mục.Chẩn đoán và khắc phục sự cố.',
    answer: '1',
    explanation: 'SEO cho SPA/trang động: (1) Nguyên nhân cốt lõi - CSR thuần túy (hiển thị phía máy khách) có nghĩa là HTML ban đầu trống.Googlebot thực thi JS nhưng có độ trễ và hạn chế.Nội dung quan trọng phải ở dạng HTML ban đầu thông qua SSR/SSG.(2) Ưu điểm của Next.js - các trang được hiển thị trên máy chủ theo mặc định.Nhưng nếu bạn tìm nạp dữ liệu trong useEffect (phía máy khách) thì nội dung đó không có trong HTML ban đầu.Sử dụng getServerSideProps, getStaticProps hoặc Thành phần máy chủ bộ định tuyến ứng dụng.(3) Thẻ meta - phải nằm trong phần đầu HTML do máy chủ hiển thị.next/head hoặc generateMetadata trong Bộ định tuyến ứng dụng.(4) Dữ liệu có cấu trúc — lược đồ JSON-LD trong <script type="application/ld+json"> cho các sản phẩm, bài viết, Câu hỏi thường gặp.(5) Sơ đồ trang web - gói sơ đồ trang web tiếp theo tự động tạo từ các trang.(6) URL Canonical - ngăn chặn các vấn đề trùng lặp nội dung từ các tham số URL.',
  },
  'ap-037': {
    question: 'Triển khai ISR ​​(Tái tạo tĩnh tăng dần) để xác thực lại trang bài đăng blog khi nội dung CMS thay đổi thông qua webhook.Viết trang và trình xử lý webhook.',
    answer: '// app/blog/[slug]/page.tsx\nnhập { notFound } từ \'next/navigation\'\n\ngiao diện BlogPost {\nsên: chuỗi\ntiêu đề: chuỗi\nnội dung: chuỗi\n}\n\nhàm không đồng bộ getPost(slug: string): Promise<BlogPost |vô giá trị> {\nconst res = đang chờ tìm nạp(`https://cms.example.com/api/posts/${slug}`, {\ntiếp theo: { xác nhận lại: 3600, tags: [`post-${slug}`] },\n})\nnếu (!res.ok) trả về null\ntrả về res.json()\n}\n\nxuất hàm không đồng bộ generateStaticParams() {\nconst res = đang chờ tìm nạp(\'https://cms.example.com/api/posts\')\nconst bài viết: BlogPost[] = đang chờ res.json()\nreturn post.map((post) => ({ slug: post.slug }))\n}\n\nxuất hàm không đồng bộ mặc định BlogPostPage({\nthông số,\n}: {\nthông số: Promise<{ slug: string }>\n}) {\nconst {slug } = đang chờ thông số\nconst post = đang chờ getPost(sên)\nif (!post) notFound()\n\ntrở lại (\n<bài viết>\n<h1>{post.title</h1>\n<div nguy hiểmSetInnerHTML={{ __html: post.content }} />\n</bài viết>\n)\n}\n\n// app/api/revalidate/route.ts\nnhập {revalidateTag } từ \'next/cache\'\nnhập { NextRequest, NextResponse } từ \'next/server\'\n\nxuất hàm không đồng bộ POST(request: NextRequest) {\nconst secret = request.headers.get(\'x-revalidation-secret\')\nif (bí mật !== process.env.REVALIDATION_SECRET) {\nreturn NextResponse.json({ message: \'Invalid secret\' }, { status: 401 })\n}\n\nconst body = đang chờ request.json()\nconst slug = body.slug dưới dạng chuỗi\n\nxác nhận lạiTag(`post-${slug}`)\n\nreturn NextResponse.json({revalidated: true, slug })\n}',
    explanation: 'ISR với xác thực lại theo yêu cầu: (1) Trang — sử dụng tìm nạp với next: { xác thực lại: 3600, tags: ["post-slug"] }.Trang được tạo tĩnh tại thời điểm xây dựng và được xác nhận lại mỗi giờ dưới dạng dự phòng.(2) Thẻ - tìm nạp bộ đệm được gắn thẻ với mã định danh theo bài đăng cụ thể.(3) Trình xử lý Webhook — CMS gọi /api/revalidate khi nội dung cập nhật.Trình xử lý xác thực bí mật (ngăn chặn việc xác thực lại trái phép), sau đó gọi revalidateTag("post-slug") để làm mất hiệu lực trang được lưu trong bộ nhớ đệm.(4) Yêu cầu tiếp theo tới trang đó sẽ kích hoạt quá trình tái tạo bằng dữ liệu CMS mới.(5) generateStaticParams hiển thị trước các bài đăng đã biết tại thời điểm xây dựng.Bài đăng mới được tạo theo yêu cầu đầu tiên (thông số động).(6) Bảo mật - luôn xác thực webhooks bằng bí mật chung.',
  },
  'ap-038': {
    question: 'Bạn đang xây dựng một trang trong Bộ định tuyến ứng dụng Next.js.Khi nào bạn nên sử dụng Thành phần máy chủ so với Thành phần máy khách?',
    answer: '1',
    explanation: 'Thành phần máy chủ và máy khách trong Bộ định tuyến ứng dụng Next.js: Thành phần máy chủ (mặc định): (1) Chỉ chạy trên máy chủ, không bao giờ được chuyển đến gói máy khách.(2) Có thể truy cập trực tiếp vào cơ sở dữ liệu, hệ thống tập tin, biến môi trường.(3) không đồng bộ/chờ ở cấp thành phần để tìm nạp dữ liệu.(4) Không có JavaScript phía máy khách cho nội dung tĩnh.Thành phần máy khách ("sử dụng máy khách"): (1) Bắt buộc đối với useState, useEffect, bất kỳ hook React nào.(2) Bắt buộc đối với trình xử lý sự kiện (onClick, onSubmit).(3) Bắt buộc đối với API trình duyệt.(4) Bắt buộc đối với nhà cung cấp ngữ cảnh.Mẫu: Thành phần máy chủ tìm nạp dữ liệu, chuyển nó dưới dạng đạo cụ cho Thành phần máy khách nhỏ xử lý tính tương tác.Điều này giảm thiểu gói khách hàng đồng thời cho phép tương tác phong phú.',
  },
  'ap-039': {
    question: 'Trang Bộ định tuyến ứng dụng Next.js này tìm nạp dữ liệu nhưng luôn hiển thị nội dung cũ ngay cả sau khi cơ sở dữ liệu được cập nhật.Tìm lỗi.',
    answer: 'Trong Bộ định tuyến ứng dụng Next.js, các yêu cầu tìm nạp được lưu vào bộ đệm theo mặc định (tương đương với bộ đệm bắt buộc).Lệnh gọi tìm nạp cần có { cache: "no-store" } cho dữ liệu luôn mới hoặc { next: { revalidate: 60 } } để xác thực lại dựa trên thời gian hoặc xác thực lại dựa trên thẻ với revalidateTag().',
    explanation: 'Vấn đề đáng chú ý về bộ nhớ đệm của Bộ định tuyến ứng dụng Next.js: Theo mặc định, tìm nạp() trong Thành phần máy chủ được lưu vào bộ nhớ đệm vô thời hạn (kết xuất tĩnh).Đây là sự nhầm lẫn số 1 trong Bộ định tuyến ứng dụng.Tùy chọn khắc phục: (1) Dữ liệu động — tìm nạp(url, { cache: "no-store" }) tìm nạp mới theo mọi yêu cầu.(2) ISR dựa trên thời gian - tìm nạp(url, { next: { xác nhận lại: 60 } }) lưu trữ trong 60 giây.(3) Theo yêu cầu — tìm nạp(url, { next: { tags: ["products"] } }) + revalidateTag("products") trong hành động webhook/máy chủ.(4) Cấp độ trang - xuất const động = "force-dynamic" làm cho toàn bộ trang trở nên động.(5) Lựa chọn đúng tùy thuộc vào yêu cầu về độ mới của dữ liệu: danh mục sản phẩm (xác nhận lại: 300), tồn kho/giá (không lưu trữ hoặc xác thực lại: 10), nội dung tĩnh (bộ nhớ đệm mặc định).',
  },
  'ap-040': {
    question: 'Bạn đang di chuyển một Ứng dụng Tạo React (CRA) lớn sang Bộ định tuyến ứng dụng Next.js.Ứng dụng này có hơn 200 tuyến đường, cửa hàng Redux và cấu hình Webpack tùy chỉnh.Chiến lược di chuyển của bạn là gì?',
    answer: '1',
    explanation: 'CRA → Chiến lược di chuyển Next.js: (1) Lộ trình tổng hợp - app/[[...slug]]/page.tsx hiển thị ứng dụng CRA hiện có dưới dạng Thành phần ứng dụng khách.Toàn bộ ứng dụng cũ hoạt động ngay lập tức trong Next.js.(2) Tuyến theo tuyến - trích xuất từng tuyến một vào các trang Next.js thích hợp.Bắt đầu với các trang có lưu lượng truy cập cao để có tác động tối đa.(3) Trạng thái - Nhà cung cấp Redux là Thành phần khách hàng bao bọc các phần tử con.Hoạt động tốt.Dần dần di chuyển dữ liệu do máy chủ tìm nạp ra khỏi Redux vào Thành phần máy chủ.(4) Webpack - hầu hết các cấu hình webpack tùy chỉnh đều có tương đương next.config.js hoặc hỗ trợ Turbopack.(5) Tìm nạp dữ liệu - tìm nạp dựa trên useEffect trong các trang cũ vẫn hoạt động trong Thành phần Máy khách.Các trang mới sử dụng Thành phần máy chủ có quyền truy cập dữ liệu trực tiếp.(6) Dòng thời gian - thường là 3-6 tháng cho hơn 200 tuyến đường với đội ngũ tận tâm.Vận chuyển tăng dần, không bao giờ xảy ra sự cố lớn.',
  },
}
