import type { QuestionTranslationMap } from '../types'

export const frontendPracticalVi: QuestionTranslationMap = {

  'fp-001': {
    question: 'Designer cung cấp cho bạn bố cục cần hoạt động trên màn hình 320px đến 4K.Đi qua chiến lược đáp ứng của bạn.',
    answer: 'Sử dụng kiểu chữ linh hoạt (clamp()), truy vấn vùng chứa, Lưới CSS với tính năng tự động điều chỉnh/tối thiểu, thuộc tính logic và điểm dừng đầu tiên trên thiết bị di động.',
    explanation: 'Bắt đầu ưu tiên thiết bị di động với các điểm dừng có chiều rộng tối thiểu.Sử dụng kẹp() cho các kích thước phông chữ linh hoạt (ví dụ: kẹp(1rem, 2.5vw, 2rem)) để văn bản chia tỷ lệ mượt mà mà không có điểm ngắt.Sử dụng CSS Grid với tính năng tự động điều chỉnh/tối thiểu để có bố cục giống như thẻ, điều chỉnh lại một cách tự nhiên.Thêm truy vấn vùng chứa (@container) để có khả năng phản hồi ở cấp thành phần độc lập với chế độ xem.Sử dụng các thuộc tính logic (kích thước nội tuyến so với chiều rộng) để quốc tế hóa.Đối với 4K, hãy giới hạn chiều rộng tối đa trên vùng chứa chính (ví dụ: 1440px) và căn giữa nó - không thể đọc được chiều rộng đầy đủ ở chế độ siêu rộng.Thử nghiệm với Chrome DeviceMode ở 320px, 768px, 1024px, 1440px, 2560px.Sử dụng đơn vị rem/em xuyên suốt;tránh px cho kích thước phông chữ.',
  },
  'fp-002': {
    question: 'Tiêu đề cố định chồng chéo nội dung khi người dùng nhấp vào liên kết neo.Tiêu đề cuộn phía sau tiêu đề cố định.Làm thế nào để bạn khắc phục điều này?',
    answer: '/* Khắc phục: thêm cuộn-padding-top vào tài khoản cho tiêu đề cố định */\nhtml {\ncuộn-đệm-top: 80px;/* chiều cao tiêu đề + khoảng trống */\n}\n\n/* Cách tiếp cận từng phần tử thay thế bằng cách sử dụng lề cuộn */\nphần[id] {\ncuộn-lề-trên cùng: 80px;\n}',
    explanation: 'Scroll-padding-top trên phần tử html/body yêu cầu trình duyệt bù vị trí bắt cuộn cuộn khi điều hướng đến các điểm neo (thông qua href="#section" hoặc ScrollIntoView).Đặt nó lớn hơn một chút so với chiều cao tiêu đề để tạo không gian dễ chịu cho thị giác.Scroll-margin-top trên các phần tử đích đạt được cùng một phần tử.Cách hack cũ là thêm một phần tử giả vô hình có lề âm, nhưng cuộn-padding-top là giải pháp hiện đại, rõ ràng.Hoạt động với cả nhấp chuột liên kết và điều hướng tiến/lùi của trình duyệt tới các liên kết cố định.',
  },
  'fp-003': {
    question: 'Gói CSS của bạn là 500KB.Làm thế nào để bạn kiểm tra và giảm thiểu nó?',
    answer: 'Kiểm tra bằng các công cụ PurgeCSS/bảo hiểm, áp dụng Mô-đun CSS hoặc phương pháp tiếp cận tiện ích đầu tiên, loại bỏ CSS khung không được sử dụng và triển khai trích xuất CSS quan trọng.',
    explanation: '1) Kiểm tra: Sử dụng tab Phạm vi phủ sóng DevTools của Chrome để tìm CSS không được sử dụng (thường là 60-80% CSS khung).Chạy PurgeCSS hoặc UnCSS dựa trên HTML/JSX của bạn để xác định các quy tắc chết.2) Thắng nhanh: Loại bỏ các lớp Bootstrap/Tailwind không sử dụng thông qua rung cây (Tailwind JIT tự động thực hiện việc này).Loại bỏ các quy tắc trùng lặp bằng cssnano.3) Kiến trúc: Chuyển sang Mô-đun CSS hoặc CSS-in-JS để tự động xác định phạm vi và loại bỏ mã chết.Nếu sử dụng Tailwind, hãy đảm bảo chế độ JIT được bật.4) Tách: Trích xuất nội tuyến CSS quan trọng trong màn hình đầu tiên trong <head>, tải phần còn lại không đồng bộ thông qua thủ thuật onload media="print" hoặc rel="preload".5) Giảm các cuộc chiến về tính đặc hiệu - bộ chọn phẳng hơn nén tốt hơn với gzip.6) Thay thế thiết lập lại tùy chỉnh CSS bằng thiết lập lại tối thiểu hiện đại (ít quy tắc hơn).Mục tiêu: nén dưới 50KB cho hầu hết các trang web.',
  },
  'fp-004': {
    question: 'Cuộc chiến chỉ số Z - nhiều nhà phát triển đã thêm các giá trị chỉ mục z như 9999, 99999 trên cơ sở mã.Các phương thức chồng chéo, menu thả xuống và chú giải công cụ đấu tranh để sắp xếp thứ tự.Bạn tổ chức các bối cảnh xếp chồng như thế nào?',
    answer: 'Tạo thang đo mã thông báo chỉ mục z, tận dụng cách ly bối cảnh xếp chồng và sử dụng các thuộc tính tùy chỉnh CSS cho hệ thống phân lớp được quản lý.',
    explanation: 'Bước 1: Xác định thang đo chỉ mục z bằng các thuộc tính tùy chỉnh CSS: --z-dropdown: 100, --z-sticky: 200, --z-overlay: 300, --z-modal: 400, --z-toast: 500, --z-tooltip: 600. Bước 2: Tạo bối cảnh xếp chồng mới có chủ ý bằng cách sử dụng cách ly: cách ly trên các vùng chứa thành phần — phạm vi này chỉ mục z để các phần tử con không thể thoát khỏi lớp cha của chúng.Bước 3: Thay thế tất cả các số chỉ số z ma thuật bằng mã thông báo.Bước 4: Ghi lại tỷ lệ trong hệ thống thiết kế của bạn.Bước 5: Thêm quy tắc stylelint (khai báo-thuộc tính-giá trị-không được phép-danh sách) để cấm các số chỉ mục z thô và thực thi bằng cách sử dụng mã thông báo.Thông tin chuyên sâu chính: hiểu rằng bối cảnh xếp chồng mới được tạo bởi vị trí + chỉ mục z, độ mờ < 1, biến đổi, bộ lọc, v.v. Sử dụng cách ly: cách ly rõ ràng để kiểm soát điều này.',
  },
  'fp-005': {
    question: 'Khách hàng muốn có một thanh bên cố định có thể cuộn theo trang nhưng dừng lại khi đến chân trang.Triển khai nó bằng CSS thuần túy.',
    answer: '/* Thanh bên cố định cho đến khi chạm vào ranh giới chân trang */\n.bố cục {\nhiển thị: lưới;\nlưới-mẫu-cột: 1fr 300px;\ncăn chỉnh các mục: bắt đầu;/* quan trọng - ngăn chặn việc kéo dài thanh bên */\n}\n\n.nội dung chính {\nchiều cao tối thiểu: 200vh;/* ví dụ về nội dung dài */\n}\n\n.sidebar {\nvị trí: dính;\ntrên cùng: 80px;/* offset cho tiêu đề */\nchiều cao tối đa: calc(100vh - 100px);\ntràn-y: tự động;\n}\n\n/* Footer nằm ngoài lưới nên sidebar tự nhiên dừng */\n.chân trang {\ncột lưới: 1/-1;\n}',
    explanation: 'vị trí: dính hoạt động trong tổ tiên cuộn gần nhất và khối chứa nó.Thanh bên nằm ở trên cùng: 80px và giữ nguyên ở đó khi người dùng cuộn.Nó tự nhiên ngừng dính khi hàng lưới gốc của nó kết thúc (nơi chân trang bắt đầu).Yêu cầu chính: 1) Cha mẹ KHÔNG được có tràn: ẩn/tự động (ngắt dính).2) căn chỉnh các mục: bắt đầu trên lưới ngăn thanh bên kéo dài để phù hợp với chiều cao nội dung chính - nếu không có điều này, sẽ không có chỗ để dính.3) Thêm chiều cao tối đa + tràn-y: tự động để thanh bên tự cuộn nếu nội dung của nó cao hơn khung nhìn.Không cần JavaScript.',
  },
  'fp-006': {
    question: 'Nhà phát triển báo cáo rằng vị trí: dính không hoạt động trên tiêu đề bảng.Thead vẫn giữ nguyên vị trí trên các trang khác nhưng không có trong bố cục này.Điều gì có thể sai?',
    answer: '1',
    explanation: 'vị trí: dính chỉ hoạt động tương ứng với tổ tiên gần nhất bằng cơ chế cuộn.Khi .table-wrapper có tràn-x: auto, nó sẽ tạo một vùng chứa cuộn mới.Phần dính cố gắng dính vào vùng chứa đó chứ không phải trang.Nếu bản thân trình bao bọc không cuộn theo chiều dọc (chỉ cuộn theo chiều ngang), thì tính dính sẽ không có tác dụng trên trục tung.Tùy chọn khắc phục: 1) Xóa tràn-x khỏi trình bao bọc và xử lý cuộn ngang theo cách khác.2) Đặt chiều cao cố định trên .table-wrapper với Overflow-y: auto để tiêu đề cố định hoạt động trong vùng có thể cuộn đó.3) Sử dụng bảng ảo hóa có hàng tiêu đề cố định tách biệt với phần thân có thể cuộn.',
  },
  'fp-007': {
    question: 'Bạn có một điều hướng ngang tràn trên thiết bị di động.Các mục được gói thành dòng thứ hai và trông có vẻ bị hỏng.Cách khắc phục nhanh nhất chỉ dành cho CSS để làm cho nó có thể cuộn theo chiều ngang là gì?',
    answer: '1',
    explanation: 'Flexbox với tràn-x: auto và flex-wrap: nowrap tạo ra một vùng chứa có thể cuộn theo chiều ngang.Các mục nằm trên một hàng duy nhất và người dùng có thể vuốt theo chiều ngang trên thiết bị di động.Thêm -webkit-overflow-scrolling: chạm để cuộn theo đà mượt mà trên iOS cũ hơn.Sử dụng khoảng cách thay vì lề để có khoảng cách nhất quán.Để ẩn thanh cuộn một cách trực quan trong khi vẫn giữ chức năng, hãy sử dụng chiều rộng thanh cuộn: none (Firefox) và ::-webkit-scrollbar { display: none } (Chromium/Safari).Tùy chọn D (khoảng trắng: nowrap) chỉ hoạt động đối với các phần tử khối nội tuyến/khối nội tuyến, không hoạt động đối với các mục linh hoạt.',
  },
  'fp-008': {
    question: 'Nhóm của bạn đang di chuyển từ cơ sở mã CSS BEM cũ sang hệ thống dựa trên mã thông báo thiết kế.Trang web có hơn 200 thành phần.Bạn lập kế hoạch di chuyển này như thế nào mà không làm gián đoạn hoạt động sản xuất?',
    answer: 'Áp dụng chiến lược gia tăng: xác định mã thông báo trước, tạo lớp tương thích ánh xạ các biến cũ, di chuyển từng thành phần bằng thử nghiệm hồi quy trực quan và chạy song song cả hai hệ thống.',
    explanation: '1) Xác định mã thông báo thiết kế dưới dạng thuộc tính tùy chỉnh CSS (--color-primary, --space-md, v.v.) trong tệp token.css chung.2) Tạo một lớp cầu nối/tương thích để ánh xạ các biến BEM cũ sang các mã thông báo mới để cả hai hệ thống cùng tồn tại.3) Thiết lập kiểm tra hồi quy trực quan (ảnh chụp màn hình Chromatic, Percy hoặc Playwright) để nắm bắt những thay đổi ngoài ý muốn - điều này rất quan trọng với hơn 200 thành phần.4) Ưu tiên thứ tự di chuyển: các thành phần dùng chung/cơ sở trước (nút, đầu vào, kiểu chữ), sau đó là các thành phần tổng hợp.5) Sử dụng tập lệnh mã hóa hoặc tìm-thay thế cho các thay đổi cơ học (ví dụ: thay thế các màu được mã hóa cứng bằng tham chiếu mã thông báo).6) Mỗi ​​thành phần được di chuyển sẽ nhận được PR kèm theo ảnh chụp màn hình trước/sau.7) Gắn cờ tính năng cho các mã thông báo mới để bạn có thể quay lại.8) Sau khi tất cả các thành phần được di chuyển, hãy xóa lớp tương thích và các biến kế thừa.Ngân sách: 2-3 lần chạy nước rút cho cơ sở hạ tầng/mã thông báo, sau đó 1-2 thành phần cho mỗi nhà phát triển cho mỗi lần chạy nước rút.',
  },
  'fp-009': {
    question: 'Triển khai chuyển đổi chủ đề tối/sáng tôn trọng tùy chọn hệ thống và duy trì lựa chọn thủ công của người dùng trong localStorage.',
    answer: '/* CSS: sử dụng các thuộc tính tùy chỉnh cho chủ đề */\n:gốc {\n--bg: #ffffff;\n--văn bản: #1a1a1a;\n--bề mặt: #f5f5f5;\n}\n\n[data-theme="dark"] {\n--bg: #121212;\n--text: #e0e0e0;\n--bề mặt: #1e1e1e;\n}\n\n/* Tôn trọng tùy chọn hệ thống khi không có lựa chọn thủ công */\n@media (thích-lược đồ màu: tối) {\n:root:not([data-theme="light"]) {\n--bg: #121212;\n--text: #e0e0e0;\n--bề mặt: #1e1e1e;\n}\n}\n\n/*Javascript */\n// Khi tải trang - chạy cái này trong <head> để tránh flash\nconst được lưu trữ = localStorage.getItem(\'theme\');\nnếu (được lưu trữ) {\ndocument.documentElement.setAttribution (\'chủ đề dữ liệu\', được lưu trữ);\n}\n\n// Chuyển đổi chức năng\nhàm chuyển đổiTheme() {\nconst current = document.documentElement.getAttribution(\'data-theme\');\nconst systemDark = window.matchMedia(\'(prefers-color-scheme: dark)\').matches;\nconst isDark = hiện tại === \'tối\' ||(!current && systemDark);\nconst tiếp theo = isDark?\'sáng\' : \'tối\';\ndocument.documentElement.setAttribution(\'data-theme\', next);\nlocalStorage.setItem(\'theme\', next);\n}\n\n// Lắng nghe các thay đổi tùy chọn hệ thống\nwindow.matchMedia(\'(thích-lược đồ màu: tối)\')\n.addEventListener(\'change\', (e) => {\nif (!localStorage.getItem(\'theme\')) {\n// Chỉ tự động chuyển đổi nếu người dùng chưa chọn thủ công\ndocument.documentElement.setAttribution(\n\'chủ đề dữ liệu\', e.matches ?\'tối\' : \'sáng\'\n);\n}\n});',
    explanation: 'Chiến lược sử dụng ba lớp: 1) Thuộc tính tùy chỉnh CSS cho các giá trị chủ đề — tất cả các thành phần đều tham chiếu các biến này.2) thuộc tính chủ đề dữ liệu trên <html> để ghi đè rõ ràng.3) ưu tiên truy vấn phương tiện lược đồ màu làm mặc định khi không có lựa chọn thủ công nào tồn tại.Bộ chọn :root:not([data-theme="light"]) đảm bảo tùy chọn tối của hệ thống chỉ áp dụng khi người dùng chưa chọn ánh sáng một cách rõ ràng.JS trong <head> chạy đồng bộ trước khi vẽ để ngăn flash sai chủ đề (FOWT).localStorage vẫn tồn tại qua các phiên.Trình nghe matchMedia xử lý các thay đổi chủ đề cấp hệ điều hành trong thời gian thực.',
  },
  'fp-010': {
    question: 'Thành phần thẻ có văn bản tràn vùng chứa trên thiết bị di động khi tiêu đề quá dài.Triển khai giải pháp chỉ dành cho CSS cắt ngắn bằng dấu chấm lửng cho phiên bản kẹp một dòng và cả phiên bản kẹp nhiều dòng.',
    answer: '/* Cắt ngắn một dòng */\n.card-title--single {\nkhoảng trắng: nowrap;\ntràn: ẩn;\ntràn văn bản: dấu chấm lửng;\n}\n\n/* Kẹp nhiều dòng (hiển thị tối đa 3 dòng) */\n.card-title--multi {\nhiển thị: -webkit-box;\n-webkit-line-kẹp: 3;\n-webkit-box-orient: dọc;\ntràn: ẩn;\n}',
    explanation: 'Dấu ba chấm một dòng yêu cầu cả ba thuộc tính: khoảng trắng: nowrap ngăn chặn việc gói, tràn: ẩn các clip nội dung, tràn văn bản: dấu chấm lửng thêm "..." tại điểm cắt.Phần tử phải có chiều rộng bị ràng buộc (cấp khối hoặc chiều rộng rõ ràng).Kẹp nhiều dòng sử dụng thuộc tính -webkit-line-clamp, mặc dù có tiền tố của nhà cung cấp, nhưng vẫn được hỗ trợ trong tất cả các trình duyệt hiện đại (Chrome, Firefox 68+, Safari, Edge).Phần tử phải sử dụng hiển thị -webkit-box.Để có khả năng truy cập, toàn bộ văn bản vẫn phải có sẵn (ví dụ: thông qua thuộc tính tiêu đề hoặc nhấp chuột có thể mở rộng) vì trình đọc màn hình có thể đọc phiên bản bị cắt bớt.',
  },
  'fp-011': {
    question: 'Một nhà phát triển đang sử dụng chuyển đổi CSS nhưng hoạt ảnh từ display: none đến display: block không hoạt động.Phần tử chỉ xuất hiện ngay lập tức.Điều gì đang xảy ra và bạn khắc phục nó như thế nào?',
    answer: '1',
    explanation: 'Thuộc tính hiển thị không thể hoạt hình được — việc thay đổi từ không thành khối là một chuyển đổi nhị phân không có giá trị trung gian, do đó các chuyển tiếp không có gì để nội suy.Cách khắc phục cổ điển: giữ phần tử trong DOM và tạo độ mờ động (0 đến 1) + khả năng hiển thị (ẩn thành hiển thị).khả năng hiển thị: ẩn sẽ xóa nó khỏi cây khả năng truy cập và các sự kiện nhấp chuột trong khi vẫn cho phép chuyển đổi.Bản sửa lỗi hiện đại (2024+): sử dụng kiểu @starting để xác định hoạt ảnh mục nhập cho các thành phần chuyển từ hiển thị: không có.Ngoài ra hành vi chuyển tiếp: allow-discrete cho phép hiển thị tham gia vào quá trình chuyển đổi.Ví dụ: @starting-style { .modal { opacity: 0;} } kết hợp với .modal { transition: độ mờ 0,3s, hiển thị 0,3s cho phép rời rạc;}.',
  },
  'fp-012': {
    question: 'Xây dựng bố cục lưới kiểu khối xây đáp ứng chỉ bằng CSS hiện đại (không có JavaScript).Nó sẽ xử lý các thẻ có chiều cao thay đổi và chỉnh lại dòng dựa trên không gian có sẵn.',
    answer: '/* CSS Masonry hiện đại với lưới CSS */\n/* Tùy chọn 1: cột (được hỗ trợ rộng rãi) */\n.cột xây {\ncột: 3 280px;/* 3 cột, mỗi cột tối thiểu 280px */\nkhoảng cách cột: 1rem;\n}\n\n.masonry-cột .card {\nbreak-inside: tránh;\nlề dưới: 1rem;\n}\n\n/* Tùy chọn 2: Lưới CSS (thông số kỹ thuật mới nổi, cờ Firefox) */\n.masonry-lưới {\nhiển thị: lưới;\nlưới-mẫu-cột: lặp lại (tự động điền, minmax (280px, 1fr));\nlưới-mẫu-hàng: khối xây;/*thông số tương lai */\nkhoảng cách: 1rem;\n}\n\n/* Tùy chọn 3: Xấp xỉ Flexbox với tỷ lệ khung hình cố định */\n.masonry-flex {\nhiển thị: linh hoạt;\nflex-wrap: bọc;\nkhoảng cách: 1rem;\n}\n\n.masonry-flex .card {\nlinh hoạt: 1 1 280px;\n}',
    explanation: 'Ba cách tiếp cận vào năm 2025: 1) Cột CSS là đáng tin cậy nhất — nó lấp đầy các cột từ trên xuống dưới rồi chuyển sang cột tiếp theo.break-inside: tránh ngăn thẻ chia thành các cột.Nhược điểm: các mục được sắp xếp theo chiều dọc chứ không phải theo chiều ngang (cột 1 điền trước).2) CSS Grid nề (grid-template-rows: Masonry) là giải pháp lý tưởng nhưng vẫn chưa được đánh giá cao trong hầu hết các trình duyệt - chỉ Firefox Nightly hỗ trợ nó.3) Flexbox tạo bố cục dạng lưới nhưng các mục có chiều cao bằng nhau trên mỗi hàng trừ khi bạn sử dụng tỷ lệ khung hình cụ thể.Đối với hoạt động sản xuất ngày nay, hãy sử dụng phương pháp tiếp cận cột cho khối xây thực sự hoặc thư viện JS nhẹ (Masonry.js, ~4KB) nếu thứ tự đọc theo chiều ngang quan trọng.',
  },
  'fp-013': {
    question: 'Bạn cần căn giữa một phương thức theo chiều dọc và chiều ngang trong khung nhìn.Nó phải ở giữa bất kể chiều cao nội dung.Cách tiếp cận nào là mạnh mẽ nhất?',
    answer: '1',
    explanation: 'Tùy chọn B sử dụng inset: 0 (viết tắt cho trên/phải/dưới/trái: 0) với display: lưới và place-items: center là mạnh mẽ nhất.Nó hoạt động bất kể kích thước nội dung phương thức, không yêu cầu biết kích thước và căn giữa cả hai trục.Lớp phủ phông nền lấp đầy khung nhìn.Tùy chọn A yêu cầu kích thước được mã hóa cứng (lề âm).Một giải pháp thay thế gần gũi là vị trí: cố định;trên cùng: 50%;trái: 50%;Transform: Translate(-50%, -50%) cũng hoạt động mà không cần biết kích thước.Thậm chí còn tốt hơn trong CSS hiện đại: sử dụng phần tử <dialog> với hành vi ::backdrop và căn giữa được tích hợp sẵn.',
  },
  'fp-014': {
    question: 'Nhóm của bạn sử dụng CSS Tailwind nhưng các nhà thiết kế phàn nàn rằng trang web trông "chung chung".Làm cách nào để bạn tạo một bản sắc hình ảnh đặc biệt trong khi vẫn giữ CSS ưu tiên tiện ích?',
    answer: 'Tùy chỉnh rộng rãi cấu hình chủ đề Tailwind, tạo mã thông báo thiết kế cấp thành phần, xây dựng một tập hợp nhỏ các tiện ích tùy chỉnh và sử dụng @apply một cách tiết kiệm cho các mẫu thành phần phức tạp.',
    explanation: 'Vấn đề "Tailwind chung" xuất phát từ việc sử dụng các giá trị mặc định.Khắc phục: 1) Tùy chỉnh đầy đủ tailwind.config.js — ghi đè các màu mặc định (không chỉ mở rộng), tỷ lệ kiểu chữ, tỷ lệ khoảng cách, giá trị bán kính đường viền và bóng để phù hợp với thương hiệu.2) Xác định lớp mã thông báo thiết kế: tạo các bí danh ngữ nghĩa như color.primary, color.surface thay vì sử dụng các giá trị bảng màu thô trong các thành phần.3) Tạo các tiện ích tùy chỉnh thông qua API plugin cho các mẫu dành riêng cho thương hiệu (ví dụ: độ dốc được gắn thương hiệu, cách xử lý văn bản cụ thể).4) Xây dựng thư viện thành phần nhỏ (nút, thẻ, v.v.) bằng cách sử dụng @apply để gói gọn các mẫu thương hiệu — các nhà phát triển soạn những thư viện này thay vì các tiện ích thô cho các thành phần chính.5) Thêm phông chữ tùy chỉnh, hình động và tương tác vi mô thông qua CSS.6) Chỉ sử dụng Tailwind để bố trí/khoảng cách;các thành phần thương hiệu quan trọng có được các lớp CSS chuyên dụng.Mục tiêu: 80% tiện ích Tailwind cho bố cục, 20% CSS tùy chỉnh cho tính cách thương hiệu.',
  },
  'fp-015': {
    question: 'Người dùng báo cáo rằng các đường nét tiêu điểm biến mất trên trang web của bạn, gây ảnh hưởng đến việc điều hướng bằng bàn phím.Nhà phát triển trước đó đã thêm `*:focus { phác thảo: none;}`.Sửa lỗi này để người dùng bàn phím nhìn thấy chỉ báo tiêu điểm nhưng người dùng chuột thì không.',
    answer: '/* Loại bỏ đường viền của chăn */\n/* XÓA: *:focus { phác thảo: không có;} */\n\n/* Sử dụng :focus-visible cho kiểu lấy nét chỉ bằng bàn phím */\n*:tập trung {\nphác thảo: không có;/* vẫn bỏ mặc định khi click chuột */\n}\n\n*:có thể nhìn thấy tiêu điểm {\nđường viền: var rắn 2px(--color-primary, #2563eb);\nphần bù phác thảo: 2px;\nbán kính đường viền: 2px;\n}\n\n/* Tăng cường tiêu điểm cho các phần tử tương tác cụ thể */\nnút: có thể nhìn thấy tiêu điểm,\na:có thể nhìn thấy tiêu điểm,\nđầu vào: có thể nhìn thấy tiêu điểm,\nchọn: có thể nhìn thấy tiêu điểm,\nvùng văn bản: có thể nhìn thấy tiêu điểm {\nđường viền: var rắn 2px(--color-primary, #2563eb);\nphần bù phác thảo: 2px;\nbóng hộp: 0 0 0 4px rgba(37, 99, 235, 0.2);\n}',
    explanation: ':focus-visible là một lớp giả CSS chỉ khớp khi trình duyệt xác định tiêu điểm phải được chỉ định rõ ràng - thường để điều hướng bằng bàn phím (phím Tab) chứ không phải cho nhấp chuột.Điều này mang lại cho người dùng bàn phím các vòng lấy nét rõ ràng trong khi vẫn giữ được vẻ ngoài gọn gàng mà người dùng mong đợi.Tất cả các trình duyệt hiện đại đều hỗ trợ nó.Phần bù phác thảo thêm khoảng trống giữa phần tử và đường viền.Bóng hộp cung cấp thêm ánh sáng cho các phần tử tương tác quan trọng.Không bao giờ sử dụng Outline: none mà không cung cấp các kiểu :focus-visible — nó sẽ tạo ra lỗi WCAG 2.4.7 (Focus Visible).',
  },
  'fp-016': {
    question: 'Người dùng báo cáo SPA của bạn chậm hơn theo thời gian — mức sử dụng bộ nhớ tăng từ 50 MB lên 500 MB sau một giờ.Làm thế nào để bạn chẩn đoán và khắc phục rò rỉ bộ nhớ?',
    answer: 'Sử dụng tab Bộ nhớ DevTools của Chrome: chụp nhanh vùng nhớ heap theo khoảng thời gian, so sánh phân bổ, xác định các nút DOM tách rời và trình xử lý/khoảng thời gian sự kiện không được dọn dẹp.',
    explanation: 'Quy trình chẩn đoán: 1) Mở tab Bộ nhớ DevTools của Chrome.2) Chụp ảnh nhanh đống khi tải trang.3) Sử dụng ứng dụng bình thường trong vài phút.4) Chụp ảnh nhanh khác.5) Sử dụng chế độ xem "So sánh" để xem những gì đã tăng lên.Thủ phạm phổ biến: a) Các nút DOM tách rời - các phần tử bị xóa khỏi DOM nhưng vẫn được tham chiếu trong JS (trình xử lý sự kiện, phần đóng, mảng toàn cục).b) Quên setInterval/setTimeout không được xóa khi ngắt kết nối thành phần.c) Trình xử lý sự kiện được thêm vào nhưng không bao giờ bị xóa (đặc biệt là trên cửa sổ/tài liệu).d) Đóng cửa chụp các vật thể lớn.e) Phát triển mảng/Bản đồ không bao giờ bị cắt bớt (lịch sử tin nhắn trò chuyện, bộ đệm phân tích).f) Đang tích lũy các trình xử lý WebSocket/EventSource.Khắc phục: Trong React, đảm bảo các chức năng dọn dẹp useEffect sẽ loại bỏ trình nghe và xóa bộ hẹn giờ.Sử dụng WeakRef/WeakMap cho bộ đệm.Sử dụng Trình giám sát hiệu suất trong DevTools để xem kích thước vùng nhớ heap JS trong thời gian thực.Thiết lập các bài kiểm tra hồi quy bộ nhớ tự động với Puppeteer.',
  },
  'fp-017': {
    question: 'Tập lệnh phân tích của bên thứ ba đang chặn tải trang và làm tổn hại đến LCP của bạn trong 2 giây.Chiến lược tải nào sẽ loại bỏ việc chặn hiển thị trong khi vẫn thu thập số liệu phân tích?',
    answer: '3',
    explanation: 'Đối với các tập lệnh không quan trọng của bên thứ ba như phân tích, việc tải sau khi trang tương tác hoàn toàn sẽ mang lại hiệu suất tốt nhất.requestIdleCallback kích hoạt khi trình duyệt không hoạt động, đảm bảo tập lệnh không cạnh tranh với quá trình hiển thị quan trọng.Triển khai: window.addEventListener("load", () => { requestIdleCallback(() => { const s = document.createElement("script"); s.src = "analytics.js"; document.body.appendChild(s); }); });Tùy chọn A vẫn chặn phân tích cú pháp tại thời điểm đó.Tùy chọn B (không đồng bộ) tải xuống song song nhưng thực thi ngay lập tức khi sẵn sàng — vẫn có thể chặn trong quá trình hiển thị quan trọng.Tùy chọn C (trì hoãn) chạy sau khi phân tích cú pháp nhưng trước DOMContentLoaded - tốt hơn nhưng vẫn chiếm luồng chính trong quá trình tải ban đầu.Đối với phân tích, độ trễ theo dõi vài giây là có thể chấp nhận được.',
  },
  'fp-018': {
    question: 'Triển khai giao tiếp giữa các tab để khi người dùng đăng xuất trên một tab, tất cả các tab đang mở khác trong ứng dụng của bạn cũng đăng xuất ngay lập tức.',
    answer: '// Cách 1: BroadcastChannel API (hiện đại, ưu tiên)\nkênh const = BroadcastChannel mới(\'auth-channel\');\n\n// Khi người dùng đăng xuất trong tab này:\nchức năng đăng xuất() {\nClearSession();\nkênh.postMessage({ type: \'LOGOUT\' });\nwindow.location.href = \'/login\';\n}\n\n// Nghe đăng xuất từ các tab khác:\nkênh.addEventListener(\'tin nhắn\', (sự kiện) => {\nif (event.data.type === \'ĐĂNG XUẤT\') {\nClearSession();\nwindow.location.href = \'/login\';\n}\n});\n\n// Phương pháp 2: sự kiện lưu trữ (dự phòng hỗ trợ rộng hơn)\nhàm logoutWithStorage() {\nClearSession();\nlocalStorage.setItem(\'logout-event\', Date.now().toString());\nwindow.location.href = \'/login\';\n}\n\nwindow.addEventListener(\'storage\', (event) => {\nif (event.key === \'logout-event\') {\nClearSession();\nwindow.location.href = \'/login\';\n}\n});',
    explanation: 'Hai cách tiếp cận chính: 1) BroadcastChannel API - được xây dựng có mục đích để nhắn tin nhiều tab.Tạo một kênh được đặt tên;bất kỳ tab nào có cùng tên kênh đều nhận được tin nhắn.API sạch, hỗ trợ dữ liệu có cấu trúc.Có sẵn trong tất cả các trình duyệt hiện đại.2) sự kiện lưu trữ localStorage - kích hoạt trong các tab KHÁC (không phải tab đã viết) khi giá trị thay đổi.Được hỗ trợ rộng rãi nhưng bị giới hạn ở dữ liệu chuỗi và cùng nguồn gốc.Thủ thuật sự kiện lưu trữ cũ hơn nhưng rất đáng tin cậy dưới dạng dự phòng.Các tùy chọn khác: SharedWorker (chuỗi chia sẻ giữa các tab), Service Worker postMessage (dành cho PWA).Để đăng xuất cụ thể, hãy xóa phía máy chủ cookie/mã thông báo và đặt thời hạn sử dụng mã thông báo ngắn làm biện pháp bảo vệ chuyên sâu.',
  },
  'fp-019': {
    question: 'Nút quay lại của trình duyệt không hoạt động bình thường trong SPA của bạn - nhấn lại hoặc không có tác dụng gì, chuyển đến một trang ngẫu nhiên hoặc mất trạng thái biểu mẫu.Làm thế nào để bạn khắc phục quản lý lịch sử?',
    answer: 'Sử dụng API Lịch sử đúng cách với pushState/replaceState, quản lý trạng thái trong URL và xử lý sự kiện popstate để khôi phục trạng thái ứng dụng.',
    explanation: 'Các sự cố và cách khắc phục lịch sử SPA thường gặp: 1) Quay lại không làm gì: Bạn đang thay đổi trạng thái giao diện người dùng mà không gọi history.pushState().Mọi điều hướng có ý nghĩa (chuyển tab, mở phương thức, thay đổi bộ lọc) sẽ đẩy một mục lịch sử.2) Nhảy ngẫu nhiên: Bạn đang đẩy quá nhiều mục (ví dụ: trên mỗi lần nhấn phím hoặc cuộn).Sử dụng thay thếState để cập nhật tại chỗ (ví dụ: tìm kiếm khi bạn nhập cập nhật URL mà không cần mục nhập mới).3) Trạng thái biểu mẫu bị mất: Lưu trữ dữ liệu biểu mẫu trong đối tượng trạng thái lịch sử: history.pushState({ formData: {...} }, "", "/form/step2").Trên popstate, khôi phục từ event.state.4) Xử lý sự kiện popstate để thực sự hiển thị trạng thái trước đó - chỉ lắng nghe các thay đổi URL là chưa đủ, bạn phải cập nhật giao diện người dùng.5) Đối với React: sử dụng bộ định tuyến (React Router, TanStack Router) để xử lý việc này.Nguyên tắc chính: URL là nguồn thông tin chính xác về những gì người dùng nhìn thấy.Mã hóa tất cả trạng thái giao diện người dùng có ý nghĩa trong URL (tuyến đường, thông số truy vấn, hàm băm).',
  },
  'fp-020': {
    question: 'Làm cách nào để bạn phát hiện và xử lý các kết nối mạng chậm trong ứng dụng web của mình một cách khéo léo?Người dùng trên 2G/3G thấy bố cục và thời gian chờ bị hỏng.',
    answer: 'Sử dụng API thông tin mạng để phát hiện, triển khai các mẫu tải thích ứng, thêm xử lý hết thời gian chờ và cung cấp trạng thái tải/lỗi có ý nghĩa.',
    explanation: 'Phát hiện: 1) navigator.connection.effectType trả về "4g", "3g", "2g" hoặc "slow-2g".2) navigator.connection.saveData boolean cho biết người dùng đã bật trình tiết kiệm dữ liệu.3) Lắng nghe các thay đổi: navigator.connection.addEventListener("change", handler).Chiến lược thích ứng: a) Trên kết nối chậm, phân phối hình ảnh nhỏ hơn (độ phân giải thấp), bỏ qua tính năng tự động phát video, giảm độ phức tạp của hoạt ảnh.b) Triển khai tải lũy tiến - hiển thị văn bản trước, sau đó là hình ảnh.c) Sử dụng các gói JS nhỏ hơn thông qua nhập động với tính năng phân tách mã nhận biết mạng.d) Đặt thời gian chờ tìm nạp thích hợp (thời gian chờ ngắn hơn + thử lại so với chờ vô hạn).e) Tích cực lưu vào bộ nhớ đệm với Nhân viên dịch vụ để các lượt truy cập lặp lại hoạt động ngoại tuyến.f) Hiển thị màn hình khung xương thay vì vòng quay.g) Sử dụng mẫu bộ nhớ đệm cũ trong khi xác nhận lại.h) Tải trước các tài nguyên quan trọng.Luôn kiểm tra các kết nối được điều chỉnh (tab Mạng Chrome DevTools: Cài đặt trước 3G chậm).',
  },
  'fp-021': {
    question: 'Triển khai nhân viên dịch vụ cho PWA ngoại tuyến đầu tiên với chiến lược bộ nhớ đệm cũ trong khi xác thực lại cho lệnh gọi API và ưu tiên bộ nhớ đệm cho nội dung tĩnh.',
    answer: '// service-worker.js\nconst STATIC_CACHE = \'static-v1\';\nconst API_CACHE = \'api-v1\';\n\nconst STATIC_ASSETS = [\n\'/\',\n\'/index.html\',\n\'/styles.css\',\n\'/app.js\',\n\'/offline.html\',\n];\n\n// Cài đặt: lưu trước nội dung tĩnh vào bộ đệm\nself.addEventListener(\'install\', (event) => {\nsự kiện.waitUntil(\ncaches.open(STATIC_CACHE).then((cache) => cache.addAll(STATIC_ASSETS))\n);\nself.skipWaiting();\n});\n\n// Kích hoạt: dọn dẹp bộ đệm cũ\nself.addEventListener(\'kích hoạt\', (sự kiện) => {\nsự kiện.waitUntil(\ncaches.keys().then((keys) =>\nHứa.tất cả(\nphím\n.filter((key) => key !== STATIC_CACHE && key !== API_CACHE)\n.map((key) => caches.delete(key))\n)\n)\n);\nself.clients.claim();\n});\n\n// Tìm nạp: chiến lược dựa trên loại yêu cầu\nself.addEventListener(\'tìm nạp\', (sự kiện) => {\nconst { yêu cầu } = sự kiện;\nconst url = URL mới(request.url);\n\nif (url.pathname.startsWith(\'/api/\')) {\n// Stale-while-revalidate cho lệnh gọi API\nevent.respondWith(stale WhileRevalidate(request, API_CACHE));\n} khác {\n// Bộ nhớ đệm đầu tiên cho nội dung tĩnh\nsự kiện.respondWith(cacheFirst(request, STATIC_CACHE));\n}\n});\n\nchức năng không đồng bộ cacheFirst(request, cacheName) {\nconst cached = đang chờ caches.match(request);\nnếu (được lưu trong bộ nhớ đệm) trả về được lưu trong bộ nhớ đệm;\nthử {\nphản hồi const = đang chờ tìm nạp (yêu cầu);\nconst cache = đang chờ caches.open(cacheName);\ncache.put(request, reply.clone());\ntrả lời phản hồi;\n} bắt {\ntrả về caches.match(\'/offline.html\');\n}\n}\n\nchức năng không đồng bộ stalewhileRevalidate(request, cacheName) {\nconst cache = đang chờ caches.open(cacheName);\nconst cached = đang chờ cache.match(request);\n\nconst getPromise = tìm nạp (yêu cầu)\n.then((phản hồi) => {\ncache.put(request, reply.clone());\ntrả lời phản hồi;\n})\n.catch(() => đã lưu vào bộ nhớ đệm);// dự phòng vào bộ đệm nếu mạng bị lỗi\n\ntrả về bộ nhớ đệm ||tìm nạpPromise;\n}',
    explanation: 'Nhân viên dịch vụ này sử dụng hai chiến lược: 1) Ưu tiên lưu vào bộ nhớ đệm cho nội dung tĩnh — kiểm tra bộ nhớ đệm trước, quay lại mạng và lưu vào bộ nhớ đệm phản hồi.Nếu cả hai đều không thành công, hãy hiển thị một trang ngoại tuyến.Điều này nhanh chóng và hoạt động ngoại tuyến.2) Cũ-trong khi xác nhận lại cho các lệnh gọi API - trả về dữ liệu được lưu trong bộ nhớ đệm ngay lập tức để tăng tốc, sau đó tìm nạp dữ liệu mới ở chế độ nền và cập nhật bộ nhớ đệm.Yêu cầu tiếp theo nhận được dữ liệu mới.Việc vô hiệu hóa bộ nhớ đệm xảy ra thông qua tên bộ nhớ đệm đã được phiên bản (STATIC_CACHE = "static-v1") — khi cập nhật, chỉnh sửa phiên bản và trình xử lý kích hoạt sẽ xóa bộ nhớ đệm cũ.SkipWaiting() + client.claim() đảm bảo nhân viên mới sẽ tiếp quản ngay lập tức.',
  },
  'fp-022': {
    question: 'Bạn cần tải từng phần hình ảnh khi chúng cuộn vào chế độ xem.Triển khai điều này bằng API trình duyệt hiện đại (không có thư viện).',
    answer: '<!-- HTML: sử dụng loading="lazy" để tải từng phần -->\n<hình ảnh\nsrc="anh hùng.jpg"\nalt="Biểu ngữ anh hùng"\nchiều rộng="800"\nchiều cao="400"\nđang tải="lười biếng"\ngiải mã="async"\n/>\n\n<!-- Để kiểm soát tốt hơn, hãy sử dụng IntersectionObserver -->\n<hình ảnh\ndữ liệu-src="photo.jpg"\nalt="Ảnh"\nlớp="lười biếng"\nchiều rộng="400"\nchiều cao="300"\n/>\n\n<kịch bản>\nconst người quan sát = máy chủ IntersectionOb mới (\n(mục nhập) => {\nmục.forEach((entry) => {\nif (entry.isIntersecting) {\nconst img = entry.target;\nimg.src = img.dataset.src;\nimg.classList.remove(\'lười biếng\');\nngười quan sát.unobserve(img);\n}\n});\n},\n{ rootMargin: \'200px\' } // bắt đầu tải 200px trước khi hiển thị\n);\n\ndocument.querySelectorAll(\'img.lazy\').forEach((img) => {\nngười quan sát.observe(img);\n});\n</script>',
    explanation: 'Hai cách tiếp cận: 1) Thuộc tính loading="lazy" gốc — đơn giản nhất, được tích hợp sẵn trong trình duyệt, không cần JS.Trình duyệt quyết định thời điểm tải dựa trên vị trí cuộn và tốc độ kết nối.Thêm thuộc tính chiều rộng/chiều cao để ngăn chặn sự thay đổi bố cục (CLS).2) IntersectionObserver — kiểm soát nhiều hơn khi tải trình kích hoạt (rootMargin đặt khoảng cách bắt đầu trước).Sử dụng data-src để giữ URL cho đến khi hình ảnh ở gần khung nhìn.Luôn bao gồm chiều rộng và chiều cao trên hình ảnh để ngăn ngừa CLS.decoding="async" yêu cầu trình duyệt giải mã hình ảnh khỏi luồng chính.Đối với các hình ảnh trong màn hình đầu tiên, KHÔNG tải chúng một cách lười biếng - điều này sẽ gây tổn hại đến LCP.Chỉ tải các hình ảnh dưới màn hình đầu tiên.',
  },
  'fp-023': {
    question: 'Ứng dụng của bạn có đầu vào tìm kiếm kích hoạt lệnh gọi API sau mỗi lần nhấn phím, gây ra giới hạn tốc độ và hiện tượng giật giao diện người dùng.Thực hiện tìm kiếm bị trả lại với tính năng dọn dẹp thích hợp.',
    answer: '// Vanilla JS gỡ lỗi bằng cách dọn dẹp\nhàm gỡ lỗi(fn, delay) {\nhãy hết thời gianId;\nconst đã được gỡ bỏ = (...args) => {\nClearTimeout(timeoutId);\ntimeoutId = setTimeout(() => fn(...args), delay);\n};\ndebounced.cancel = () => clearTimeout(timeoutId);\ntrả lại bị trả lại;\n}\n\n// Sử dụng với AbortController để hủy các yêu cầu trên chuyến bay\nconst searchInput = document.getElementById(\'search\');\nhãy abortController = null;\n\nconst handSearch = debounce(async (truy vấn) => {\nif (abortController) abortController.abort();\nabortController = new AbortController();\n\nthử {\nconst res = đang chờ tìm nạp(`/api/search?q=${encodeURIComponent(query)}`, {\ntín hiệu: abortController.signal,\n});\ndữ liệu const = đang chờ res.json();\nrenderResults(dữ liệu);\n} bắt (lỗi) {\nif (err.name !== \'AbortError\') {\nshowError(err.message);\n}\n}\n}, 300);\n\nsearchInput.addEventListener(\'input\', (e) => {\nhandSearch(e.target.value);\n});\n\n// Dọn dẹp khi tải trang / ngắt kết nối thành phần\n// xử lýSearch.cancel();',
    explanation: 'Việc gỡ lỗi trì hoãn việc thực thi cho đến khi người dùng ngừng nhập trong khoảng thời gian được chỉ định (300 mili giây là một mặc định phù hợp).Chi tiết chính: 1) ClearTimeout trên mỗi lần nhấn phím sẽ đặt lại bộ hẹn giờ.2) AbortController hủy mọi tìm nạp đang diễn ra khi một tìm kiếm mới kích hoạt - ngăn chặn các điều kiện chạy đua trong đó phản hồi chậm cũ ghi đè lên kết quả mới hơn.3) Lọc AbortError trong khối bắt vì nó được mong đợi.4) Phương thức cancel() cho phép dọn dẹp khi ngắt kết nối.5) EncodeURIComponent ngăn chặn việc tiêm qua chuỗi truy vấn.Đối với React, hãy sử dụng cùng một mẫu bên trong useEffect với chức năng dọn dẹp hoặc sử dụng hook useDeferredValue để hiển thị đầu vào tìm kiếm.',
  },
  'fp-024': {
    question: 'Công ty của bạn cần nhúng tiện ích vào trang web của bên thứ ba.Tiện ích phải có phong cách riêng, hiệu quả và an toàn.Làm thế nào để bạn kiến ​​trúc này?',
    answer: 'Sử dụng Shadow DOM để tách biệt kiểu, hộp cát iframe để bảo mật, tập lệnh tải nhỏ và postMessage để liên lạc.',
    explanation: 'Kiến trúc: 1) Tập lệnh trình tải: Cung cấp thẻ tập lệnh nhỏ (<2KB) mà bên thứ ba nhúng.Tập lệnh này tạo vùng chứa tiện ích và tải tiện ích thực tế một cách không đồng bộ.2) Cách ly kiểu: Sử dụng Shadow DOM để đóng gói CSS của tiện ích - kiểu trang chủ không thể tràn vào và kiểu tiện ích không thể rò rỉ ra ngoài.Đính kèm gốc bóng với chế độ: "đóng" để đóng gói mạnh hơn.3) Bảo mật: Nếu tiện ích xử lý dữ liệu nhạy cảm (thanh toán, xác thực), hãy hiển thị tiện ích đó trong iframe được đóng hộp cát trên miền của bạn.Sử dụng postMessage để liên lạc giữa cha mẹ và con cái với việc kiểm tra nguồn gốc nghiêm ngặt.4) Hiệu suất: Gói tiện ích riêng biệt, rung cây mạnh mẽ, nén mục tiêu < 50KB.Tải sau khi trang chủ tương tác (trì hoãn).Sử dụng kết nối trước với CDN của bạn.5) Lập phiên bản: Lưu trữ trên CDN có semver trong URL (widget.example.com/v2/loader.js).6) CSP: Tài liệu yêu cầu chỉ thị Chính sách-Bảo mật-Nội dung cho các trang web lưu trữ.7) Thay đổi kích thước: Sử dụng ResizeObserver để điều chỉnh kích thước vùng chứa.',
  },
  'fp-025': {
    question: 'Người dùng gửi biểu mẫu nhưng không có gì xảy ra — không có lỗi, không có chuyển hướng.Bạn kiểm tra bảng điều khiển và thấy việc gửi biểu mẫu mặc định đã bị ngăn nhưng lệnh gọi tìm nạp JavaScript không thành công.Nguyên nhân có thể xảy ra nhất là gì?',
    answer: '1',
    explanation: 'Nguyên nhân phổ biến nhất dẫn đến "thất bại thầm lặng" là do lời hứa bị từ chối không được xử lý.Nếu tìm nạp() không thành công (lỗi mạng, CORS, v.v.) và không có .catch() hoặc thử/bắt, lỗi sẽ biến mất một cách âm thầm.Người dùng không thấy gì vì PreventDefault() đã ngừng gửi bản gốc.Khắc phục: Luôn gói tìm nạp trong thử/bắt, hiển thị giao diện người dùng lỗi trong khối bắt và thêm trình xử lý window.addEventListener("unhandledrejection") chung làm mạng an toàn.Đồng thời kiểm tra: reply.ok không tự động đúng - trạng thái 400/500 không gây ra lỗi, bạn phải kiểm tra thủ công.',
  },
  'fp-026': {
    question: 'Điểm Lighthouse là 45. Hãy áp dụng cách tiếp cận có hệ thống của bạn để đạt được điểm trên 90.',
    answer: 'Ưu tiên theo tác động của Core Web Vitals: sửa LCP trước (hình ảnh, phông chữ, tài nguyên chặn hiển thị), sau đó là CLS (thay đổi bố cục), sau đó là INP (khả năng phản hồi tương tác), sau đó là kiểm tra các phần còn lại.',
    explanation: 'Cách tiếp cận có hệ thống: Giai đoạn 1 - LCP (đích < 2,5 giây): a) Tối ưu hóa hình ảnh chính: sử dụng các định dạng hiện đại (WebP/AVIF), định cỡ phù hợp (srcset), tải trước hình ảnh LCP.b) Loại bỏ CSS/JS chặn kết xuất: CSS quan trọng nội tuyến, trì hoãn không quan trọng.c) Tối ưu hóa phông chữ: hiển thị phông chữ: hoán đổi, tải trước phông chữ chính, sử dụng ngăn xếp phông chữ hệ thống cho nội dung.d) Máy chủ: bật tính năng nén (Brotli > gzip), HTTP/2, CDN.Giai đoạn 2 - CLS (mục tiêu < 0,1): a) Thêm chiều rộng/chiều cao cho tất cả hình ảnh/video.b) Dành không gian cho nội dung động (quảng cáo, nội dung nhúng).c) Tránh chèn nội dung vào màn hình đầu tiên sau khi tải.Giai đoạn 3 - INP (mục tiêu < 200ms): a) Phá vỡ các tác vụ dài với năng suất/lập lịch.yield().b) Giảm công việc của luồng chính: trì hoãn JS không quan trọng, sử dụng web Workers.c) Tối ưu hóa việc xử lý sự kiện.Giai đoạn 4: Cho phép nén văn bản, giảm JS/CSS không sử dụng, thêm gợi ý tài nguyên (kết nối trước, tìm nạp trước).Đo lường trong quá trình sản xuất bằng thư viện web-vitals chứ không chỉ với Lighthouse.',
  },
  'fp-027': {
    question: 'Thời gian hiển thị nội dung đầu tiên là 4,5 giây.HTML tải trong 600 mili giây nhưng không có gì hiển thị cho đến khi gói JavaScript tải xong.Làm thế nào để bạn chẩn đoán và khắc phục điều này?',
    answer: 'Ứng dụng được hiển thị phía máy khách không có SSR/SSG.Khắc phục bằng cách triển khai kết xuất phía máy chủ, nội tuyến CSS quan trọng và giảm JS cần thiết cho lần vẽ đầu tiên.',
    explanation: 'Chẩn đoán: Mở tab Hiệu suất DevTools của Chrome và ghi lại lượt tải trang.Nhìn vào đoạn phim - nếu nó trống trong vài giây thì JS đang chặn hiển thị.Kiểm tra thác mạng: nếu HTML đến nhanh nhưng gói JS lớn phải tải xuống, phân tích cú pháp và thực thi trước khi vẽ, thì đó là nút cổ chai CSR.Cách khắc phục: 1) SSR/SSG: Kết xuất trước HTML trên máy chủ để trình duyệt có thể vẽ ngay lập tức.Trong Next.js, hãy sử dụng các thành phần máy chủ getServerSideProps hoặc App Router.2) CSS quan trọng nội tuyến trong <head> để lần vẽ đầu tiên không chờ các tệp CSS.3) Tách mã: Sử dụng tính năng nhập động để ban đầu chỉ tải mã cho trang hiện tại.4) Thêm shell/skeleton HTML tĩnh trong index.html cho các SPA thuần túy để nội dung nào đó hiển thị trước JS.5) Tải trước các tài nguyên chính: <link rel="preload" as="script"> cho JS quan trọng.6) Giảm thời gian phân tích cú pháp JS: rung cây, loại bỏ polyfill cho các trình duyệt hiện đại, nén bằng Brotli.',
  },
  'fp-028': {
    question: 'Trang web thương mại điện tử của bạn có hơn 50 hình ảnh sản phẩm trên mỗi trang và hình ảnh mất quá nhiều thời gian để tải.Thiết kế một chiến lược tối ưu hóa hình ảnh hoàn chỉnh.',
    answer: 'Sử dụng các định dạng hiện đại (AVIF/WebP), srcset đáp ứng, tải chậm, CDN với các phép biến đổi, kỹ thuật giữ chỗ làm mờ và bộ nhớ đệm thích hợp.',
    explanation: 'Chiến lược hoàn chỉnh: 1) Định dạng: Cung cấp AVIF với dự phòng WebP bằng phần tử <picture>.AVIF nhỏ hơn 50% so với JPEG, WebP nhỏ hơn 30%.2) Đáp ứng: Sử dụng thuộc tính srcset + size để cung cấp kích thước phù hợp cho từng khung nhìn.Không gửi hình ảnh 2000px tới vùng chứa 400px.3) Tải chậm: loading="lazy" trên các hình ảnh ở màn hình đầu tiên bên dưới.KHÔNG lười tải hàng hiển thị đầu tiên.4) Chuyển đổi hình ảnh CDN: Sử dụng CDN hình ảnh (Tối ưu hóa hình ảnh Cloudinary, imgix hoặc Vercel) để tự động thay đổi kích thước, chuyển đổi định dạng và lưu vào bộ nhớ đệm ở rìa.Nối ?w=400&f=avif vào URL.5) Trình giữ chỗ: Hiển thị LQIP bị mờ (Trình giữ chỗ hình ảnh chất lượng thấp) hoặc trình giữ chỗ màu chủ đạo trong khi tải hình ảnh đầy đủ.6) Kích thước: Luôn đặt chiều rộng/chiều cao hoặc tỷ lệ khung hình để ngăn CLS.7) Bộ đệm: Đặt Kiểm soát bộ đệm: công khai, độ tuổi tối đa=31536000, không thay đổi đối với URL hình ảnh được băm.8) Tải trước: <link rel="preload"> cho hình ảnh LCP.Ngân sách: < 200KB cho mỗi hình ảnh trên thiết bị di động.',
  },
  'fp-029': {
    question: 'Gói JS của bạn có dung lượng không nén là 2 MB (được nén bằng 650KB).Làm thế nào để bạn phân tích những gì trong đó và giảm kích thước?',
    answer: 'Sử dụng trình phân tích gói để trực quan hóa, sau đó áp dụng phân tách mã, rung cây, kiểm tra phần phụ thuộc và nhập động để giảm kích thước.',
    explanation: 'Bước 1 - Phân tích: Chạy webpack-bundle-analyzer hoặc source-map-explorer để trực quan hóa những gì trong gói.Những phát hiện chung: a) Một thư viện khổng lồ (moment.js, lodash full build).b) Phụ thuộc trùng lặp (hai phiên bản của cùng một thư viện).c) Mã thùng xuất khẩu chưa sử dụng.Bước 2 — Thắng nhanh: a) Thay thế các thư viện nặng: moment.js -> date-fns hoặc dayjs (70KB -> 2KB).lodash -> lodash-es có rung cây hoặc nhập riêng lẻ.b) Loại bỏ các dep trùng lặp: npm dedupe, kiểm tra package-lock.c) Sử dụng tính năng nhập động () cho các tuyến đường và các tính năng nặng (biểu đồ, trình chỉnh sửa, trình xem PDF).Bước 3 - Tách mã: Chia theo tuyến (mỗi trang chỉ tải mã của nó).Tách riêng các phần của nhà cung cấp (chúng thay đổi ít hơn, bộ nhớ đệm tốt hơn).Bước 4 — Rung cây: Đảm bảo tất cả các bộ phận đều sử dụng mô-đun ES.Tránh các tập tin thùng có tác dụng phụ.Thêm "sideEffects": false vào pack.json.Bước 5 — Nén: Nén trước Brotli tại thời điểm xây dựng (nhỏ hơn 30% so với gzip).Mục tiêu: < 200KB được nén cho lần tải đầu tiên.',
  },
  'fp-030': {
    question: 'Triển khai màn hình tải khung trong HTML/CSS khớp với bố cục thẻ với hình ảnh, tiêu đề và hai dòng văn bản.',
    answer: '<!-- Thẻ bộ xương -->\n<div class="bộ xương-thẻ">\n<div class="hình ảnh bộ xương"></div>\n<div class="bộ xương-title"></div>\n<div class="văn bản khung xương"></div>\n<div class="bộ xương-văn bản bộ xương--ngắn"></div>\n</div>\n\n<phong cách>\n.skeleton-card {\nphần đệm: 16px;\nbán kính đường viền: 8px;\nnền: var(--surface, #fff);\n}\n\n.bộ xương {\nnền: gradient tuyến tính(\n90 độ,\n#e0e0e0 25%,\n#f0f0f0 50%,\n#e0e0e0 75%\n);\nkích thước nền: 200% 100%;\nhình ảnh động: lung linh 1,5 giây dễ dàng ra vào vô hạn;\nbán kính đường viền: 4px;\n}\n\n.skeleton-hình ảnh {\nchiều rộng: 100%;\ntỷ lệ khung hình: 16/9;\nlề dưới: 12px;\n}\n\n.skeleton-title {\nchiều cao: 24px;\nchiều rộng: 70%;\nlề dưới: 12px;\n}\n\n.skeleton-text {\nchiều cao: 16px;\nchiều rộng: 100%;\nlề dưới: 8px;\n}\n\n.skeleton-text--short {\nchiều rộng: 60%;\n}\n\n@keyframes lung linh {\n0% { vị trí nền: 200% 0;}\n100% { vị trí nền: -200% 0;}\n}\n\n/* Tôn trọng ưu tiên chuyển động giảm */\n@media (thích-giảm-chuyển động: giảm) {\n.bộ xương {\nhoạt hình: không có;\nnền: #e0e0e0;\n}\n}\n</style>',
    explanation: 'Màn hình Skeleton vượt trội hơn các màn hình quay về hiệu suất cảm nhận vì chúng hiển thị hình dạng của nội dung sắp ra mắt, đặt ra kỳ vọng của người dùng.Nguyên tắc chính: 1) Phù hợp với bố cục nội dung thực tế — cùng chiều rộng, chiều cao và khoảng cách như thẻ thật.2) Sử dụng hoạt ảnh lung linh (chuyển động chuyển màu) để biểu thị đang tải.3) Tôn trọng ưu tiên giảm chuyển động bằng cách tắt hoạt ảnh đối với những người dùng thích nó.4) Sử dụng tỷ lệ khung hình cho trình giữ chỗ hình ảnh để duy trì tỷ lệ.5) Thay đổi độ rộng dòng văn bản (100%, 60%) để bắt chước văn bản tự nhiên.6) Giữ thành phần khung dưới dạng cấu trúc HTML nhẹ, riêng biệt - không bao bọc thành phần thực bằng các trạng thái tải làm tăng kích thước DOM.',
  },
  'fp-031': {
    question: 'Điểm CLS là 0,3 (kém - ngưỡng là 0,1).Người dùng thấy nội dung nhảy lung tung khi tải trang.Làm thế nào để bạn xác định nguyên nhân và khắc phục chúng?',
    answer: 'Sử dụng trình gỡ lỗi Layout Shift, xác định các yếu tố gây ra thay đổi (hình ảnh, quảng cáo, phông chữ, nội dung động) và dành khoảng trống cho từng yếu tố.',
    explanation: 'Chẩn đoán: 1) Tab Hiệu suất DevTools của Chrome - bật "Vùng thay đổi bố cục" để hiển thị các thay đổi bằng màu xanh lam.2) Tiện ích mở rộng Web Vitals hiển thị CLS theo thời gian thực.3) PerformanceObserver với loại "layout-shift" ghi lại mỗi ca với các phần tử đã di chuyển.Các nguyên nhân thường gặp và cách khắc phục: a) Hình ảnh không có kích thước: Thêm thuộc tính chiều rộng + chiều cao hoặc sử dụng CSS tỷ lệ khung hình.b) Quảng cáo/nội dung nhúng: Đặt trước kích thước vùng chứa cố định với chiều cao tối thiểu trước khi tải quảng cáo.c) Phông chữ web: Sử dụng hiển thị phông chữ: hoán đổi với điều chỉnh kích thước và ghi đè tăng dần để khớp với số liệu phông chữ dự phòng hoặc sử dụng bộ mô tả @font-face để giảm thiểu hiện tượng phản xạ.d) Chèn nội dung động: Không bao giờ chèn nội dung lên trên nội dung hiển thị hiện có.Nếu bạn phải (biểu ngữ, thông báo), hãy sử dụng hoạt ảnh chuyển đổi thay vì thuộc tính kích hoạt bố cục.e) CSS được tải muộn: CSS quan trọng nội tuyến.f) Kết xuất phía máy khách: Sử dụng SSR để gửi HTML cuối cùng.Kiểm tra: Chạy Lighthouse khi điều chỉnh tốc độ chậm - CLS thường kém hơn khi kết nối chậm.',
  },
  'fp-032': {
    question: 'Bạn có một trang có bảng dữ liệu lớn (10.000 hàng).Hiển thị tất cả các hàng khiến trang bị treo trong 3 giây khi tải.Cách tiếp cận tốt nhất là gì?',
    answer: '1',
    explanation: 'Cuộn ảo (cửa sổ) chỉ hiển thị các hàng hiển thị trong khung nhìn (cộng với một bộ đệm nhỏ).Khi người dùng cuộn, các hàng sẽ được tái chế — các phần tử rời khỏi khung nhìn sẽ bị xóa và các phần tử mới sẽ được thêm vào ở cạnh cuộn.Điều này giữ cho số lượng nút DOM ở mức thấp (~50 nút thay vì 10.000).Thư viện: TanStack Virtual, cửa sổ phản ứng, phản ứng điêu luyện.Triển khai: vùng chứa có chiều cao cố định với tràn: tự động, các hàng được định vị tuyệt đối dựa trên độ lệch cuộn và phần tử đệm để duy trì kích thước thanh cuộn chính xác.Tùy chọn A vẫn tạo 10.000 nút DOM.Tùy chọn C tải tất cả dữ liệu nhưng không giải quyết được nút thắt cổ chai hiển thị.Tùy chọn D (batching) tốt hơn đồng bộ nhưng cuối cùng vẫn tạo ra 10.000 nút.',
  },
  'fp-033': {
    question: 'Bạn được giao nhiệm vụ thiết lập hệ thống lập ngân sách và giám sát hiệu suất cho một nhóm gồm 12 nhà phát triển.Làm cách nào để ngăn chặn tình trạng hồi quy hiệu suất trong CI/CD?',
    answer: 'Triển khai ngân sách hiệu suất trong CI, giám sát người dùng thực (RUM) trong sản xuất, Lighthouse tự động trong kiểm tra PR và theo dõi kích thước gói.',
    explanation: 'Hệ thống toàn diện: 1) Ngân sách hiệu suất: Xác định ngưỡng trong tệp cấu hình - Gói JS < 200KB, CSS < 50KB, LCP < 2,5 giây, CLS < 0,1, INP < 200ms.2) Kiểm tra CI: Chạy Lighthouse CI (lhci) trên mọi PR đối với việc triển khai theo giai đoạn.Thất bại trong PR nếu vượt quá ngân sách.Sử dụng kích thước gói hoặc giới hạn kích thước để kiểm tra kích thước gói trong CI - hiển thị sự khác biệt trong nhận xét PR.3) RUM (Giám sát người dùng thực): Triển khai thư viện quan trọng trên web để thu thập CWV từ người dùng thực.Gửi tới bộ phận phân tích (SpeedCurve, Datadog hoặc điểm cuối tùy chỉnh).Trang tổng quan hiển thị chỉ số quan trọng p75 theo trang và loại thiết bị.4) Cảnh báo: Thiết lập cảnh báo khi p75 CWV vượt quá ngưỡng.5) Quy trình PR: Nhận xét tự động về các PR hiển thị delta kích thước gói và delta điểm Lighthouse.6) Đào tạo dành cho nhà phát triển: Đánh giá hiệu suất hàng tháng của các trang chính, bảng điều khiển được chia sẻ trên TV nhóm, các mẫu tối ưu hóa tài liệu trong sổ tay của nhóm.7) Giám sát tổng hợp: Ngọn hải đăng theo lịch trình chạy từ nhiều địa điểm (SpeedCurve, WebPageTest).Điều này nắm bắt các hồi quy do thay đổi dữ liệu/nội dung, không chỉ mã.',
  },
  'fp-034': {
    question: 'Trang của bạn có các trình xử lý sự kiện cuộn đắt tiền gây ra hiện tượng giật (rớt khung hình).Trình xử lý tính toán lại vị trí phần tử trên mỗi sự kiện cuộn.Tối ưu hóa nó.',
    answer: '// Tối ưu hóa: sử dụng IntersectionObserver + requestAnimationFrame\n// 1. Phát hiện khả năng hiển thị với IntersectionObserver (không cần trình nghe cuộn)\nconst người quan sát = máy chủ IntersectionOb mới (\n(mục nhập) => {\nmục.forEach((entry) => {\nif (entry.isIntersecting) {\nentry.target.classList.add(\'visible\');\nngười quan sát.unobserve(entry.target);// dừng xem khi nhìn thấy\n}\n});\n},\n{ ngưỡng: 0,1 }\n);\n\ndocument.querySelectorAll(\'.animate-on-scroll\').forEach((el) => {\nngười quan sát.observe(el);\n});\n\n// 2. Hiệu ứng thị sai với điều chỉnh rAF\nhãy đánh dấu = sai;\nwindow.addEventListener(\'scroll\', () => {\nnếu (! tích tắc) {\nrequestAnimationFrame(() => {\ncập nhậtParallax();\nđánh dấu = sai;\n});\ntích tắc = đúng;\n}\n}, { bị động: đúng });\n\nhàm cập nhậtParallax() {\n// Cache querySelectorAll kết quả bên ngoài bộ xử lý\nparallaxElements.forEach((el) => {\n// Sử dụng biến đổi (thân thiện với bộ tổng hợp, không kích hoạt bố cục)\nconst offset = el.dataset.offset ||0,5;\nel.style.transform = `translateY(${window.scrollY * offset}px)`;\n});\n}\n\nconst parallaxElements = document.querySelectorAll(\'.parallax\');',
    explanation: 'Ba tối ưu hóa: 1) Thay thế kiểm tra khả năng hiển thị dựa trên cuộn bằng IntersectionObserver — nó chạy khỏi luồng chính và chỉ kích hoạt khi các phần tử vào/rời khỏi khung nhìn.2) Điều chỉnh cuộn còn lại hoạt động với requestAnimationFrame (rAF) — đảm bảo trình xử lý chạy tối đa một lần trên mỗi khung hình (60 khung hình/giây).Cờ tích tắc ngăn xếp hàng nhiều lệnh gọi lại rAF.3) Thêm { Passive: true } vào trình nghe cuộn - cho trình duyệt biết trình xử lý sẽ không gọi PreventDefault(), cho phép tối ưu hóa cuộn.Bổ sung: lưu trữ các truy vấn DOM bên ngoài trình xử lý (querySelectorAll đắt tiền), sử dụng biến đổi thay vì trên/trái (chỉ kích hoạt tổng hợp, không kích hoạt bố cục) và tránh getBoundingClientRect trong trình xử lý cuộn (buộc bố cục đồng bộ).',
  },
  'fp-035': {
    question: 'Các tệp phông chữ của bạn có tổng dung lượng 800KB và văn bản sẽ không hiển thị trong 2 giây khi tải phông chữ (FOIT).Cách nhanh nhất để hiển thị văn bản ngay lập tức là gì?',
    answer: '1',
    explanation: 'font-display: swap hiển thị văn bản ngay lập tức bằng phông chữ hệ thống dự phòng, sau đó chuyển sang phông chữ tùy chỉnh sau khi tải.Không có văn bản vô hình.Tải trước (<link rel="preload" href="font.woff2" as="font" crossorigin>) bắt đầu tải xuống sớm, giảm thời gian trao đổi.Tối ưu hóa bổ sung: a) Chỉ sử dụng định dạng woff2 (nén tốt nhất, hỗ trợ phổ quát).b) Tập hợp phông chữ chỉ bao gồm các ký tự cần thiết (tập hợp con tiếng Latin có thể cắt 80% phông chữ CJK).c) Tự lưu trữ thay vì Google Fonts (loại bỏ việc tra cứu DNS bổ sung).d) Sử dụng tính năng điều chỉnh kích thước, ghi đè lên, ghi đè xuống trên @font-face để khớp với các chỉ số phông chữ dự phòng — giảm thiểu sự thay đổi bố cục trong quá trình hoán đổi.e) Giới hạn tối đa 2-3 tệp phông chữ.Tùy chọn A làm phình CSS và chặn hiển thị.Tùy chọn D khiến văn bản vô hình thậm chí còn dài hơn.Tùy chọn C đã lỗi thời.',
  },
  'fp-036': {
    question: 'QA báo cáo rằng trình đọc màn hình không thể điều hướng bảng dữ liệu của bạn — nó đọc các ô không theo thứ tự và tiêu đề cột không được liên kết với các ô dữ liệu.Hãy sửa cái bảng này.',
    answer: '<!-- Đã sửa: bảng ngữ nghĩa có tiêu đề phù hợp -->\n<bảng>\n<caption>Thành viên nhóm</caption>\n<đầu>\n<tr>\n<th phạm vi="col">Tên</th>\n<th phạm vi="col">Email</th>\n<th phạm vi="col">Vai trò</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Alice</td>\n<td>alice@co.com</td>\n<td>Quản trị viên</td>\n</tr>\n</tbody>\n</bảng>\n\n<!-- Nếu bạn PHẢI sử dụng div (ví dụ: cuộn ảo), hãy thêm vai trò ARIA -->\n<div role="table" aria-label="Thành viên nhóm">\n<div vai trò="rowgroup">\n<div vai trò="hàng">\n<div role="columnheader">Tên</div>\n<div role="columnheader">Email</div>\n<div role="columnheader">Vai trò</div>\n</div>\n</div>\n<div vai trò="rowgroup">\n<div vai trò="hàng">\n<div role="cell">Alice</div>\n<div role="cell">alice@co.com</div>\n<div role="cell">Quản trị viên</div>\n</div>\n</div>\n</div>',
    explanation: 'Trình đọc màn hình sử dụng ngữ nghĩa của bảng để cho phép người dùng điều hướng theo hàng và cột (Ctrl+Alt+Phím mũi tên trong NVDA/JAWS).Nếu không có <table>, <th> và <td>, người đọc sẽ thấy một danh sách các div phẳng.Các thành phần chính: 1) <caption> đặt cho bảng một tên có thể truy cập được.2) <thscope="col"> liên kết từng tiêu đề với cột của nó — trình đọc màn hình sẽ thông báo "Tên: Alice" khi điều hướng xuống dưới.3) <thead>/<tbody> cung cấp ngữ nghĩa nhóm.4) Đối với tiêu đề hàng, hãy sử dụng <thscope="row">.Nếu bạn phải sử dụng div (đối với thư viện cuộn ảo), hãy sao chép mô hình bảng ARIA đầy đủ với role="table", role="row", role="columnheader" và role="cell".Nhưng các bảng HTML gốc luôn được ưu tiên hơn.',
  },
  'fp-037': {
    question: 'Triển khai menu thả xuống có thể điều hướng bằng bàn phím với các thuộc tính ARIA thích hợp.Người dùng có thể mở nó bằng Enter/Space, điều hướng bằng các phím mũi tên và đóng bằng Escape.',
    answer: '<div class="dropdown">\n<nút\nid="nút menu"\naria-haspopup="true"\naria-expanded="false"\naria-controls="menu-list"\n>\nTùy chọn ▾\n</button>\n<ul\nid="danh sách menu"\nvai trò="menu"\naria-labelledby="nút menu"\nẩn giấu\n>\n<li role="menuitem" tabindex="-1">Chỉnh sửa</li>\n<li role="menuitem" tabindex="-1">Trùng lặp</li>\n<li role="menuitem" tabindex="-1">Xóa</li>\n</ul>\n</div>\n\n<kịch bản>\nnút const = document.getElementById(\'menu-button\');\nconst menu = document.getElementById(\'menu-list\');\nconst items = menu.querySelectorAll(\'[role="menuitem"]\');\nđặt currentIndex = -1;\n\nhàm openMenu() {\nmenu.hidden = false;\nnút.setAttribution(\'aria-expanded\', \'true\');\ncurrentIndex = 0;\nitems[currentIndex].focus();\n}\n\nhàm closeMenu() {\nmenu.hidden = true;\nnút.setAttribution(\'aria-expanded\', \'false\');\nchỉ số hiện tại = -1;\nnút.focus();// trả lại tiêu điểm để kích hoạt\n}\n\nnút.addEventListener(\'click\', () => {\nmenu.hidden ?openMenu() : closeMenu();\n});\n\nnút.addEventListener(\'keydown\', (e) => {\nif (e.key === \'ArrowDown\' || e.key === \'Enter\' || e.key === \' \') {\ne.preventDefault();\nopenMenu();\n}\n});\n\nmenu.addEventListener(\'keydown\', (e) => {\nchuyển đổi (e.key) {\ntrường hợp \'Mũi tên xuống\':\ne.preventDefault();\ncurrentIndex = (currentIndex + 1) % items.length;\nitems[currentIndex].focus();\nphá vỡ;\ntrường hợp \'Mũi tên lên\':\ne.preventDefault();\ncurrentIndex = (currentIndex - 1 + items.length) % items.length;\nitems[currentIndex].focus();\nphá vỡ;\ntrường hợp \'Thoát\':\ncloseMenu();\nphá vỡ;\ntrường hợp \'Nhập\':\ntrường hợp \'\':\ne.preventDefault();\nitems[currentIndex].click();\ncloseMenu();\nphá vỡ;\ntrường hợp \'Tab\':\ncloseMenu();\nphá vỡ;\n}\n});\n\n// Đóng khi click ra ngoài\ndocument.addEventListener(\'click\', (e) => {\nif (!e.target.closest(\'.dropdown\')) closeMenu();\n});\n</script>',
    explanation: 'Điều này tuân theo mẫu thiết kế Nút Menu WAI-ARIA.Các tính năng trợ năng chính: 1) aria-haspopup="true" thông báo rằng nút này sẽ mở ra một menu.2) aria-expanded phản ánh trạng thái mở/đóng.3) nút liên kết điều khiển aria tới menu.4) role="menu" và role="menuitem" đưa ra ngữ nghĩa phù hợp.5) Phím mũi tên điều hướng giữa các mục (có gói).6) Escape đóng và trả tiêu điểm về nút kích hoạt — rất quan trọng đối với người dùng bàn phím cần "thoát ra".7) Enter/Space kích hoạt mục được tập trung.8) Tab đóng menu (hành vi dự kiến).9) Các mục có tabindex="-1" để chúng có thể được lấy tiêu điểm theo chương trình nhưng không theo thứ tự tab.10) Nhấp vào bên ngoài để đóng menu.Kiểm tra bằng NVDA hoặc VoiceOver để xác minh thông báo.',
  },
  'fp-038': {
    question: 'Thiết kế của bạn sử dụng màu sắc thương hiệu không đạt tỷ lệ tương phản WCAG AA.Nhà thiết kế nhấn mạnh vào việc giữ nguyên màu sắc chính xác của thương hiệu.Làm thế nào để bạn đáp ứng cả yêu cầu về khả năng tiếp cận và thiết kế?',
    answer: 'Sử dụng màu thương hiệu cho các thành phần lớn/mục đích trang trí và đảm bảo văn bản đáp ứng yêu cầu về độ tương phản bằng cách điều chỉnh nền, thêm đường viền hoặc sử dụng màu thương hiệu một cách có chọn lọc.',
    explanation: 'Các chiến lược duy trì thương hiệu trong khi đáp ứng WCAG AA (4,5:1 đối với văn bản thông thường, 3:1 đối với văn bản lớn): 1) Làm tối hoặc làm sáng màu thương hiệu một chút chỉ để sử dụng cho văn bản — thường điều chỉnh 10-15% là đủ và không thể nhận thấy bằng mắt thường.2) Sử dụng màu thương hiệu chính xác cho văn bản lớn (24px+/in đậm 18,66px+) chỉ cần tỷ lệ 3:1.3) Sử dụng màu thương hiệu trên nền tối hơn/sáng hơn để tăng độ tương phản.4) Đặt màu thương hiệu chính xác cho các thành phần trang trí, biểu tượng và đường viền — không phải nội dung văn bản.5) Thêm bóng hoặc đường viền văn bản tinh tế để tăng độ tương phản cảm nhận được.6) Tạo một "bảng màu có thể truy cập" để ánh xạ từng màu thương hiệu tới biến thể tuân thủ WCAG gần nhất của nó.Công cụ: Máy tính độ tương phản APCA (công cụ kế thừa cảm nhận cho độ tương phản WCAG 2), bộ chọn màu Chrome DevTools hiển thị tỷ lệ tương phản trong thời gian thực.Trình bày cho nhà thiết kế những so sánh song song - họ thường không thể phân biệt được sắc thái đã điều chỉnh.',
  },
  'fp-039': {
    question: 'SPA của bạn sử dụng định tuyến phía máy khách.Người dùng trình đọc màn hình không được thông báo khi trang thay đổi — sau khi bấm vào liên kết điều hướng, tiêu điểm vẫn ở trên liên kết và nội dung mới không được thông báo.Hãy sửa cái này.',
    answer: '// Trình xử lý thay đổi tuyến đường (hoạt động với mọi bộ định tuyến SPA)\nhàm onRouteChange(newPageTitle) {\n// 1. Cập nhật tiêu đề tài liệu\ndocument.title = newPageTitle + \' |Trang web của tôi\';\n\n// 2. Di chuyển tiêu điểm đến vùng nội dung chính\nconst main = document.getElementById(\'main-content\');\nmain.setAttribution(\'tabindex\', \'-1\');// làm cho có thể lấy nét\nmain.focus();\n\n// 3. Thông báo thay đổi trang qua khu vực trực tiếp\nconst phát thanh viên = document.getElementById(\'route-announcer\');\nphát thanh viên.textContent = \'\';// đặt lại để kích hoạt thông báo lại\nrequestAnimationFrame(() => {\nphát thanh viên.textContent = `Đã điều hướng đến ${newPageTitle}`;\n});\n}\n\n// Thêm vùng trực tiếp vô hình này vào HTML của bạn (một lần)\n// <div id="người phát thanh lộ trình"\n// vai trò="trạng thái"\n// aria-live="lịch sự"\n// aria-atomic="true"\n// style="position: tuyệt đối; chiều rộng: 1px; chiều cao: 1px;\n// tràn: ẩn;clip: trực tràng(0,0,0,0);\n// khoảng trắng: nowrap;">\n// </div>\n\n// Ví dụ về Bộ định tuyến phản ứng:\n// useEffect(() => {\n// onRouteChange(currentRoute.title);\n// }, [location.pathname]);',
    explanation: 'SPA phá vỡ mô hình điều hướng trang truyền thống mà trình đọc màn hình dựa vào.Trong trang web nhiều trang, tải trang mới sẽ kích hoạt trình đọc màn hình thông báo tiêu đề trang mới và di chuyển tiêu điểm lên đầu.Trong SPA, DOM biến đổi một cách âm thầm.Cần có ba bản sửa lỗi: 1) Cập nhật document.title — trình đọc màn hình thường thông báo điều này.2) Di chuyển tiêu điểm đến vùng nội dung chính để người dùng có thể bắt đầu đọc nội dung mới ngay lập tức.tabindex="-1" làm cho các phần tử không tương tác có thể lấy nét được.3) Sử dụng vùng aria-live="polite" để thông báo rõ ràng điều hướng — đây là phương pháp đáng tin cậy nhất trên tất cả các kết hợp trình đọc màn hình + trình duyệt.Thủ thuật đặt kép (xóa rồi đặt trong rAF) đảm bảo trình đọc màn hình phát hiện thay đổi ngay cả khi điều hướng đến trang có cùng tiêu đề.',
  },
  'fp-040': {
    question: 'Công ty của bạn nhận được khiếu nại pháp lý về khả năng tiếp cận.Bạn được giao nhiệm vụ tạo một kế hoạch khắc phục khả năng truy cập cho một ứng dụng lớn có hàng trăm trang.Bạn tiếp cận điều này như thế nào?',
    answer: 'Kiểm tra, ưu tiên theo tác động của người dùng và rủi ro pháp lý, khắc phục các vấn đề quan trọng trước tiên, triển khai thử nghiệm tự động để ngăn chặn sự hồi quy và đào tạo nhóm.',
    explanation: 'Giai đoạn 1 (Tuần 1-2) — Kiểm tra: a) Chạy quét tự động bằng axe-core/WAVE trên tất cả các trang để xác định các sự cố mà máy có thể phát hiện được (30-40% sự cố).b) Tiến hành kiểm tra thủ công bằng trình đọc màn hình (NVDA/VoiceOver) trên 20 trang được sử dụng nhiều nhất.c) Kiểm tra khả năng điều hướng chỉ bằng bàn phím trên các luồng người dùng quan trọng (đăng ký, thanh toán, nội dung chính).d) Thuê kiểm toán viên WCAG bên thứ ba để đánh giá chính thức.Giai đoạn 2 (Tuần 3) - Ưu tiên: Phân loại vấn đề theo mức độ nghiêm trọng: P0 (chặn hoàn toàn người dùng - thiếu nhãn biểu mẫu, bẫy bàn phím), P1 (ma sát lớn - không có văn bản thay thế, cấu trúc tiêu đề kém, thiếu ARIA), P2 (nhỏ - độ tương phản màu, thứ tự tiêu điểm).Trước tiên hãy sửa P0 trên các luồng quan trọng.Giai đoạn 3 (Tuần 4-8) - Khắc phục: Giao các vấn đề cho các công việc tồn đọng trong nước rút.Trước tiên, hãy sửa các thành phần được chia sẻ (tiêu đề, điều hướng, biểu mẫu) để có tác động tối đa.Giai đoạn 4 (Đang thực hiện) - Ngăn chặn hồi quy: Thêm axe-core vào đường dẫn CI/CD (eslint-plugin-jsx-a11y cho React, @axe-core/playwright cho E2E).Thêm thử nghiệm trình đọc màn hình vào danh sách kiểm tra QA.Giai đoạn 5 - Đào tạo: Đào tạo bắt buộc về khả năng tiếp cận cho tất cả các nhà phát triển và nhà thiết kế.Xuất bản một trang trợ năng với tuyên bố tuân thủ.',
  },
  'fp-041': {
    question: 'Việc gửi biểu mẫu sẽ gửi các giá trị trống mặc dù người dùng đã điền vào tất cả các trường.Vấn đề HTML có thể xảy ra nhất là gì?',
    answer: '1',
    explanation: 'Dữ liệu biểu mẫu HTML được gửi dưới dạng cặp khóa-giá trị trong đó khóa là thuộc tính tên.Nếu không có thuộc tính tên, đầu vào sẽ không có khóa và giá trị của chúng sẽ bị loại khỏi quá trình gửi biểu mẫu.Khắc phục: thêm name="username" và name="email" vào đầu vào.Tùy chọn C (thiếu liên kết nhãn) cũng là một vấn đề thực sự (khả năng truy cập) nhưng không khiến nội dung gửi trống.Trong khi bạn đang sửa lỗi này, hãy thêm: id trên đầu vào + cho trên nhãn (khả năng truy cập), thuộc tính bắt buộc (xác thực) và thuộc tính tự động hoàn thành (tự động điền của trình duyệt).Một bẫy phỏng vấn phổ biến: các nhà phát triển từng sử dụng quản lý trạng thái React đôi khi quên rằng các biểu mẫu HTML gốc hoàn toàn dựa vào thuộc tính name.',
  },
  'fp-042': {
    question: 'Xây dựng mẫu email HTML đáp ứng hoạt động trong Outlook, Gmail và Apple Mail.Email có hình ảnh tiêu đề, khu vực nội dung hai cột và nút CTA.',
    answer: '<!DOCTYPE html>\n<html lang="vi">\n<đầu>\n<bộ ký tự meta="utf-8" />\n<meta name="viewport" content="width=device-width, first-scale=1.0" />\n<title>Bản tin</title>\n<!--[if mso]>\n<phong cách>\nbảng { thu gọn đường viền: thu gọn;}\n.fallback-font { font-family: Arial, sans-serif;}\n</style>\n<![endif]-->\n</head>\n<body style="margin: 0; phần đệm: 0; màu nền: #f4f4f4; họ phông chữ: Arial, Helvetica, sans-serif;">\n<!-- Bảng bao bọc bên ngoài để căn giữa -->\n<table role="trình bày" width="100%" cellpadding="0" cellpacing="0" border="0">\n<tr>\n<tdalign="center" style="padding: 20px 10px;">\n<!-- Thùng chứa bên trong -->\n<table role="trình bày" width="600" cellpadding="0" cellpacing="0" border="0"\nstyle="max-width: 600px; chiều rộng: 100%; màu nền: #ffffff;">\n<!-- Hình ảnh tiêu đề -->\n<tr>\n<td style="padding: 0;">\n<img src="https://example.com/header.jpg" alt="Tiêu đề bản tin"\nwidth="600" style="display: block; chiều rộng tối đa: 100%; chiều cao: tự động;"/>\n</td>\n</tr>\n<!-- Nội dung hai cột -->\n<tr>\n<td style="padding: 20px;">\n<!--[if mso]><table role="trình bày" width="100%"><tr><td width="280" valign="top"><![endif]-->\n<div style="display: khối nội tuyến; chiều rộng: 100%; chiều rộng tối đa: 280px; căn chỉnh dọc: trên cùng;">\n<h2 style="margin: 0 0 10px; cỡ chữ: 20px; color: #333;">Tính năng Một</h2>\n<p style="margin: 0; cỡ chữ: 14px; chiều cao dòng: 1.6; màu: #666;">\nMô tả tính năng đầu tiên.\n</p>\n</div>\n<!--[if mso]></td><td width="20"></td><td width="280" valign="top"><![endif]-->\n<div style="display: khối nội tuyến; chiều rộng: 100%; chiều rộng tối đa: 280px; căn chỉnh dọc: trên cùng;">\n<h2 style="margin: 0 0 10px; cỡ chữ: 20px; màu: #333;">Tính năng thứ hai</h2>\n<p style="margin: 0; cỡ chữ: 14px; chiều cao dòng: 1.6; màu: #666;">\nMô tả tính năng thứ hai.\n</p>\n</div>\n<!--[if mso]></td></tr></table><![endif]-->\n</td>\n</tr>\n<!-- Nút CTA -->\n<tr>\n<tdalign="center" style="padding: 20px;">\n<a href="https://example.com" target="_blank"\nstyle="display: khối nội tuyến; phần đệm: 14px 32px; màu nền: #2563eb;\nmàu sắc: #ffffff;trang trí văn bản: không có;cỡ chữ: 16px;độ dày phông chữ: đậm;\nbán kính đường viền: 4px;">\nBắt đầu\n</a>\n</td>\n</tr>\n</bảng>\n</td>\n</tr>\n</bảng>\n</body>\n</html>',
    explanation: 'Email HTML bị kẹt trong quá khứ — bố cục dựa trên bảng là bắt buộc vì Outlook sử dụng Word làm công cụ kết xuất.Các quy tắc chính: 1) Sử dụng các bảng có vai trò="trình bày" để bố trí (không phải bảng dữ liệu).2) Nội tuyến tất cả CSS - hầu hết các ứng dụng email đều loại bỏ các thẻ <style> (Gmail loại bỏ chúng trong một số ngữ cảnh).3) Sử dụng nhận xét có điều kiện MSO (<!--[if mso]>) cho cấu trúc bảng dành riêng cho Outlook vì Outlook bỏ qua độ rộng tối đa, khối nội tuyến và nhiều thuộc tính CSS hiện đại.4) Hình ảnh cần hiển thị: chặn để ngăn khoảng cách ảo.Đặt chiều rộng trong thuộc tính HTML VÀ chiều rộng tối đa: 100% trong CSS để chia tỷ lệ đáp ứng.5) Luôn bao gồm màu văn bản - chế độ tối trong ứng dụng email có thể thay đổi hình nền.6) Kiểm tra bằng Litmus hoặc Email về Acid trên các máy khách.7) Chiều rộng tối đa 600px là tiêu chuẩn an toàn cho email.',
  },
  'fp-043': {
    question: 'Trang của bạn tải trong Safari chậm hơn đáng kể so với Chrome.Bạn phát hiện ra vấn đề liên quan đến cách tải tài nguyên.Sự kết hợp gợi ý tài nguyên nào mang lại hiệu suất trình duyệt chéo tốt nhất cho trang tải phông chữ từ Google Fonts và dữ liệu từ API của bạn?',
    answer: '1',
    explanation: 'Sự kết hợp đúng sử dụng gợi ý phù hợp cho từng loại tài nguyên: 1) kết nối trước cho phông chữ CDN — thiết lập sớm kết nối TCP + bắt tay TLS (tiết kiệm 100-300 mili giây).Sử dụng thuộc tính crossorigin cho các tệp phông chữ (yêu cầu CORS).2) dns-prefetch làm phương án dự phòng cho các trình duyệt không hỗ trợ kết nối trước (phiên bản Safari cũ hơn).Đặt dns-prefetch SAU KHI kết nối trước - trình duyệt sử dụng cái tốt nhất mà nó hỗ trợ.3) tải trước các CSS quan trọng phải chặn hiển thị (sử dụng có tác động mạnh nhất).Không tải trước mọi thứ — nó sẽ cạnh tranh băng thông và có thể ảnh hưởng đến hiệu suất.tìm nạp trước (tùy chọn C) dành cho tài nguyên trang tiếp theo, không phải trang hiện tại.Chỉ tìm nạp trước DNS (tùy chọn D) chỉ lưu tra cứu DNS (~ 20-120 mili giây), thiếu khoản tiết kiệm thiết lập kết nối lớn hơn.',
  },
  'fp-044': {
    question: 'Trang của bạn có phần video anh hùng tự động phát.Người dùng phàn nàn rằng nó lãng phí dữ liệu trên thiết bị di động và video không phát trên Safari của iOS.Sửa HTML để xử lý việc này đúng cách.',
    answer: '<!-- Video đáp ứng với dự phòng thích hợp -->\n<video\ntự động phát\ntắt tiếng\nvòng lặp\nplayinline\ntải trước="siêu dữ liệu"\nposter="hero-poster.jpg"\nclass="anh hùng-video"\n>\n<!-- Phục vụ tệp nhỏ hơn trên thiết bị di động thông qua thuộc tính media -->\n<nguồn\nsrc="hero-mobile.mp4"\ngõ="video/mp4"\nmedia="(độ rộng tối đa: 768px)"\n/>\n<source src="hero-desktop.webm" type="video/webm" />\n<source src="hero-desktop.mp4" type="video/mp4" />\n<!-- Dự phòng do không hỗ trợ video -->\n<img src="hero-poster.jpg" alt="Biểu ngữ anh hùng" />\n</video>\n\n<kịch bản>\n// Tôn trọng việc tiết kiệm dữ liệu và kết nối chậm\nnếu (\nnavigator.connection &&\n(navigator.connection.saveData ||\nnavigator.connection.effectType === \'2g\' ||\nnavigator.connection.effectType === \'slow-2g\')\n) {\nconst video = document.querySelector(\'.hero-video\');\nvideo.removeAttribution(\'autoplay\');\nvideo.preload = \'không\';\n// Thay vào đó hãy hiển thị hình ảnh poster\n}\n</script>',
    explanation: 'Các thuộc tính chính: 1) tắt tiếng là BẮT BUỘC để tự động phát hoạt động - tất cả các trình duyệt đều chặn tự động phát có âm thanh.2) playinline ngăn iOS Safari buộc phát lại toàn màn hình.Không có nó, iOS sẽ bỏ qua hoàn toàn tính năng tự động phát.3) áp phích cung cấp hình ảnh ngay lập tức trong khi video đệm.4) preload="metadata" chỉ tải đủ để nhận thời lượng/kích thước chứ không phải toàn bộ tệp.5) Nhiều phần tử <source> có loại cung cấp đàm phán định dạng - trình duyệt chọn phần tử đầu tiên mà nó hỗ trợ.WebM thường nhỏ hơn MP4.6) Thuộc tính media trên <source> phục vụ phiên bản di động nhỏ hơn.7) JavaScript kiểm tra API thông tin mạng để tắt tính năng tự động phát trên các kết nối chậm hoặc chế độ tiết kiệm dữ liệu.8) <img> dự phòng bên trong <video> cho các trình duyệt cổ.Luôn cân nhắc: video tự động phát có băng thông từ 3-10MB — hãy sử dụng nó một cách thận trọng.',
  },
  'fp-045': {
    question: 'Trang web của bạn bị kiểm tra SEO kém mặc dù có nội dung tốt.Báo cáo cho biết cấu trúc ngữ nghĩa yếu, thiếu siêu dữ liệu và khả năng thu thập dữ liệu kém.Làm cách nào để khắc phục nền tảng HTML cho SEO?',
    answer: 'Triển khai các mốc HTML ngữ nghĩa thích hợp, dữ liệu có cấu trúc (JSON-LD), thẻ meta toàn diện, URL chuẩn và phân cấp URL/tiêu đề rõ ràng.',
    explanation: 'Sửa lỗi SEO HTML toàn diện: 1) Cấu trúc ngữ nghĩa: Sử dụng chính xác một <h1> trên mỗi trang, phân cấp logic h2-h6, các mốc <main>, <nav>, <article>, <section>, <aside>.Công cụ tìm kiếm sử dụng những điều này để hiểu cấu trúc nội dung.2) Thẻ meta: <title> duy nhất (50-60 ký tự) và <meta name="description"> (150-160 ký tự) trên mỗi trang.Thêm <meta name="robots" content="index, follow">.3) Dữ liệu có cấu trúc: Thêm đánh dấu lược đồ JSON-LD (Tổ chức, Bài viết, Sản phẩm, BreadcrumbList, Câu hỏi thường gặp) — bật đoạn mã chi tiết trong kết quả tìm kiếm.4) URL Canonical: <link rel="canonical"> trên mỗi trang để tránh vấn đề trùng lặp nội dung.5) Mở thẻ meta Graph + Twitter Card để chia sẻ trên mạng xã hội.6) Phân cấp tiêu đề rõ ràng - không bỏ qua cấp độ (h1 -> h3 là xấu).7) Văn bản thay thế hình ảnh trên mỗi hình ảnh.8) Liên kết nội bộ với văn bản liên kết mô tả (không phải “bấm vào đây”).9) Sơ đồ trang web XML + robot.txt.10) Đối với SPA: triển khai SSR/SSG để trình thu thập thông tin thấy HTML được hiển thị chứ không phải <div id="root"> trống.Xác thực bằng Google Search Console và Kiểm tra kết quả nhiều định dạng.',
  },
}
