import type { QuestionTranslationMap } from '../types'

export const reactPracticalVi: QuestionTranslationMap = {

  'rp-001': {
    question: 'Ứng dụng React của bạn hiển thị danh sách 10.000 mục và trang bị chậm đáng kể khi cuộn.Đi qua cách tiếp cận của bạn để khắc phục điều này.',
    answer: 'Sử dụng ảo hóa danh sách (cửa sổ) để chỉ hiển thị các mục hiển thị.Các thư viện như cửa sổ phản ứng hoặc @tanstack/virtual chỉ hiển thị các mục trong khung nhìn cộng với một bộ đệm quét quá mức nhỏ.Các bước: (1) Đo chiều cao thùng chứa và chiều cao vật phẩm.(2) Thay thế bản đồ đơn giản() bằng thành phần danh sách ảo hóa.(3) Giữ nguyên các thành phần vật phẩm bằng React.memo để tránh hiển thị lại các vật phẩm hiển thị.(4) Nếu các mục có chiều cao thay đổi, hãy sử dụng VariableSizeList hoặc đo động.(5) Cân nhắc thêm tính năng phân trang hoặc cuộn vô hạn làm mẫu UX bổ sung.',
    explanation: 'Việc hiển thị các nút DOM 10k rất tốn kém bất kể React.Ảo hóa giảm số lượng nút DOM xuống còn ~20-50 mục hiển thị.Reac-window rất nhẹ (~6KB), trong khi Reac-virtuoso xử lý các độ cao động ngay lập tức.Luôn lập cấu hình bằng React DevTools Profiler và tab Chrome Performance để xác nhận điểm nghẽn là số lượng DOM so với các kết xuất đắt tiền.',
  },
  'rp-002': {
    question: 'React DevTools Profiler hiển thị một thành phần mất 200 mili giây để hiển thị.Xem qua các bước tối ưu hóa của bạn từ chẩn đoán đến khắc phục.',
    answer: 'Bước 1: Mở React DevTools Profiler, ghi lại tương tác, xác định thành phần chậm trong biểu đồ ngọn lửa.Bước 2: Kiểm tra "Tại sao điều này lại hiển thị?"— tìm kiếm những thay đổi prop không cần thiết, thay đổi ngữ cảnh hoặc kết xuất lại gốc.Bước 3: Kiểm tra mã thành phần để tìm các phép tính tốn kém (thao tác mảng lớn, biến đổi đối tượng sâu).Bước 4: Áp dụng các bản sửa lỗi theo thứ tự tác động: (a) Ghi nhớ các tính toán tốn kém bằng useMemo, (b) Bao bọc thành phần trong React.memo bằng một bộ so sánh tùy chỉnh nếu đạo cụ ổn định, (c) Di chuyển công việc tốn kém ra ngoài đường dẫn kết xuất (Web Worker, phía máy chủ), (d) Tách thành phần để chỉ phần động hiển thị lại, (e) Sử dụng useTransition cho các cập nhật không khẩn cấp.Bước 5: Lập lại hồ sơ để xác nhận sự cải thiện.',
    explanation: 'Kết xuất 200 mili giây sẽ chặn luồng chính và gây ra hiện tượng giật (ngân sách 60 khung hình/giây là ~16 mili giây).Hồ sơ có hệ thống ngăn ngừa tối ưu hóa sớm.Các nguyên nhân phổ biến nhất là: tạo lại các đối tượng/mảng trong đạo cụ, tính toán dữ liệu dẫn xuất trên mỗi lần kết xuất và hiển thị các cây con lớn không thay đổi.',
  },
  'rp-003': {
    question: 'Một thành phần hiển thị lại 50 lần khi trạng thái gốc thay đổi một lần.Bạn mở React DevTools và thấy thành phần này lần nào cũng nhận được cùng một đạo cụ.Nguyên nhân có thể xảy ra nhất là gì?',
    answer: '0',
    explanation: 'Các hàm mũi tên nội tuyến như `onClick={() => doSomething(id)}` tạo một tham chiếu hàm mới trên mỗi kết xuất gốc.Ngay cả khi hành vi giống hệt nhau, so sánh nông cạn của React.memo sẽ thấy một tham chiếu khác và hiển thị lại đứa trẻ.Khắc phục: bọc trình xử lý bằng useCallback trong phần tử mẹ hoặc cơ cấu lại để phần tử con nhận được đạo cụ ổn định.Lưu ý: 50 lần hiển thị lại cho thấy bản thân phần gốc có thể đang hiển thị lại quá mức - hãy điều tra ngược dòng.',
  },
  'rp-004': {
    question: 'Bạn hiển thị danh sách các mục bằng cách sử dụng `.map()` nhưng quên thêm prop `key`.Người dùng báo cáo các mục hiển thị dữ liệu cũ sau khi sắp xếp danh sách.Tại sao điều này xảy ra?',
    answer: '1',
    explanation: 'Nếu không có khóa rõ ràng, React sẽ quay trở lại các chỉ mục mảng.Khi danh sách được sắp xếp lại, chỉ mục 0 vẫn ánh xạ tới nút DOM đầu tiên, vì vậy React cố gắng vá các nút hiện có bằng dữ liệu mới thay vì di chuyển chúng.Điều này khiến các giá trị đầu vào, tiêu điểm và trạng thái bên trong dính vào mục sai.Cách khắc phục: sử dụng mã định danh duy nhất, ổn định (ví dụ: item.id) làm khóa.',
  },
  'rp-005': {
    question: 'Người dùng sản xuất báo cáo màn hình trắng trên ứng dụng React của bạn.Không có lỗi nào xuất hiện trong bảng thông tin giám sát của bạn.Làm thế nào để bạn ngăn chặn và xử lý điều này?',
    answer: 'Triển khai Ranh giới Lỗi tại các điểm chiến lược trong cây thành phần.(1) Tạo ErrorBoundary cấp cao nhất bao bọc toàn bộ ứng dụng hiển thị giao diện người dùng dự phòng bằng nút "Tải lại".(2) Thêm các ranh giới lỗi chi tiết xung quanh các tính năng độc lập (thanh bên, nội dung chính, tiện ích) để sự cố ở một tính năng không làm chết toàn bộ trang.(3) Tích hợp tính năng báo lỗi (Sentry, DataDog) bên trong thành phầnDidCatch để nắm bắt lỗi + ngăn xếp thành phần.(4) Đối với các lỗi không đồng bộ (không bị giới hạn), hãy thêm các trình nghe window.onerror và window.onunhandledrejection.(5) Sử dụng errorElement của React Router để xử lý lỗi ở cấp độ tuyến đường.(6) Thêm cơ chế kiểm tra tình trạng để phát hiện các vòng lặp sự cố vô hạn và cung cấp tùy chọn xóa bộ nhớ đệm.',
    explanation: 'Ranh giới lỗi (các thành phần lớp có getDerivedStateFromError/ComponentDidCatch) phát hiện các lỗi thời gian hiển thị trong cây con của chúng.Họ KHÔNG bắt lỗi trong trình xử lý sự kiện, mã không đồng bộ hoặc SSR.Màn hình trắng thường có nghĩa là lỗi hiển thị chưa được xử lý được truyền đến thư mục gốc và ngắt kết nối toàn bộ cây.',
  },
  'rp-006': {
    question: 'Một nhà phát triển cấp dưới viết `<button onClick={handleSubmit()}>Gửi</button>` và báo cáo rằng biểu mẫu sẽ gửi ngay lập tức khi tải trang thay vì khi nhấp chuột.Có chuyện gì vậy?',
    answer: '1',
    explanation: '`handleSubmit()` với dấu ngoặc đơn gọi hàm trong khi kết xuất và chuyển giá trị trả về của nó cho onClick.Cách khắc phục là chuyển tham chiếu hàm: `onClick={handleSubmit}`.Nếu bạn cần truyền đối số, hãy sử dụng hàm mũi tên: `onClick={() => handSubmit(id)}`.',
  },
  'rp-007': {
    question: 'Thành phần này sẽ chuyển đổi một lớp khi nhấp chuột, nhưng việc nhấp chuột không thực hiện trực quan ngay cả khi trạng thái cập nhật.Tìm lỗi.',
    answer: '1',
    explanation: 'Trong JSX, thuộc tính `class` HTML phải được viết là `className`.Việc sử dụng `class` sẽ không gây ra lỗi trong mọi trường hợp, nhưng nó sẽ không áp dụng lớp CSS một cách chính xác.React sẽ hiển thị cảnh báo trong quá trình phát triển: "Thuộc tính DOM không hợp lệ `class`. Ý bạn là `className`?"',
  },
  'rp-008': {
    question: 'Điều gì sẽ xuất hiện trong bảng điều khiển khi nhấp vào nút?',
    answer: '2',
    explanation: 'Các cập nhật trạng thái được chia theo đợt và `count` được ghi lại bằng cách đóng ở giá trị hiện tại của nó (0).Tất cả ba lệnh gọi `setCount(count + 1)` đều tương đương với `setCount(0 + 1)` — lệnh cuối cùng thắng, do đó màn hình hiển thị 1. `console.log(count)` vẫn in giá trị đóng cũ 0. Để tăng ba lần, hãy sử dụng biểu mẫu cập nhật: `setCount(prev => prev + 1)`.',
  },
  'rp-009': {
    question: 'Nhóm của bạn muốn áp dụng Thành phần máy chủ React (RSC) trong SPA do khách hàng kết xuất hiện có.Chiến lược di chuyển của bạn là gì?',
    answer: 'Giai đoạn 1: Áp dụng khung hỗ trợ RSC (Bộ định tuyến ứng dụng Next.js).Thiết lập thư mục ứng dụng mới cùng với các trang hiện có.Giai đoạn 2: Xác định các thành phần lá chỉ hiển thị dữ liệu và không có tính tương tác - đây là những ứng cử viên lý tưởng đầu tiên cho Thành phần Máy chủ.Chuyển chúng sang RSC (không có lệnh "sử dụng ứng dụng khách").Giai đoạn 3: Thiết lập mẫu ranh giới rõ ràng - Thành phần máy chủ tìm nạp dữ liệu và chuyển dữ liệu đó dưới dạng đạo cụ cho Thành phần máy khách.Chỉ thêm "sử dụng ứng dụng khách" khi cần tương tác.Giai đoạn 4: Di chuyển việc tìm nạp dữ liệu từ useEffect/React Query sang tìm nạp dữ liệu ở cấp máy chủ trong RSC.Giai đoạn 5: Giới thiệu tính năng phát trực tuyến có ranh giới Hồi hộp để cải thiện hiệu suất được cảm nhận.Giai đoạn 6: Kích thước gói kiểm tra - RSC sẽ giảm đáng kể JS của máy khách do mã chỉ dành cho máy chủ (bao gồm cả các phần phụ thuộc lớn) không bao giờ được gửi tới trình duyệt.',
    explanation: 'RSC không phải là sự thay thế tự động;nó yêu cầu một khung (Next.js, Waku).Sự thay đổi tư duy quan trọng: theo mặc định, các thành phần được ưu tiên máy chủ.Chỉ thêm "sử dụng ứng dụng khách" khi bạn cần hook, trình xử lý sự kiện hoặc API trình duyệt.Những cạm bẫy phổ biến bao gồm cố gắng sử dụng hook trong Thành phần máy chủ, nhập các thư viện chỉ dành cho máy khách trong mã máy chủ và sử dụng quá mức "sử dụng máy khách" làm mất đi các lợi ích.',
  },
  'rp-010': {
    question: 'Bạn kết xuất một thành phần có điều kiện với `{isLoggedIn && <Dashboard />}`.Người kiểm tra báo cáo nhìn thấy "0" trên màn hình khi người dùng chưa đăng nhập. Đã xảy ra lỗi gì?',
    answer: '1',
    explanation: '`&&` của JavaScript trả về toán hạng bên trái nếu sai.Nếu `isLoggedIn` là `0` (không phải `false`, `null` hoặc `unknown`), React sẽ hiển thị nó dưới dạng chuỗi "0".Cách khắc phục: ép buộc thành boolean bằng `!!isLoggedIn`, `Boolean(isLoggedIn)` hoặc sử dụng `isLoggedIn ternary ?<Bảng điều khiển /> : null`.',
  },
  'rp-011': {
    question: 'Bạn cần xây dựng một thư viện thành phần sẽ được chia sẻ giữa 5 nhóm sản phẩm khác nhau.Bạn cấu trúc nó trong React như thế nào?',
    answer: 'Tạo một gói chuyên dụng (khuyên dùng monorepo) với: (1) Kiến trúc thành phần: thiết kế nguyên tử (các nguyên tử như Nút, các phân tử như SearchBar, các sinh vật như DataTable).(2) Mỗi ​​thành phần có thư mục riêng với index.tsx, ComponentName.tsx, ComponentName.test.tsx, ComponentName.stories.tsx.(3) Xuất qua các tệp thùng với các bản xuất có tên có thể rung được trên cây.(4) Tạo kiểu: sử dụng CSS Modules hoặc giải pháp CSS-in-JS hỗ trợ SSR;hiển thị mã thông báo thiết kế dưới dạng thuộc tính tùy chỉnh CSS.(5) Loại an toàn: xuất tất cả các giao diện chống đỡ.(6) Tài liệu: Sách truyện để kiểm tra trực quan và tài liệu.(7) Lập phiên bản: lập phiên bản ngữ nghĩa với các tập hợp thay đổi.(8) Bản dựng: biên dịch sang ESM + CJS bằng tsup hoặc Rollup;bảo tồn cấu trúc mô-đun để rung cây.(9) Kiểm tra: kiểm tra đơn vị với Thư viện kiểm tra, hồi quy trực quan với Chromatic.',
    explanation: 'Thư viện thành phần dùng chung không thành công khi chúng được liên kết chặt chẽ với một ứng dụng, được ghi chép kém hoặc khó cập nhật.Các yếu tố thành công chính là: hợp đồng API nghiêm ngặt thông qua TypeScript, tài liệu trực quan qua Storybook và phát hành tự động thông qua CI/CD với các bộ thay đổi.',
  },
  'rp-012': {
    question: 'Thành phần này sẽ cập nhật tên hiển thị khi đầu vào thay đổi, nhưng việc nhập đầu vào không có tác dụng gì.Tìm lỗi.',
    answer: '1',
    explanation: 'React chỉ hiển thị lại khi trạng thái (useState/useReducer) hoặc props thay đổi.Một biến `let` đơn giản được tạo lại trong mỗi lần kết xuất và các đột biến đối với biến đó sẽ bị mất.Sửa: `const [name, setName] = useState(\'Alice\')` và `setName(e.target.value)` trong trình xử lý.',
  },
  'rp-013': {
    question: 'Bạn cần di chuyển một thành phần lớp lớn với thành phầnDidMount, thành phầnDidUpdate, thành phầnWillUnmount và getDerivedStateFromProps sang các hook chức năng.Đi qua quá trình này.',
    answer: 'Bước 1: Ánh xạ các phương thức vòng đời tới các hook: thành phầnDidMount → useEffect(..., []), thành phầnDidUpdate → useEffect(..., [deps]), thành phầnWillUnmount → hàm dọn dẹp useEffect, getDerivedStateFromProps → tính toán các giá trị dẫn xuất trong quá trình kết xuất hoặc useMemo.Bước 2: Chuyển đổi this.state thành các lệnh gọi useState riêng lẻ (được chia theo mối quan tâm, không phải một đối tượng lớn).Bước 3: Thay thế lệnh gọi lại this.setState bằng useEffect tùy thuộc vào trạng thái được cập nhật.Bước 4: Thay thế các phương thức phiên bản bằng các hàm thông thường hoặc useCallback.Bước 5: Thay thế this.refs bằng useRef.Bước 6: Nếu thành phần sử dụng ngữ cảnh, hãy thay thế bối cảnh tĩnh bằng useContext.Bước 7: Trích xuất logic liên quan vào các móc tùy chỉnh (ví dụ: useSubscription cho mẫu đăng ký/hủy đăng ký).Bước 8: Kiểm tra tính tương đương của hành vi - các hook có sự khác biệt nhỏ về thời gian (các hiệu ứng chạy sau khi vẽ, không đồng bộ như thành phầnDidMount).',
    explanation: 'Cạm bẫy lớn nhất là cố gắng dịch 1:1.Móc khuyến khích phân chia theo mối quan tâm (tất cả logic đăng ký cùng nhau) thay vì theo giai đoạn vòng đời.getDerivedStateFromProps thường chỉ ra vấn đề về thiết kế - trạng thái dẫn xuất thường có thể được tính toán trong quá trình kết xuất mà không có trạng thái nào cả.',
  },
  'rp-014': {
    question: 'Ứng dụng của bạn sử dụng React.lazy() cho các tuyến phân tách mã.Người dùng có kết nối chậm sẽ nhìn thấy màn hình trống trong vài giây khi tải các đoạn.Bạn nên thêm gì?',
    answer: '1',
    explanation: 'React.lazy yêu cầu ranh giới Hồi hộp.Trong khi đoạn lười đang tải, Suspense hiển thị phần chống đỡ `dự phòng` (ví dụ: một con quay hoặc bộ xương).Nếu không có sự hồi hộp, React sẽ đưa ra lỗi.Để có trải nghiệm người dùng tốt hơn: (1) hiển thị các màn hình khung phù hợp với bố cục, (2) tìm nạp trước các đoạn khi di chuột/tiêu điểm của các liên kết điều hướng, (3) sử dụng `startTransition` để giữ cho giao diện người dùng cũ hiển thị trong khi giao diện người dùng mới tải.',
  },
  'rp-015': {
    question: 'Bạn đang kiến ​​trúc một hệ thống giao diện người dùng vi mô trong đó 4 nhóm độc lập xây dựng và triển khai các ứng dụng React được gộp thành một hệ vỏ.Bạn áp dụng cách tiếp cận nào?',
    answer: 'Tùy chọn A (được khuyến nghị): Liên kết mô-đun (plugin Webpack 5 / Vite).Mỗi nhóm xây dựng một mô-đun từ xa để xuất các thành phần React.Ứng dụng shell sử dụng chúng khi chạy.Các phần phụ thuộc được chia sẻ (React, React DOM) được định cấu hình dưới dạng đơn lẻ để tránh xung đột phiên bản.Tùy chọn B: cách ly dựa trên iframe cho các nhóm cũ, với giao tiếp postMessage.Tùy chọn C: Thành phần web làm ranh giới tích hợp - mỗi nhóm gói ứng dụng React của họ trong một thành phần tùy chỉnh.Các quyết định chính: (1) Định tuyến: shell sở hữu bộ định tuyến;micro-frontend đăng ký tuyến đường của họ.(2) Trạng thái chia sẻ: sử dụng các sự kiện tùy chỉnh hoặc xe buýt sự kiện nhẹ;tránh các cửa hàng toàn cầu được chia sẻ.(3) Cách ly kiểu dáng: CSS Modules hoặc Shadow DOM để tránh rò rỉ.(4) Triển khai: mỗi nhóm triển khai độc lập theo lộ trình CDN của riêng mình.(5) Phiên bản: thử nghiệm hợp đồng giữa shell và điều khiển từ xa.(6) Cách ly lỗi: Ranh giới lỗi trên mỗi giao diện người dùng vi mô.',
    explanation: 'Sự độc lập phát triển thương mại của các mặt trận vi mô đối với sự phức tạp của hội nhập.Liên kết mô-đun là cách tiếp cận thân thiện với React nhất.Rủi ro chính: trôi dạt phiên bản phụ thuộc được chia sẻ, xung đột CSS và chi phí hiệu suất do tải nhiều gói.Chỉ áp dụng nếu các yêu cầu về quyền tự chủ của nhóm biện minh cho sự phức tạp.',
  },
  'rp-016': {
    question: 'Lệnh gọi API trong useEffect tạo ra một điều kiện tương tranh khi người dùng điều hướng nhanh giữa các trang.Viết giải pháp bằng AbortController.',
    answer: 'hàm UserProfile({ userId }: { userId: string }) {\nconst [người dùng, setUser] = useState<User |null>(null);\nconst [lỗi, setError] = useState<string |null>(null);\nconst [đang tải, setLoading] = useState(true);\n\nuseEffect(() => {\nbộ điều khiển const = AbortController mới();\n\nhàm không đồng bộ tìm nạpUser() {\nsetLoading(true);\nsetError(null);\nthử {\nconst res = đang chờ tìm nạp(`/api/users/${userId}`, {\ntín hiệu: bộ điều khiển.signal,\n});\nif (!res.ok) ném Lỗi mới(\'Không thể tìm nạp\');\ndữ liệu const = đang chờ res.json();\nsetUser(dữ liệu);\n} bắt (lỗi) {\nif (err instanceof DOMException && err.name === \'AbortError\') {\ntrở lại;// Bỏ qua các yêu cầu bị hủy\n}\nsetError(err instanceof Error ? err.message : \'Lỗi không xác định\');\n} cuối cùng {\nif (!controller.signal.aborted) {\nsetLoading(false);\n}\n}\n}\n\ntìm nạpNgười dùng();\n\nreturn () => control.abort();\n}, [userId]);\n\nif (đang tải) trả về <Spinner />;\nif (lỗi) trả về <ErrorMessage message={error} />;\nreturn <UserCard user={user} />;\n}',
    explanation: 'Nếu không có AbortController, điều hướng nhanh sẽ kích hoạt nhiều lần tìm nạp.Các phản hồi trước đó (cũ) có thể được giải quyết sau các phản hồi mới hơn, ghi đè dữ liệu chính xác bằng dữ liệu lỗi thời.Chức năng dọn dẹp sẽ hủy bỏ yêu cầu đang thực hiện khi userId thay đổi hoặc thành phần bị ngắt kết nối.Luôn kiểm tra AbortError để tránh đặt trạng thái lỗi cho việc hủy có chủ ý.',
  },
  'rp-017': {
    question: 'useEffect của bạn kích hoạt hai lần trong quá trình phát triển.Một nhà phát triển cấp dưới muốn xóa StrictMode để "sửa" lỗi này.Bạn nói gì với họ?',
    answer: '1',
    explanation: 'React 18+ StrictMode trong quá trình gắn kết, ngắt kết nối, sau đó gắn lại các thành phần để xác minh rằng các hiệu ứng được dọn dẹp đúng cách.Nếu việc kích hoạt hai lần gây ra sự cố (ví dụ: lệnh gọi API trùng lặp, đăng ký trùng lặp), thì điều đó sẽ phát hiện ra lỗi thực sự: chức năng dọn dẹp bị thiếu hoặc không chính xác.Trong quá trình sản xuất, các hiệu ứng chạy một lần.Khắc phục nguyên nhân gốc rễ (thêm cách dọn dẹp thích hợp), không phải triệu chứng.',
  },
  'rp-018': {
    question: 'Người dùng báo cáo trang bị treo khi nhập vào hộp tìm kiếm lọc một tập dữ liệu lớn (50.000 mục).Viết giải pháp bằng cách sử dụng useDeferredValue.',
    answer: 'function SearchableList({ items }: { items: Item[] }) {\nconst [truy vấn, setQuery] = useState(\'\');\nconst deferredQuery = useDeferredValue(truy vấn);\nconst isStale = truy vấn !== deferredQuery;\n\nconst filterItems = useMemo(\n() =>\nitems.filter((item) =>\nitem.name.toLowerCase().includes(deferredQuery.toLowerCase())\n),\n[các mục, deferredQuery]\n);\n\ntrở lại (\n<div>\n<đầu vào\ngiá trị={truy vấn}\nonChange={(e) => setQuery(e.target.value)}\nplaceholder="Tìm kiếm..."\n/>\n<div style={{ độ mờ: isStale ?0,6 : 1, chuyển tiếp: \'độ mờ 0,2s\' }}>\n<VirtualizedList items={filteredItems} />\n</div>\n</div>\n);\n}',
    explanation: 'useDeferredValue cho phép React giữ đầu vào phản hồi nhanh bằng cách trì hoãn quá trình lọc đắt tiền.Đầu vào cập nhật ngay lập tức với giá trị đã nhập, trong khi cập nhật danh sách được hoãn lại ở mức ưu tiên thấp hơn.Kết hợp với useMemo để tránh phải tính toán lại trên mỗi kết xuất và ảo hóa cho chính danh sách, điều này mang lại trải nghiệm người dùng mượt mà.Kiểm tra isStale thêm gợi ý trực quan cho biết kết quả đang tải.',
  },
  'rp-019': {
    question: 'Xây dựng một hook useDebounce tùy chỉnh và sử dụng nó để gỡ bỏ đầu vào tìm kiếm gọi API.',
    answer: 'hàm useDebounce<T>(giá trị: T, độ trễ: số): T {\nconst [debouncedValue, setDebouncedValue] = useState(value);\n\nuseEffect(() => {\nconst clock = setTimeout(() => setDebouncedValue(value), delay);\nreturn () => clearTimeout(timer);\n}, [giá trị, độ trễ]);\n\ntrả lại giá trị bị trả lại;\n}\n\n// Cách sử dụng\nhàm SearchInput() {\nconst [truy vấn, setQuery] = useState(\'\');\nconst debouncedQuery = useDebounce(query, 300);\nconst [kết quả, setResults] = useState([]);\n\nuseEffect(() => {\nif (!debouncedQuery.trim()) {\nsetResults([]);\ntrở lại;\n}\nbộ điều khiển const = AbortController mới();\n\ntìm nạp(`/api/search?q=${encodeURIComponent(debouncedQuery)}`, {\ntín hiệu: bộ điều khiển.signal,\n})\n.then((res) => res.json())\n.then(setResults)\n.catch((err) => {\nif (err.name !== \'AbortError\') console.error(err);\n});\n\nreturn () => control.abort();\n}, [debouncedQuery]);\n\ntrở lại (\n<div>\n<input value={query} onChange={(e) => setQuery(e.target.value)} />\n<ul>{results.map((r) => <li key={r.id}>{r.name</li>)</ul>\n</div>\n);\n}',
    explanation: 'Hook useDebounce trì hoãn việc cập nhật giá trị được gỡ lỗi cho đến khi đầu vào ngừng thay đổi đối với độ trễ đã chỉ định.Mỗi lần nhấn phím sẽ đặt lại bộ hẹn giờ thông qua chức năng dọn dẹp.Hiệu ứng tìm kiếm chỉ kích hoạt khi debouncedQuery thay đổi, giảm lệnh gọi API từ mỗi lần nhấn phím xuống còn một lệnh gọi mỗi lần tạm dừng.Kết hợp với AbortController để đảm bảo an toàn cho điều kiện cuộc đua.',
  },
  'rp-020': {
    question: 'Thành phần này sẽ tìm nạp dữ liệu một lần khi gắn kết, nhưng nó tạo ra vòng lặp vô hạn các lệnh gọi API.Tìm lỗi.',
    answer: '1',
    explanation: 'Không có mảng phụ thuộc, useEffect sẽ chạy sau mỗi lần kết xuất.Quá trình tìm nạp thành công → trạng thái cập nhật setUsers → hiển thị lại thành phần → useEffect chạy lại → vòng lặp vô hạn.Việc thêm `[]` làm đối số thứ hai sẽ khiến nó chỉ chạy trên mount.Đây là một trong những lỗi React hook phổ biến nhất.',
  },
  'rp-021': {
    question: 'Triển khai hook useLocalStorage đồng bộ hóa trạng thái với localStorage và hoạt động trên các tab trình duyệt.',
    answer: 'hàm useLocalStorage<T>(key: string, initValue: T) {\nconst [storedValue, setStoredValue] = useState<T>(() => {\nthử {\nconst item = window.localStorage.getItem(key);\ntrả lại hàng?(JSON.parse(item) as T): giá trị ban đầu;\n} bắt {\ntrả về giá trị ban đầu;\n}\n});\n\nconst setValue = useCallback(\n(giá trị: T | ((trước: T) => T)) => {\nsetStoredValue((trước) => {\nconst nextValue = giá trị instanceof Hàm?value(prev): giá trị;\nthử {\nwindow.localStorage.setItem(key, JSON.stringify(nextValue));\n// Thông báo cho các thành phần khác trong cùng tab\nwindow.dispatchEvent(\nStorageEvent mới(\'storage\', { key, newValue: JSON.stringify(nextValue) })\n);\n} bắt (lỗi) {\nconsole.warn(\'localStorage ghi không thành công:\', err);\n}\ntrả về giá trị tiếp theo;\n});\n},\n[chìa khóa]\n);\n\nuseEffect(() => {\nhàm xử lýStorageChange(e: StorageEvent) {\nif (e.key === key && e.newValue !== null) {\nthử {\nsetStoredValue(JSON.parse(e.newValue) as T);\n} bắt {\n// Bỏ qua lỗi phân tích cú pháp\n}\n}\n}\nwindow.addEventListener(\'storage\', handStorageChange);\nreturn () => window.removeEventListener(\'storage\', handStorageChange);\n}, [khóa]);\n\ntrả về [storedValue, setValue] dưới dạng const;\n}',
    explanation: 'Móc khởi tạo từ localStorage bằng cách sử dụng trình khởi tạo lười biếng (hàm trong useState) để tránh đọc trên mỗi lần kết xuất.Trình bao bọc setValue ghi vào cả state và localStorage.Trình xử lý sự kiện lưu trữ đồng bộ hóa trên các tab — trình duyệt kích hoạt các sự kiện "lưu trữ" khi một tab khác ghi vào localStorage.Chúng tôi gửi một StorageEvent theo cách thủ công để đồng bộ hóa cùng một tab.',
  },
  'rp-022': {
    question: 'Triển khai cập nhật giao diện người dùng lạc quan cho nút "thích" hiển thị số lượng cập nhật ngay lập tức và hoàn nguyên khi API bị lỗi.',
    answer: 'hàm LikeButton({ postId, initCount }: { postId: string; initCount: number }) {\nconst [đếm, setCount] = useState(initialCount);\nconst [isLiked, setIsLiked] = useState(false);\nconst [isPending, setIsPending] = useState(false);\n\nhàm không đồng bộ handLike() {\nnếu (đang chờ xử lý) trả về;\n\nconst prevCount = đếm;\nconst prevLiked = isLiked;\n\n// Cập nhật lạc quan\nsetCount((c) => (isLiked ? c - 1 : c + 1));\nsetIsLiked((đã thích) => !đã thích);\nsetIsPending(true);\n\nthử {\nconst res = đang chờ tìm nạp(`/api/posts/${postId}/like`, {\nphương pháp: isLiked ?\'XÓA\' : \'ĐĂNG\',\n});\nif (!res.ok) ném Lỗi mới(\'API không thành công\');\n// Tùy chọn đồng bộ với số lượng máy chủ:\n// const data = đang chờ res.json();\n// setCount(data.likeCount);\n} bắt {\n// Hoàn nguyên khi thất bại\nsetCount(prevCount);\nsetIsLiked(prevLiked);\ntoast.error(\'Không thể cập nhật lượt thích. Vui lòng thử lại.\');\n} cuối cùng {\nsetIsPending(false);\n}\n}\n\ntrở lại (\n<button onClick={handleLike} bị vô hiệu hóa={isPending}>\n{isLiked ?\'❤️\' : \'🤍\'} {đếm}\n</button>\n);\n}',
    explanation: 'Giao diện người dùng lạc quan cập nhật trạng thái cục bộ trước khi lệnh gọi API hoàn tất, giúp ứng dụng có cảm giác tức thì.Nếu API không thành công, chúng tôi sẽ hoàn nguyên về các giá trị trước đó được lưu trữ trong các biến cục bộ.Cờ isPending ngăn các yêu cầu trùng lặp.Để sản xuất, hãy cân nhắc sử dụng useMutation của React Query với onMutate (cập nhật lạc quan), onError (khôi phục) và onSettled (tải lại).',
  },
  'rp-023': {
    question: 'Xây dựng hook useIntersectionObserver tùy chỉnh và sử dụng nó để triển khai cuộn vô hạn với TanStack Query.',
    answer: 'hàm useIntersectionObserver(\ntùy chọn?: IntersectionObserverInit\n) {\nconst [entry, setEntry] = useState<IntersectionObserverEntry |null>(null);\nconst [nút, setNode] = useState<Element |null>(null);\n\nconst người quan sát = useRef<IntersectionObserver |null>(null);\n\nuseEffect(() => {\nif (observer.current) Observer.current.disconnect();\nif (!node) trả về;\n\nObserver.current = new IntersectionObserver(\n([entry]) => setEntry(entry),\ntùy chọn\n);\nngười quan sát.current.observe(nút);\n\nreturn () => Observer.current?.disconnect();\n}, [nút, tùy chọn?.threshold, tùy chọn?.root, tùy chọn?.rootMargin]);\n\nreturn { ref: setNode, entry, isIntersecting: !!entry?.isIntersecting };\n}\n\n// Cách sử dụng với TanStack Query\nhàm InfinitePostList() {\nconst {\ndữ liệu, tìm nạpNextPage, hasNextPage, isFetchingNextPage, trạng thái,\n} = useInfiniteQuery({\nqueryKey: [\'bài viết\'],\nqueryFn: ({ pageParam = 0 }) =>\ntìm nạp(`/api/posts?cursor=${pageParam}`).then((r) => r.json()),\ngetNextPageParam: (lastPage) => LastPage.nextCursor ??không xác định,\nban đầuPageParam: 0,\n});\n\nconst { ref, isIntersecting } = useIntersectionObserver({\nngưỡng: 0,1,\n});\n\nuseEffect(() => {\nif (isIntersecting && hasNextPage && !isFetchingNextPage) {\ntìm nạpNextPage();\n}\n}, [isIntersecting, hasNextPage, isFetchingNextPage, getNextPage]);\n\nif (trạng thái === \'đang chờ xử lý\') return <Skeleton />;\n\ntrở lại (\n<div>\n{data?.pages.map((page, i) => (\n<Khóa phân đoạn={i}>\n{page.items.map((bài) => (\n<Khóa PostCard={post.id} post={post} />\n))}\n</đoạn>\n))}\n<div ref={ref} style={{ chiều cao: 1 }} />\n{isFetchingNextPage && <Spinner />}\n</div>\n);\n}',
    explanation: 'hook useIntersectionObserver sử dụng mẫu tham chiếu gọi lại (setNode) để xử lý các phần tử động.Khi div canh gác ở phía dưới vào khung nhìn, nó sẽ kích hoạt tìm nạpNextPage.Các điều kiện bảo vệ ngăn chặn việc tìm nạp khi đã tải hoặc khi không còn trang nào nữa.TanStack Query tự động xử lý bộ nhớ đệm, chống trùng lặp và quản lý trang.',
  },
  'rp-024': {
    question: 'Những giá trị nào sẽ được ghi lại khi nút được nhấp một lần?',
    answer: '1',
    explanation: 'Các bản cập nhật useState không đồng bộ — `count` vẫn giữ giá trị đóng cũ (0) khi console.log chạy.Các đột biến useRef là đồng bộ — `countRef.current` ngay lập tức là 1 sau mức tăng.Thành phần này sẽ hiển thị lại với count=1 sau khi trình xử lý sự kiện kết thúc, nhưng nhật ký sẽ ghi lại giá trị trước khi cập nhật.',
  },
  'rp-025': {
    question: 'Triển khai hook usePrevious để theo dõi giá trị trước đó của biến prop hoặc biến trạng thái.Sau đó chỉ ra cách bạn sử dụng nó để tạo hiệu ứng cho bộ đếm khi giá trị thay đổi.',
    answer: 'hàm usePrevious<T>(value: T): T |không xác định {\nconst ref = useRef<T |không xác định>(không xác định);\n\nuseEffect(() => {\nref.current = giá trị;\n});\n\ntrả về ref.current;\n}\n\n// Cách sử dụng: tạo hiệu ứng thay đổi bộ đếm\nhàm AnimatedCounter({ value }: { value: number }) {\nconst prevValue = usePrevious(value);\nconst [animClass, setAnimClass] = useState(\'\');\n\nuseEffect(() => {\nif (prevValue === không xác định) trả về;\nif (giá trị > prevValue) {\nsetAnimClass(\'phản đối\');\n} khác nếu (giá trị < prevValue) {\nsetAnimClass(\'đảo ngược\');\n}\nconst hẹn giờ = setTimeout(() => setAnimClass(\'\'), 300);\nreturn () => clearTimeout(timer);\n}, [giá trị, prevValue]);\n\nreturn <span className={`counter ${animClass}`}>{value</span>;\n}',
    explanation: 'usePrevious tận dụng thực tế là useRef vẫn tồn tại trong các lần kết xuất và useEffect chạy sau khi kết xuất.Trong quá trình kết xuất, ref.current vẫn giữ giá trị cũ.Sau khi kết xuất, hiệu ứng sẽ cập nhật nó lên giá trị mới.Điều này cho phép bạn truy cập vào giá trị của kết xuất trước đó trong quá trình kết xuất hiện tại — hữu ích cho hoạt ảnh dựa trên so sánh, ghi nhật ký thay đổi hoặc logic có điều kiện.',
  },
  'rp-026': {
    question: 'Bạn gọi useState bên trong vòng lặp for để tạo trạng thái cho danh sách đầu vào động.Ứng dụng gặp sự cố với "Kết xuất nhiều móc hơn so với lần hiển thị trước đó".Quy tắc bạn đã phá vỡ là gì?',
    answer: '1',
    explanation: 'React xác định các hook theo thứ tự cuộc gọi của chúng.Nếu số lượng lệnh gọi hook thay đổi giữa các lần hiển thị (ví dụ: một vòng lặp có số lần lặp thay đổi), React không thể khớp các hook với trạng thái trước đó của chúng.Khắc phục: sử dụng một `useState<Record<string, string>>({})` hoặc `useState<string[]>([])` duy nhất để quản lý đầu vào động dưới dạng một phần trạng thái.',
  },
  'rp-027': {
    question: 'Xây dựng hook useMediaQuery trả về xem truy vấn phương tiện CSS có khớp hay không và cập nhật theo thời gian thực khi cửa sổ được thay đổi kích thước.',
    answer: 'hàm useMediaQuery(query: string): boolean {\nconst [khớp, setMatches] = useState(() => {\nif (cửa sổ typeof === \'không xác định\') trả về sai;\ntrả về window.matchMedia(query).matches;\n});\n\nuseEffect(() => {\nconst mediaQuery = window.matchMedia(truy vấn);\nconst handler = (event: MediaQueryListEvent) => setMatches(event.matches);\n\n// Đặt giá trị ban đầu trong trường hợp nó thay đổi giữa kết xuất và hiệu ứng\nsetMatches(mediaQuery.matches);\n\nmediaQuery.addEventListener(\'change\', handler);\nreturn () => mediaQuery.removeEventListener(\'change\', handler);\n}, [truy vấn]);\n\ntrả lại các trận đấu;\n}\n\n// Cách sử dụng\nchức năng Thanh bên() {\nconst isDesktop = useMediaQuery(\'(min-width: 768px)\');\n\ntrả về isDesktop ?<DesktopSidebar /> : <MobileDrawer />;\n}',
    explanation: 'window.matchMedia cung cấp một cách hiệu quả để quan sát các thay đổi truy vấn phương tiện mà không cần bỏ phiếu hoặc lắng nghe sự kiện thay đổi kích thước.Sự kiện "thay đổi" chỉ kích hoạt khi trạng thái khớp thay đổi, khiến nó hoạt động hiệu quả.Trình khởi tạo lười biếng trong useState tránh tình trạng hydrat hóa không khớp trong SSR bằng cách kiểm tra window.Móc này cho phép hành vi phản hồi trong logic JavaScript, bổ sung cho các truy vấn phương tiện CSS.',
  },
  'rp-028': {
    question: 'Bạn có một cây thành phần được lồng sâu (sâu 6 cấp) và cần chia sẻ trạng thái xác thực, chủ đề và ngôn ngữ của người dùng.Bối cảnh vs Redux vs Zustand - khi nào bạn sử dụng cái nào?',
    answer: 'Bối cảnh: Tốt nhất cho các cập nhật tần suất thấp được chia sẻ rộng rãi (chủ đề, ngôn ngữ, trạng thái xác thực).Nó được tích hợp sẵn, không yêu cầu phụ thuộc thêm.Nhược điểm: mọi người tiêu dùng đều hiển thị lại khi giá trị ngữ cảnh thay đổi - giảm thiểu bằng cách phân tách ngữ cảnh (AuthContext, ThemeContext, LocaleContext) và ghi nhớ các giá trị.Bộ công cụ Redux/Redux: Tốt nhất khi bạn cần một bộ chứa trạng thái có thể dự đoán được với phần mềm trung gian (ghi nhật ký, thunk không đồng bộ), gỡ lỗi du hành thời gian hoặc khi nhiều thành phần thường xuyên đọc/ghi cùng một trạng thái.Mẫu bộ chọn (useSelector) ngăn việc hiển thị lại không cần thiết.Đáng giá cho các nhóm lớn được hưởng lợi từ kiến ​​trúc nghiêm ngặt.Zustand: Tốt nhất cho các ứng dụng vừa và nhỏ muốn có các mẫu giống Redux mà không cần bản soạn sẵn.Nó sử dụng các bộ chọn theo mặc định (không có kết xuất lại bổ sung), hoạt động bên ngoài React (vanilla JS) và có bề mặt API tối thiểu.Tuyệt vời cho trạng thái mà nhiều thành phần không liên quan chia sẻ.Nguyên tắc nhỏ: Bắt đầu với Ngữ cảnh.Thêm Zustand khi việc hiển thị lại bối cảnh gặp sự cố.Sử dụng Redux khi bạn cần phần mềm trung gian, công cụ phát triển hoặc nhóm của bạn đã sử dụng nó.',
    explanation: 'Vấn đề "Bối cảnh gây ra quá nhiều lần hiển thị lại" là có thật nhưng thường bị cường điệu hóa.Việc phân tách ngữ cảnh theo tần suất cập nhật và ghi nhớ bằng useMemo sẽ giải quyết được hầu hết các trường hợp.Quyết định này phải dựa vào mức độ quen thuộc của nhóm, kích thước ứng dụng và liệu bạn có cần các tính năng như phần mềm trung gian hay công cụ phát triển hay không.',
  },
  'rp-029': {
    question: 'Hai thành phần anh em cần phải đồng bộ hóa — khi người dùng chọn một mục trong ComponentA, ComponentB sẽ đánh dấu mục đó.Cách tiếp cận đúng đơn giản nhất là gì?',
    answer: '1',
    explanation: 'Nâng trạng thái lên là mô hình cơ bản của React để giao tiếp với anh chị em.Cấp độ gốc giữ trạng thái selectedItem và chuyển nó xuống dưới dạng đạo cụ, cùng với lệnh gọi lại setter.Nếu khoảng cách khoan chống quá sâu, hãy bọc nó trong Ngữ cảnh.Sử dụng localStorage hoặc postMessage cho các thành phần React trên cùng một trang là một kiểu phản mẫu - nó bỏ qua mô hình kết xuất của React và tạo ra các lỗi đồng bộ hóa.',
  },
  'rp-030': {
    question: 'Xây dựng thành phần đồng hồ đếm ngược đơn giản đếm ngược từ một số giây nhất định và hiển thị "Hết giờ!"khi nó đạt đến số không.',
    answer: 'hàm CountdownTimer({ giây }: { giây: số }) {\nconst [timeLeft, setTimeLeft] = useState(giây);\n\nuseEffect(() => {\nif (timeLeft <= 0) trả về;\n\nconst hẹn giờ = setInterval(() => {\nsetTimeLeft((prev) => prev - 1);\n}, 1000);\n\nreturn () => clearInterval(timer);\n}, [timeLeft]);\n\nif (timeLeft <= 0) return <p>Hết giờ!</p>;\n\nconst phút = Math.floor(timeLeft / 60);\nconst giây = timeLeft % 60;\n\ntrở lại (\n<p>\n{mins.toString().padStart(2, \'0\')}:{secs.toString().padStart(2, \'0\')}\n</p>\n);\n}',
    explanation: 'useEffect thiết lập một khoảng thời gian giảm dần timeLeft mỗi giây.Hàm dọn dẹp sẽ xóa khoảng thời gian khi thành phần ngắt kết nối hoặc khi timeLeft thay đổi.Sử dụng biểu mẫu cập nhật `prev => prev - 1` để tránh các sự cố đóng cũ.Khi timeLeft đạt đến 0, lượt quay lại sớm sẽ bỏ qua việc thiết lập khoảng thời gian mới.',
  },
  'rp-031': {
    question: 'Triển khai hook useClickOutside để đóng menu thả xuống khi người dùng nhấp vào bên ngoài nó.',
    answer: 'hàm useClickOutside<T mở rộng HTMLElement>(\ntrình xử lý: () => void\n): RefObject<T |vô giá trị> {\nconst ref = useRef<T |null>(null);\n\nuseEffect(() => {\nhàm xử lýClick(sự kiện: MouseEvent) {\nif (ref.current && !ref.current.contains(event.target as Node)) {\nxử lý();\n}\n}\n\ndocument.addEventListener(\'mousedown\', handClick);\nreturn () => document.removeEventListener(\'mousedown\', handClick);\n}, [trình xử lý]);\n\ntrả lại ref;\n}\n\n// Cách sử dụng\nhàm thả xuống() {\nconst [isOpen, setIsOpen] = useState(false);\nconst close = useCallback(() => setIsOpen(false), []);\nconst dropdownRef = useClickOutside<HTMLDivElement>(close);\n\ntrở lại (\n<div ref={dropdownRef}>\n<button onClick={() => setIsOpen((o) => !o)}>Menu</button>\n{isOpen && (\n<ul className="dropdown-menu">\n<li>Tùy chọn 1</li>\n<li>Tùy chọn 2</li>\n</ul>\n)}\n</div>\n);\n}',
    explanation: 'Móc gắn một trình nghe mousedown vào tài liệu.Khi một cú nhấp chuột xảy ra bên ngoài phần tử ref, nó sẽ gọi trình xử lý.Việc sử dụng mousedown thay vì nhấp chuột sẽ ngăn danh sách thả xuống đóng và mở lại khi nhấp vào nút chuyển đổi (nhấp chuột sẽ kích hoạt sau khi di chuột xuống).Trình xử lý phải được ghi nhớ bằng useCallback để tránh gắn lại trình nghe trên mỗi lần kết xuất.',
  },
  'rp-032': {
    question: 'Móc tùy chỉnh này có nhiệm vụ theo dõi kích thước cửa sổ, nhưng nó gây ra cảnh báo rò rỉ bộ nhớ khi ngắt kết nối thành phần.Tìm lỗi.',
    answer: '1',
    explanation: 'Nếu không dọn dẹp, trình xử lý sự kiện thay đổi kích thước vẫn tiếp tục tồn tại sau khi thành phần được ngắt kết nối, khiến setSize cũ kích hoạt trên thành phần đã bị xóa.Cách khắc phục là trả về một hàm dọn dẹp từ useEffect: `return () => window.removeEventListener("resize", handResize)`.Đây là mẫu rò rỉ bộ nhớ trong sách giáo khoa trong React hook.',
  },
  'rp-033': {
    question: 'Nhóm của bạn đang xây dựng một biểu mẫu phức tạp với hơn 30 trường, xác thực nhiều trường, các phần có điều kiện và điều hướng nhiều bước.Bạn chọn kiến ​​trúc nào?',
    answer: 'Sử dụng React Hook Form + Zod để xác thực lược đồ.Kiến trúc: (1) Xác định các lược đồ Zod theo từng bước, kết hợp chúng thành một lược đồ đầy đủ với z.object().merge().(2) Sử dụng useForm với zodResolver - điều này mang lại cho bạn register(), handSubmit(), formState với các lỗi trên mỗi trường.(3) Nhiều bước: Sử dụng một phiên bản biểu mẫu duy nhất qua các bước.Lưu trữ chỉ mục bước ở trạng thái.Mỗi bước hiển thị các trường của nó có điều kiện.Sử dụng trigger() để chỉ xác thực các trường của bước hiện tại trước khi tiếp tục.(4) Xác thực chéo trường: .refine() và .superRefine() của Zod xử lý "mật khẩu phải khớp với confirmPassword", v.v. (5) Các phần có điều kiện: sử dụng watch() để quan sát các trường kiểm soát và hiển thị/ẩn các trường phụ thuộc.(6) Hiệu suất: React Hook Form sử dụng đầu vào không được kiểm soát theo mặc định - không hiển thị lại mỗi lần nhấn phím.(7) Các thay đổi chưa được lưu: so sánh form.formState.isDirty với trình nghe beforeunload.(8) Kiên trì: lưu các giá trị biểu mẫu vào sessionStorage khi thay đổi bước để khắc phục sự cố.',
    explanation: 'React Hook Form được thiết kế cho các biểu mẫu nhạy cảm với hiệu suất.Nó tránh hiển thị lại toàn bộ biểu mẫu trên mỗi lần nhấn phím (không giống như Formik theo mặc định).Zod cung cấp xác thực thời gian chạy an toàn loại chia sẻ các loại với TypeScript.Đối với hơn 30 trường, sự kết hợp này có quy mô tốt hơn nhiều so với các phương pháp sử dụng Trạng thái trên mỗi trường được cuộn thủ công.',
  },
  'rp-034': {
    question: 'Viết một hook useFetch tùy chỉnh để xử lý các trạng thái tải, lỗi và dữ liệu bằng các generic TypeScript thích hợp.',
    answer: 'gõ FetchState<T> = {\ndữ liệu: T |vô giá trị;\nlỗi: chuỗi |vô giá trị;\nđang tải: boolean;\n};\n\nhàm useFetch<T>(url: string, options?:RequestInit): FetchState<T> {\nconst [trạng thái, setState] = useState<FetchState<T>>({\ndữ liệu: vô giá trị,\nlỗi: vô giá trị,\nđang tải: đúng,\n});\n\nuseEffect(() => {\nbộ điều khiển const = AbortController mới();\nsetState({ data: null, error: null, loading: true });\n\ntìm nạp(url, { ...options, signal: control.signal })\n.then((res) => {\nif (!res.ok) ném Lỗi mới(`HTTP ${res.status}: ${res.statusText}`);\ntrả về res.json() dưới dạng Promise<T>;\n})\n.then((data) => setState({ data, error: null, loading: false }))\n.catch((err) => {\nif (err.name === \'AbortError\') return;\nsetState({ data: null, error: err.message, loading: false });\n});\n\nreturn () => control.abort();\n}, [url]);\n\ntrạng thái trả về;\n}\n\n// Cách sử dụng\nhàm UserProfile({ id }: { id: string }) {\nconst { data: user, loading, error } = useFetch<User>(`/api/users/${id}`);\n\nif (đang tải) trả về <Skeleton />;\nif (lỗi) trả về <Alertvariant="error">{error</Alert>;\nreturn <h1>{user?.name</h1>;\n}',
    explanation: 'Móc này gói gọn mẫu lỗi tìm nạp bằng các tổng quát TypeScript để truy cập dữ liệu an toàn kiểu.Nó sử dụng AbortController để dọn dẹp khi thay đổi hoặc ngắt kết nối URL.Lưu ý: đối với các ứng dụng sản xuất, hãy ưu tiên TanStack Query để bổ sung bộ nhớ đệm, chống trùng lặp, thử lại, cũ trong khi xác nhận lại, v.v.Móc này là một bài tập học tập tốt và phù hợp với các trường hợp sử dụng đơn giản.',
  },
  'rp-035': {
    question: 'Bạn muốn lưu trữ tham chiếu đến phần tử DOM để tập trung vào phần tử đó theo chương trình.Bạn sử dụng móc nào và tại sao?',
    answer: '1',
    explanation: 'useRef trả về một đối tượng có thể thay đổi { current: initValue } tồn tại trong suốt thời gian tồn tại của thành phần.Khi được chuyển đến thuộc tính `ref` của phần tử JSX, React đặt `.current` thành nút DOM.Không giống như useState, việc thay đổi `.current` không kích hoạt kết xuất lại - đó chính xác là những gì bạn muốn để truy cập DOM bắt buộc như lấy nét, cuộn hoặc đo.',
  },
  'rp-036': {
    question: 'Xây dựng biểu mẫu trình hướng dẫn nhiều bước giúp duy trì trạng thái giữa các bước, xác thực từng bước trước khi tiến lên và hiển thị chỉ báo tiến trình.',
    answer: 'const stepSchemas = [\nz.object({ name: z.string().min(1, \'Bắt buộc\'), email: z.string().email() }),\nz.object({ địa chỉ: z.string().min(1, \'Bắt buộc\'), thành phố: z.string().min(1, \'Bắt buộc\') }),\nz.object({ cardNumber: z.string().regex(/^\d{16}$/, \'Phải có 16 chữ số\') }),\n];\n\ngõ FormData = z.infer<typeof stepSchemas[0]> &\nz.infer<typeof stepSchemas[1]> &\nz.infer<typeof stepSchemas[2]>;\n\nhàm Wizard() {\nconst [bước, setStep] = useState(0);\nconst [formData, setFormData] = useState<Partial<FormData>>({});\n\nconst {\nđăng ký, xử lýSubmit, formState: { lỗi }, kích hoạt,\n} = useForm({\ntrình phân giải: zodResolver(stepSchemas[step]),\nGiá trị mặc định: formData,\nchế độ: \'onBlur\',\n});\n\nhàm không đồng bộ handNext(data: Partial<FormData>) {\nsetFormData((prev) => ({ ...prev, ...data }));\nif (bước < stepSchemas.length - 1) {\nsetStep((s) => s + 1);\n} khác {\nđang chờ submitForm({ ...formData, ...data });\n}\n}\n\nconst StepComponent = [Thông tin cá nhân, Địa chỉ, Thanh toán][bước];\n\ntrở lại (\n<div>\n<ProgressBar hiện tại={step} tổng={stepSchemas.length} />\n<biểu mẫu onSubmit={handleSubmit(handleNext)}>\n<StepComponent đăng ký={register} lỗi={errors} />\n<div>\n{bước > 0 && (\n<button type="button" onClick={() => setStep((s) => s - 1)}>\nQuay lại\n</button>\n)}\n<loại nút="gửi">\n{bước === stepSchemas.length - 1 ?\'Gửi\' : \'Tiếp theo\'}\n</button>\n</div>\n</form>\n</div>\n);\n}',
    explanation: 'Trình hướng dẫn lưu trữ dữ liệu biểu mẫu tích lũy trong đối tượng trạng thái gốc.Mỗi bước có lược đồ Zod riêng để xác thực.Ở "Tiếp theo", handSubmit xác thực các trường của bước hiện tại.Nếu hợp lệ, dữ liệu sẽ được hợp nhất vào formData và tiến lên từng bước.Nút "Quay lại" điều hướng mà không cần xác thực.Giá trị mặc định khôi phục dữ liệu nhập trước đó khi quay lại một bước.Để sản xuất, hãy xem xét việc lưu giữ formData sang sessionStorage.',
  },
  'rp-037': {
    question: 'Triển khai hệ thống phương thức hỗ trợ xếp chồng nhiều phương thức, điều hướng bằng bàn phím (Thoát để đóng) và bẫy tiêu điểm.',
    answer: 'const ModalContext = createContext<{\nopen: (nội dung: ReactNode) => chuỗi;\nclose: (id: string) => void;\n}>({ open: () => \'\', close: () => {} });\n\nfunction ModalProvider({ Children }: { Children: ReactNode }) {\nconst [modals, setModals] = useState<{ id: string;nội dung: ReactNode []>([]);\n\nconst open = useCallback((content: ReactNode) => {\nconst id = crypto.randomUUID();\nsetModals((prev) => [...prev, { id, content }]);\ntrả về id;\n}, []);\n\nconst close = useCallback((id: string) => {\nsetModals((prev) => prev.filter((m) => m.id !== id));\n}, []);\n\ntrở lại (\n<ModalContext.Provider value={{ mở, đóng }}>\n{trẻ em}\n{modals.map((modal, chỉ mục) => (\n<Lớp phủ phương thức\nkey={modal.id}\nid={modal.id}\nzIndex={1000 + chỉ mục}\nonClose={() => close(modal.id)}\n>\n{modal.content}\n</ModalOverlay>\n))}\n</ModalContext.Provider>\n);\n}\n\nhàm ModalOverlay({ id, zIndex, onClose, Children }: {\nid: chuỗi;zIndex: số;onClose: () => void;trẻ em: ReactNode;\n}) {\nconst lớp phủRef = useRef<HTMLDivElement>(null);\nconst previousFocus = useRef<HTMLElement |null>(null);\n\nuseEffect(() => {\ntrướcFocus.current = document.activeElement dưới dạng HTMLElement;\n// Tập trung vào phần tử có thể lấy tiêu điểm đầu tiên trong phương thức\nconst có thể tập trung = lớp phủRef.current?.querySelectorAll<HTMLElement>(\n\'nút, [href], đầu vào, chọn, vùng văn bản, [tabindex]:not([tabindex="-1"])\'\n);\ncó thể lấy nét được không?.[0]?.focus();\n\nreturn () => previousFocus.current?.focus();\n}, []);\n\nuseEffect(() => {\nhàm handKeyDown(e: KeyboardEvent) {\nif (e.key === \'Escape\') { onClose();trở lại;}\nif (e.key !== \'Tab\' || !overlayRef.current) return;\n\nconst có thể tập trung = lớp phủRef.current.querySelectorAll<HTMLElement>(\n\'nút, [href], đầu vào, chọn, vùng văn bản, [tabindex]:not([tabindex="-1"])\'\n);\nconst đầu tiên = có thể lấy nét[0];\nconst cuối = có thể lấy nét[focusable.length - 1];\n\nif (e.shiftKey && document.activeElement === đầu tiên) {\ne.preventDefault();cuối cùng?.focus();\n} else if (!e.shiftKey && document.activeElement === cuối cùng) {\ne.preventDefault();đầu tiên?.focus();\n}\n}\ndocument.addEventListener(\'keydown\', handKeyDown);\nreturn () => document.removeEventListener(\'keydown\', handKeyDown);\n}, [onClose]);\n\ntrả về createPortal(\n<div style={{ location: \'fixed\', inset: 0, zIndex }} onClick={onClose}>\n<div\nref={overlayRef}\nvai trò="hộp thoại"\naria-modal="true"\nonClick={(e) => e.stopPropagation()}\n>\n{trẻ em}\n</div>\n</div>,\ntài liệu.body\n);\n}',
    explanation: 'Hệ thống sử dụng ngăn xếp dựa trên ngữ cảnh.Mỗi phương thức có một ID duy nhất và chỉ số z tăng dần để xếp chồng.Chu kỳ bẫy tiêu điểm Tab giữa các phần tử có thể lấy tiêu điểm bên trong phương thức.Khi mở, phần tử được tập trung trước đó sẽ được lưu và khôi phục khi đóng.Escape đóng phương thức trên cùng.createPortal hiển thị các phương thức ở phần nội dung tài liệu để tránh các vấn đề về chỉ mục z và tràn.',
  },
  'rp-038': {
    question: 'Làm cách nào để bạn triển khai chiến lược xử lý lỗi toàn cầu trong ứng dụng React sản xuất bao gồm lỗi kết xuất, lỗi không đồng bộ, lỗi xử lý sự kiện và lỗi API?',
    answer: 'Lớp 1 - Ranh giới lỗi: Bao bọc gốc ứng dụng và từng phần tính năng chính trong Ranh giới lỗi.Những lỗi này phát hiện lỗi thời gian kết xuất và hiển thị giao diện người dùng dự phòng.Sử dụng getDerivedStateFromError để dự phòng, thành phầnDidCatch để ghi nhật ký.Lớp 2 — Trình xử lý sự kiện toàn cầu: Thêm window.addEventListener("error", handler) và window.addEventListener("unhandledrejection", handler) vào điểm nhập ứng dụng để phát hiện các lỗi chưa phát hiện được và lời hứa từ chối.Lớp 3 - Trình chặn lỗi API: Sử dụng trình bao bọc Axios/tìm nạp để bắt lỗi HTTP (4xx/5xx), xử lý 401 (chuyển hướng đến đăng nhập), 403 (hiển thị bị cấm), 500 (hiển thị lỗi chung).Ghép nối với onError của React Query hoặc trình xử lý lỗi chung.Lớp 4 — Try/catch của trình xử lý sự kiện: Bao bọc các trình xử lý sự kiện bằng hàm bậc cao hơn: `const safe = (fn) => (...args) => { try { fn(...args) } Catch(e) { reportError(e) } }`.Lớp 5 - Báo cáo lỗi: Tích hợp Sentry hoặc Datadog RUM.Nắm bắt lỗi, ngăn xếp thành phần, bối cảnh người dùng và đường dẫn.Lớp 6 - Hướng tới người dùng: Thông báo về các lỗi có thể phục hồi, dự phòng toàn trang cho các lỗi nghiêm trọng, nút "Báo cáo sự cố" đính kèm ID lỗi.Lớp 7 - Giám sát: Trang tổng quan về tỷ lệ lỗi, cảnh báo khi tỷ lệ lỗi tăng đột biến, nhóm theo loại lỗi.',
    explanation: 'Không có cơ chế nào có thể bắt được tất cả các lỗi React.Ranh giới lỗi chỉ phát hiện các lỗi hiển thị đồng bộ trong cây con của chúng.Trình xử lý sự kiện, setTimeout, mã không đồng bộ và lỗi kết xuất phía máy chủ phải được xử lý riêng.Cách tiếp cận theo lớp đảm bảo phạm vi bao phủ toàn diện.',
  },
  'rp-039': {
    question: 'Người dùng báo cáo mất dữ liệu biểu mẫu khi vô tình nhấp vào nút quay lại của trình duyệt.Triển khai giải pháp cảnh báo họ trước khi rời đi.',
    answer: 'hàm useUnsavedChangesWarning(hasUnsavedChanges: boolean) {\n// Xử lý tiến/lùi/đóng trình duyệt\nuseEffect(() => {\nif (!hasUnsavedChanges) trả về;\n\nhàm xử lýBeforeUnload(e: BeforeUnloadEvent) {\ne.preventDefault();\n// Chrome yêu cầu phải đặt returnValue\ne.returnValue = \'\';\n}\n\nwindow.addEventListener(\'trướcunload\', handBeforeUnload);\nreturn () => window.removeEventListener(\'trướcunload\', handBeforeUnload);\n}, [hasUnsavedChanges]);\n}\n\n// Với React Router v6 — sử dụng trình chặn\nhàm EditForm() {\nconst [isDirty, setIsDirty] = useState(false);\ntrình chặn const = useBlocker(isDirty);\n\nuseUnsavedChangesWarning(isDirty);\n\nuseEffect(() => {\nif (blocker.state === \'bị chặn\') {\nconst nghỉ = window.confirm(\n\'Bạn có những thay đổi chưa được lưu.Dù sao cũng rời đi?\'\n);\nif (rời) blocker.proceed();\ntrình chặn khác.reset();\n}\n}, [trình chặn]);\n\ntrở lại (\n<form onChange={() => setIsDirty(true)}>\n<tên đầu vào="tiêu đề" />\n<textarea name="body" />\n<button type="submit" onClick={() => setIsDirty(false)}>\nLưu\n</button>\n</form>\n);\n}',
    explanation: 'Hai tình huống cần xử lý: (1) Điều hướng trình duyệt (quay lại, đóng tab, làm mới) - sử dụng sự kiện beforeunload.(2) Định tuyến phía máy khách (Điều hướng Bộ định tuyến React) - sử dụng useBlocker (React Router v6.4+) hoặc hook không ổn định_usePrompt.Hộp thoại trước khi tải được kiểm soát bởi trình duyệt và không thể tùy chỉnh.Để định tuyến phía máy khách, bạn có thể hiển thị một phương thức tùy chỉnh.Tự động lưu vào localStorage/sessionStorage cung cấp một mạng lưới an toàn bổ sung.',
  },
  'rp-040': {
    question: 'Làm cách nào để bạn xử lý việc làm mới mã thông báo xác thực một cách minh bạch trong ứng dụng React để lệnh gọi API không bao giờ thất bại do mã thông báo đã hết hạn theo quan điểm của người dùng?',
    answer: 'Triển khai trình chặn làm mới mã thông báo bằng cách sử dụng trình chặn chặn Axios hoặc trình bao bọc tìm nạp.Kiến trúc: (1) Lưu trữ mã thông báo truy cập (tồn tại trong thời gian ngắn, ~ 15 phút) trong bộ nhớ (biến/trạng thái) và mã thông báo làm mới (tồn tại lâu dài) trong cookie httpOnly.(2) Thêm trình chặn phản hồi Axios: trên 401, xếp hàng yêu cầu không thành công, gọi điểm cuối /refresh, khi cập nhật thành công mã thông báo truy cập và thử lại tất cả các yêu cầu đã xếp hàng đợi, khi chuyển hướng đăng nhập không thành công.(3) Ngăn chặn các điều kiện chạy đua: sử dụng cờ `isRefreshing` - nếu quá trình làm mới đang diễn ra, hãy xếp hàng các yêu cầu 401 tiếp theo và giải quyết chúng khi quá trình làm mới hoàn tất.(4) Làm mới chủ động: kiểm tra thời hạn sử dụng token (giải mã JWT) trước mỗi yêu cầu;nếu nó hết hạn trong vòng 30 giây, hãy làm mới trước.(5) Tích hợp phản ứng: bọc phiên bản Axios trong Ngữ cảnh hoặc hook useApi tùy chỉnh.Sử dụng onError của React Query để xử lý trường hợp "làm mới không thành công" cuối cùng.(6) Đăng xuất khi không làm mới: xóa mã thông báo, chuyển hướng đến đăng nhập, hiển thị thông báo "Phiên đã hết hạn".',
    explanation: 'Làm mới mã thông báo minh bạch là rất quan trọng đối với UX trong SPA.Thách thức chính là xử lý các yêu cầu đồng thời - nhiều lệnh gọi API có thể không thành công với lỗi 401 cùng một lúc.Nếu không có hàng đợi, mỗi cuộc gọi sẽ kích hoạt một cuộc gọi làm mới riêng biệt, điều này có thể làm vô hiệu các cuộc gọi khác.Mẫu hàng đợi đảm bảo chỉ xảy ra một lần làm mới và tất cả các yêu cầu chờ được thử lại bằng mã thông báo mới.',
  },
  'rp-041': {
    question: 'Xây dựng đầu vào tìm kiếm đã được gỡ lỗi hiển thị vòng quay tải trong khi tìm nạp, xử lý các kết quả trống bằng thông báo và hủy các yêu cầu đang thực hiện.',
    answer: 'hàm DebouncedSearch() {\nconst [truy vấn, setQuery] = useState(\'\');\nconst debouncedQuery = useDebounce(query, 300);\nconst [kết quả, setResults] = useState<SearchResult[]>([]);\nconst [đang tải, setLoading] = useState(false);\nconst [đã tìm kiếm, setSearched] = useState(false);\n\nuseEffect(() => {\nif (!debouncedQuery.trim()) {\nsetResults([]);\nsetSearched(false);\nsetLoading(false);\ntrở lại;\n}\n\nbộ điều khiển const = AbortController mới();\nsetLoading(true);\n\ntìm nạp(`/api/search?q=${encodeURIComponent(debouncedQuery)}`, {\ntín hiệu: bộ điều khiển.signal,\n})\n.then((res) => res.json())\n.then((dữ liệu: SearchResult[]) => {\nsetResults(dữ liệu);\nsetSearched(true);\nsetLoading(false);\n})\n.catch((err) => {\nif (err.name !== \'AbortError\') {\nsetLoading(false);\nsetSearched(true);\n}\n});\n\nreturn () => control.abort();\n}, [debouncedQuery]);\n\ntrở lại (\n<div>\n<div className="search-wrapper">\n<đầu vào\ngiá trị={truy vấn}\nonChange={(e) => setQuery(e.target.value)}\nplaceholder="Tìm kiếm..."\n/>\n{đang tải && <Spinner className="input-spinner" />}\n</div>\n{đã tìm kiếm && results.length === 0 && (\n<p className="no-results">\nKhông tìm thấy kết quả nào cho &ldquo;{debouncedQuery}&rdquo;\n</p>\n)}\n<ul>\n{results.map((r) => (\n<li key={r.id}>{r.title</li>\n))}\n</ul>\n</div>\n);\n}',
    explanation: 'Chuỗi thành phần gỡ lỗi → tìm nạp → hiển thị.Cờ `đã tìm kiếm` phân biệt "chưa tìm kiếm" với "đã tìm kiếm và nhận được 0 kết quả".AbortController hủy các yêu cầu đang thực hiện khi truy vấn thay đổi, ngăn chặn các điều kiện tương tranh.Vòng quay tải xuất hiện trong khu vực đầu vào để có phản hồi ngay lập tức.Đối với sản xuất, `useQuery` của TanStack Query với `keepPreviousData` thậm chí còn cung cấp trải nghiệm người dùng mượt mà hơn.',
  },
  'rp-042': {
    question: 'Ứng dụng React của bạn cần hỗ trợ chỉnh sửa cộng tác theo thời gian thực (như Google Docs).Cách tiếp cận kỹ thuật của bạn là gì?',
    answer: 'Chọn thư viện CRDT (Yjs hoặc Automerge) thay vì OT để giải quyết xung đột đơn giản hơn.Kiến trúc: (1) Lớp dữ liệu: Tài liệu Yjs (Y.Text, Y.Map, Y.Array) là nguồn chân lý cho trạng thái cộng tác.(2) Vận chuyển: Kết nối WebSocket thông qua nhà cung cấp y-websocket.Mỗi khách hàng kết nối với một phòng chung.Yjs tự động đồng bộ hóa các khác biệt - không cần logic đồng bộ hóa tùy chỉnh.(3) Liên kết phản ứng: Tạo một hook tùy chỉnh useCollaborativeState đăng ký các thay đổi tài liệu Yjs và kích hoạt kết xuất lại React.Để chỉnh sửa văn bản, hãy sử dụng trình chỉnh sửa nhận biết Yjs như TipTap (với y-prosemirror) hoặc Slate.(4) Nhận thức: Sử dụng giao thức nhận thức của Yjs để hiển thị vị trí con trỏ, sự hiện diện của người dùng và các điểm nổi bật của lựa chọn trong thời gian thực.(5) Tính kiên trì: Phía máy chủ, duy trì trạng thái tài liệu Yjs vào cơ sở dữ liệu trên mỗi bản cập nhật (đã được phát hành).Khi kết nối lại, nhà cung cấp Yjs sẽ đồng bộ hóa từ trạng thái liên tục.(6) Hỗ trợ ngoại tuyến: Yjs hoạt động ngoại tuyến - các thay đổi được xếp hàng đợi và hợp nhất khi kết nối lại thông qua các thuộc tính CRDT (giao hoán, tính bình thường).(7) Dành riêng cho phản ứng: Bao bọc tài liệu cộng tác trong Ngữ cảnh.Sử dụng useSyncExternalStore để đăng ký các thay đổi của Yjs một cách hiệu quả.',
    explanation: 'CRDT (Loại dữ liệu được sao chép không xung đột) đảm bảo tính nhất quán cuối cùng mà không cần cơ quan trung ương, khiến chúng trở nên lý tưởng cho việc chỉnh sửa cộng tác.Yjs là thư viện CRDT hoàn thiện nhất dành cho JavaScript.Thách thức chính về tích hợp React là kết nối mô hình có thể quan sát được của Yjs với chu trình kết xuất của React - useSyncExternalStore là nguyên thủy chính xác cho việc này.',
  },
  'rp-043': {
    question: 'Bạn cần hiển thị 5.000 điểm đánh dấu trên bản đồ trong React.Mỗi điểm đánh dấu cần một trình xử lý nhấp chuột.Sau khi lập hồ sơ, bạn thấy sự hòa giải của React chính là điểm nghẽn.Tối ưu hóa nào là hiệu quả nhất?',
    answer: '1',
    explanation: 'Với 5.000 thành phần, ngay cả React.memo cũng có chi phí so sánh nông cạn trên mỗi kết xuất gốc.Ủy quyền sự kiện làm giảm đáng kể số lượng nút DOM và số lượng thành phần React.Đối với các kịch bản bản đồ: hiển thị điểm đánh dấu trên lớp Canvas hoặc SVG với một phần tử vùng chứa duy nhất và tính toán điểm đánh dấu nào được nhấp vào từ tọa độ sự kiện.Các thư viện như deck.gl và Reac-map-gl sử dụng phương pháp này.Ngoài ra, hãy nhóm các điểm đánh dấu gần đó thành các nhóm có thể mở rộng khi thu phóng.',
  },
  'rp-044': {
    question: 'Triển khai thành phần React hiển thị bảng dữ liệu với các cột có thể sắp xếp, trong đó việc nhấp vào tiêu đề cột sẽ sắp xếp theo cột đó và chuyển đổi giữa tăng dần/giảm dần.',
    answer: 'gõ SortDirection = \'asc\' |\'desc\';\ngõ SortConfig = { key: string;hướng: SortDirection } |vô giá trị;\n\nhàm SortableTable<T mở rộng Bản ghi<chuỗi, không xác định>>({\ndữ liệu,\ncột,\n}: {\ndữ liệu: T[];\ncột: { key: keyof T & string;nhãn: chuỗi [];\n}) {\nconst [sortConfig, setSortConfig] = useState<SortConfig>(null);\n\nconst được sắp xếpData = useMemo(() => {\nif (!sortConfig) trả về dữ liệu;\nconst { key, Direction } = SortConfig;\nreturn [...data].sort((a, b) => {\nconst aVal = a[key];\nconst bVal = b[key];\nif (aVal == null) trả về 1;\nif (bVal == null) trả về -1;\nconst cmp = aVal < bVal ?-1 : aVal > bVal ?1: 0;\nhướng quay lại === \'asc\'?cmp : -cmp;\n});\n}, [dữ liệu, sắp xếpConfig]);\n\nhàm xử lýSort(key: string) {\nsetSortConfig((prev) => {\nif (prev?.key === key) {\ntrả về prev.direction === \'asc\'\n?{ phím, hướng: \'desc\' }\n: vô giá trị;// đặt lại lần nhấp chuột thứ ba\n}\nreturn { key, Direction: \'asc\' };\n});\n}\n\ntrở lại (\n<bảng>\n<đầu>\n<tr>\n{columns.map((col) => (\n<th\nkey={col.key}\nonClick={() => handSort(col.key)}\nstyle={{ con trỏ: \'con trỏ\' }}\naria-sắp={\nSortConfig?.key === col.key\n?SortConfig.direction === \'asc\'\n?\'tăng dần\'\n: \'giảm dần\'\n: \'không có\'\n}\n>\n{col.label}\n{sortConfig?.key === col.key && (\n<span>{sortConfig.direction === \'asc\' ?\' ▲\' : \' ▼\'</span>\n)}\n</th>\n))}\n</tr>\n</thead>\n<tbody>\n{sortedData.map((row, i) => (\n<tr phím={i}>\n{columns.map((col) => (\n<td key={col.key}>{Chuỗi(row[col.key] ?? \'\')</td>\n))}\n</tr>\n))}\n</tbody>\n</bảng>\n);\n}',
    explanation: 'Việc sắp xếp được tính toán thông qua useMemo - chỉ được tính toán lại khi dữ liệu hoặc cấu hình sắp xếp thay đổi.Chu kỳ ba lần nhấp chuột (chưa sắp xếp → tăng dần → giảm dần → chưa sắp xếp) là một mẫu UX phổ biến.aria-sort cung cấp khả năng truy cập.Đối với các tập dữ liệu lớn, hãy cân nhắc việc sắp xếp phía máy chủ hoặc thư viện như TanStack Table để xử lý việc sắp xếp, lọc, phân trang và ảo hóa.',
  },
  'rp-045': {
    question: 'Thành phần này sử dụng React.memo nhưng vẫn hiển thị lại mỗi khi thành phần gốc hiển thị.Bảng điều khiển hiển thị "Kết xuất con" trên mỗi thay đổi trạng thái gốc.Tìm lỗi.',
    answer: '1',
    explanation: 'React.memo thực hiện so sánh nông cạn các đạo cụ.`{ color: "red", fontSize: 16 }` là một tham chiếu đối tượng mới mỗi lần hiển thị (mặc dù các giá trị giống hệt nhau) và hàm mũi tên nội tuyến cũng là một tham chiếu mới.Sửa: `const style = useMemo(() => ({ color: "red", fontSize: 16 }), [])` và `const handClick = useCallback(() => console.log("clicked"), [])`.Ngoài ra, hãy xác định đối tượng kiểu bên ngoài thành phần nếu nó thực sự tĩnh.',
  },
  'rp-046': {
    question: 'Bạn đang xây dựng một trang tổng quan với 20 tiện ích, mỗi tiện ích tìm nạp dữ liệu riêng.Trang này mất 8 giây để tương tác.Làm thế nào để bạn tối ưu hóa trải nghiệm tải?',
    answer: 'Chiến lược 1 - Tải lũy tiến với Hồi hộp: Bao bọc từng tiện ích trong ranh giới Hồi hộp bằng một khung dự phòng.Các tiện ích quan trọng (KPI, cảnh báo) được ưu tiên cao hơn;các tiện ích phụ (biểu đồ, báo cáo) có thể truyền vào. Chiến lược 2 - Tối ưu hóa lớp dữ liệu: Sử dụng TanStack Query với staleTime để lưu trữ dữ liệu tiện ích vào bộ nhớ đệm.Bật tính năng tìm nạp trước khi di chuột điều hướng trên trang tổng quan.Loại bỏ các lệnh gọi API giống hệt nhau.Chiến lược 3 — Tìm nạp dữ liệu song song: Đảm bảo các tiện ích tìm nạp dữ liệu song song, không phải tuần tự (lỗi thường gặp với hiệu ứng sử dụng thác nước).Sử dụng Promise.all hoặc để TanStack Query xử lý tính song song.Chiến lược 4 - Phân tách mã: Các thành phần tiện ích nặng tải chậm (thư viện biểu đồ, lưới dữ liệu).Chỉ tải mã khi tiện ích cuộn vào chế độ xem bằng IntersectionObserver.Chiến lược 5 - Hiển thị phía máy chủ: Kết xuất trước vỏ bảng điều khiển và dữ liệu tiện ích quan trọng trên máy chủ.Truyền phát phần còn lại khi nó có sẵn.Chiến lược 6 - Ảo hóa: Nếu các tiện ích nằm trong lưới có thể cuộn, chỉ hiển thị các tiện ích hiển thị.Chiến lược 7 - Màn hình khung: Hiển thị bố cục trang tổng quan ngay lập tức với các khung, thay thế từng khung khi dữ liệu đến.Điều này cải thiện đáng kể hiệu suất cảm nhận.',
    explanation: 'Nguyên tắc cốt lõi là: hiển thị nội dung nào đó hữu ích càng sớm càng tốt.Người dùng nhận thấy một trang có màn hình khung tải dần dần nhanh hơn trang có một vòng quay duy nhất, ngay cả khi tổng thời gian tải là như nhau.Ưu tiên nội dung trong màn hình đầu tiên.',
  },
  'rp-047': {
    question: 'Triển khai mẫu thành phần phức hợp cho thành phần Tab trong đó API trông giống như: <Tabs><Tab label="A">Content A</Tab><Tab label="B">Content B</Tab></Tabs>',
    answer: 'const TabsContext = createContext<{\nactiveIndex: số;\nsetActiveIndex: (i: số) => void;\n} |null>(null);\n\nhàm useTabsContext() {\nconst ctx = useContext(TabsContext);\nif (!ctx) ném ra Lỗi mới(\'Tab phải được sử dụng trong Tab\');\ntrả lại ctx;\n}\n\nchức năng Tabs({ defaultIndex = 0, Children }: {\nchỉ số mặc định?: số;\ntrẻ em: ReactNode;\n}) {\nconst [activeIndex, setActiveIndex] = useState(defaultIndex);\nconst tabs = Children.toArray(children) as ReactElement<TabProps>[];\n\ntrở lại (\n<TabsContext.Provider value={{ activeIndex, setActiveIndex }}>\n<div role="tablist" className="tab-headers">\n{tabs.map((tab, chỉ mục) => (\n<nút\nkhóa={chỉ mục}\nvai trò="tab"\naria-selected={activeIndex === chỉ mục}\nclassName={activeIndex === chỉ mục?\'tab đang hoạt động\' : \'tab\'}\nonClick={() => setActiveIndex(index)}\n>\n{tab.props.label}\n</button>\n))}\n</div>\n<div role="tabpanel" className="tab-content">\n{tabs[activeIndex]?.props.children}\n</div>\n</TabsContext.Provider>\n);\n}\n\ngiao diện TabProps {\nnhãn: chuỗi;\ntrẻ em: ReactNode;\n}\n\nchức năng Tab({ trẻ em }: TabProps) {\ntrả về <>{con</>;\n}\n\n// Cách sử dụng\n<Tab defaultIndex={0}>\n<Tab label="Profile">Nội dung hồ sơ tại đây</Tab>\n<Tab label="Settings">Nội dung cài đặt tại đây</Tab>\n<Tab label="Billing">Nội dung thanh toán tại đây</Tab>\n</Tab>',
    explanation: 'Mẫu thành phần phức hợp cung cấp cho người dùng một API khai báo rõ ràng đồng thời gói gọn việc quản lý trạng thái phức tạp.Tab sở hữu trạng thái hoạt động và đọc Tab con để xây dựng các nút tiêu đề.Chỉ nội dung của tab đang hoạt động mới được hiển thị.Ngữ cảnh đảm bảo các thành phần phụ có thể giao tiếp với thành phần chính.Các vai trò ARIA (danh sách tab, tab, bảng tab, aria được chọn) cung cấp khả năng truy cập.',
  },
  'rp-048': {
    question: 'Ứng dụng React của nhóm bạn đã phát triển lên hơn 200 thành phần và quá trình xây dựng mất 45 giây.Kinh nghiệm của nhà phát triển đang bị ảnh hưởng.Bạn thực hiện những bước nào để cải thiện DX?',
    answer: 'Hiệu suất xây dựng: (1) Chuyển từ CRA/Webpack sang Vite - nó sử dụng ESM gốc trong nhà phát triển và chỉ chuyển đổi các tệp theo yêu cầu (khởi động nguội trong <1 giây so với 30 giây+).(2) Kích hoạt bộ nhớ đệm liên tục trong gói.(3) Định cấu hình TypeScript với "incremental: true" và tham chiếu dự án cho các monorepos lớn.(4) Sử dụng SWC hoặc esbuild thay vì Babel để dịch mã nhanh hơn.Tổ chức mã: (5) Thực thi phân tách mã tại các ranh giới tuyến đường bằng React.lazy.(6) Chia khối nguyên khối thành các gói trong monorepo (Turborepo/Nx) với bộ nhớ đệm bản dựng độc lập.(7) Thiết lập tính năng linting tệp thùng để ngăn chặn việc vô tình nhập toàn bộ gói.Công cụ phát triển: (8) Định cấu hình ESLint chỉ với các quy tắc cần thiết và sử dụng cấu hình phẳng để tăng tốc.(9) Sử dụng lint-staged + Husky để xác nhận trước — chỉ các tệp đã thay đổi lint.(10) Thêm thư viện thành phần với Storybook để phát triển riêng biệt.(11) Thiết lập MSW (Mock Service Worker) để mô phỏng API để bỏ chặn việc phát triển giao diện người dùng.Kiểm tra: (12) Sử dụng Vitest thay vì Jest để thực hiện kiểm tra nhanh hơn (ESM gốc, HMR).(13) Song song hóa các bản dựng CI trên các gói.',
    explanation: 'Các vấn đề về DX phức tạp - việc xây dựng chậm dẫn đến chuyển đổi ngữ cảnh, dẫn đến lỗi, dẫn đến tốc độ chậm hơn.Thay đổi ROI cao nhất thường là chuyển sang Vite (thường cắt thời gian khởi động máy chủ dev từ 30 giây xuống <2 giây).Sau đó, xử lý biểu đồ phụ thuộc (tệp thùng, phân tách mã) và đường dẫn CI.',
  },
  'rp-049': {
    question: 'Bạn đang hiển thị một biểu mẫu lớn với 50 đầu vào được kiểm soát.Việc nhập bất kỳ thông tin đầu vào nào đều gây ra độ trễ đáng chú ý vì toàn bộ biểu mẫu sẽ hiển thị lại sau mỗi lần nhấn phím.Cách tiếp cận nào mang lại sự cải thiện hiệu suất tốt nhất?',
    answer: '1',
    explanation: 'Với 50 đầu vào được kiểm soát, mỗi lần nhấn phím sẽ cập nhật trạng thái, hiển thị lại toàn bộ thành phần biểu mẫu (và tất cả 50 đầu vào).Đầu vào không được kiểm soát với useRef tránh điều này - DOM quản lý trạng thái đầu vào bên trong và React không được tham gia cho đến khi gửi biểu mẫu.React Hook Form sử dụng cách tiếp cận này theo mặc định thông qua register().Cách thay thế: chia đầu vào thành các thành phần phụ riêng biệt, mỗi thành phần có trạng thái sử dụng riêng, do đó chỉ có đầu vào gõ mới hiển thị lại.',
  },
  'rp-050': {
    question: 'Triển khai thành phần bậc cao hơn (HOC) có tên withAuth để chuyển hướng người dùng chưa được xác thực đến trang đăng nhập và hiển thị vòng quay tải trong khi kiểm tra trạng thái xác thực.',
    answer: 'hàm withAuth<P mở rộng đối tượng>(WrappedComponent: ComponentType<P>) {\nhàm AuthGuard(props: P) {\nconst { người dùng, đang tải } = useAuth();\nconst điều hướng = useNavigate();\n\nuseEffect(() => {\nif (!loading && !user) {\nđiều hướng(\'/đăng nhập\', {\nthay thế: đúng,\ntrạng thái: { từ: window.location.pathname },\n});\n}\n}, [người dùng, đang tải, điều hướng]);\n\nnếu (đang tải) {\ntrở lại (\n<div className="auth-loading">\n<Con Quay />\n<p>Xác minh xác thực...</p>\n</div>\n);\n}\n\nif (!user) trả về null;// Chuyển hướng\n\nreturn <WrappedComponent {...props} />;\n}\n\nAuthGuard.displayName = `withAuth(${\nWrappedComponent.displayName ||WrappedComponent.name ||\'Thành phần\'\n})`;\n\ntrả về AuthGuard;\n}\n\n// Cách sử dụng\nconst ProtectedDashboard = withAuth(Dashboard);\n\n// Trong các tuyến đường:\n<Route path="/dashboard" element={<ProtectedDashboard />} />',
    explanation: 'Mẫu HOC bao bọc một thành phần bằng logic xác thực.Nó kiểm tra trạng thái xác thực từ hook useAuth (được hỗ trợ bởi Context).Trong khi tải, nó hiển thị một vòng quay.Nếu không được xác thực, nó sẽ chuyển hướng đến /login với đường dẫn hiện tại ở trạng thái (đối với chuyển hướng sau đăng nhập).Việc gán displayName giúp gỡ lỗi React DevTools.Giải pháp thay thế hiện đại: sử dụng thành phần bố cục ProtectedRoute với <Outlet /> của React Router thay vì HOC.',
  },
}
